Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2019-04, with the labels that each got.

#142 Split up base input to smaller components
  docs/storybook/base.md
  src/components/TemplateCourseTimes.vue
  src/components/ui/BaseInput.unit.js
  src/components/ui/BaseInput.vue
  src/components/ui/BaseInput/BaseInput.unit.js
  src/components/ui/BaseInput/BaseInput.vue
  src/components/ui/BaseInput/BaseInputCalendar.vue
  src/components/ui/BaseInput/BaseInputCheckbox.unit.js
  src/components/ui/BaseInput/BaseInputCheckbox.vue
  src/components/ui/BaseInput/BaseInputDefault.unit.js
  src/components/ui/BaseInput/BaseInputDefault.vue
  src/components/ui/BaseInput/BaseInputHidden.unit.js
  src/components/ui/BaseInput/BaseInputHidden.vue
  src/components/ui/BaseInput/BaseInputRadio.unit.js
  src/components/ui/BaseInput/BaseInputRadio.vue
  src/components/ui/BaseSelect.vue
  src/components/ui/_globals.js
  src/themes/default/styles/index.scss
  src/themes/default/styles/variables/_sizes.scss
  stories/base.stories.js
  tests/unit/commonTests.js
  yarn.lock
Labels: refactoring

#106 First draft of Development Workflow/Guidelines
  .github/issue_template.md
  docs/0-GettingStarted/3-Workflow.md
Labels: WIP, waiting

#149 add mergify documentation
  .travis.yml
  README.md
  deploy.sh
  docs/0-GettingStarted/4-Workflow.md
  docs/2-Tools.md
Labels: ready to merge

#153 #39 Allow merge flag only after approval
  .mergify.yml
Labels: ready to merge

#156 remove .vue from imports
  _templates/new/component/stories.ejs.t
  docs/3-FAQ.md
  src/components/CardFooter.vue
  src/components/CourseCard.vue
  src/components/Courses.vue
  src/components/TemplateCourseWizard.vue
  src/components/TemplateLandingCTA.vue
  src/components/ui/BaseBreadcrumb.vue
  src/components/ui/BaseInput/BaseInput.vue
  src/layouts/default.vue
  src/pages/content/index.vue
  stories/CourseCard.stories.js
  stories/TemplateTabs.stories.js
  stories/base.stories.js
  stories/misc.stories.js
Labels: refactoring

#158 chore(package): update prettier to version 1.17.0
  docs/0-GettingStarted/1-Build.md
  package.json
  src/components/ui/BaseIcon.vue
  yarn.lock
Labels: ready to merge

#164 some small theme changes
  docs/.vuepress/config.js
  docs/.vuepress/override.styl
  docs/0-GettingStarted/0-Development.md
  docs/0-GettingStarted/9-EditorSetup.md
  docs/1-Tutorials/APIRequests.md
  docs/1-Tutorials/StorybookDokuErstellen.md
  docs/2-Tools.md
Labels: ready to merge

#152 #86 add tests to all base components
  src/components/ui/BaseDialog/BaseDialog.vue
  src/components/ui/BaseInput/BaseInput.vue
  src/components/ui/BaseInput/BaseInputCalendar.vue
  src/components/ui/BaseInput/BaseInputCheckbox.unit.js
  src/components/ui/BaseInput/BaseInputCheckbox.vue
  src/components/ui/BaseInput/BaseInputDefault.vue
  src/components/ui/BaseInput/BaseInputHidden.unit.js
  src/components/ui/BaseInput/BaseInputHidden.vue
  src/components/ui/BaseInput/BaseInputRadio.vue
  src/components/ui/BaseModal.unit.js
  src/components/ui/BaseModal.vue
  src/components/ui/BaseSelect.unit.js
  src/components/ui/BaseSelect.vue
  src/components/ui/BaseVideo.unit.js
  stories/base.stories.js
Labels: bug, ready to merge, refactoring

#157 #88 refactor course template
  .eslintrc.js
  src/assets/icons/delete.svg
  src/components/CourseTimes.vue
  src/components/CourseWizard/StepData.unit.js
  src/components/CourseWizard/StepData.vue
  src/components/CourseWizard/StepDone.vue
  src/components/CourseWizard/StepMembers.unit.js
  src/components/CourseWizard/StepMembers.vue
  src/components/CourseWizard/index.unit.js
  src/components/CourseWizard/index.vue
  src/components/LandingCTA.vue
  src/components/StepProgress.unit.js
  src/components/TemplateCourseWizard.vue
  src/components/ui/BaseButton.vue
  src/components/ui/BaseInput/BaseInput.vue
  src/components/ui/BaseModal.unit.js
  src/components/ui/BaseSelect.vue
  src/components/ui/BaseTextarea.unit.js
  src/components/ui/BaseTextarea.vue
  src/layouts/default.vue
  src/pages/courses/create.vue
  stories/Onboarding.stories.js
  stories/base.stories.js
  yarn.lock
Labels: ready to merge, refactoring

#167 simply mergify config and update documentation
  .mergify.yml
  docs/2-Tools.md
  docs/CodeStyleguide.md
Labels: ready to merge

#71 #42 deploy cleanup
  .dockerignore
  .travis.yml
  deploy/Dockerfile.fast.nuxt
  deploy/Dockerfile.fast.storybook
  deploy/Dockerfile.fast.vuepress
  deploy/Dockerfile.nuxt
  deploy/Dockerfile.storybook
  deploy/Dockerfile.vuepress
  deploy/compose-nuxt.dummy
  deploy/compose-storybook.dummy
  deploy/compose-vuepress.dummy
  deploy/deploy.sh
  deploy/travis_rsa.enc
Labels: ready to merge, refactoring
