Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2019-08, with the labels that each got.

#247 Vue 63/permission component
  docs/storybook/UserHas.md
  src/components/UserHasPermission.unit.js
  src/components/UserHasPermission.vue
  src/components/UserHasRole.unit.js
  src/components/UserHasRole.vue
  stories/.storybook/config.js
  stories/.storybook/store.js
  stories/UserHas.stories.js
  tests/unit/setup.js
  yarn.lock
Labels: ready to merge, size/L

#248 yarn => npm
  .gitignore
  .travis.yml
  .vscode/settings.json
  deploy/Dockerfile.nuxt
  deploy/Dockerfile.storybook
  deploy/Dockerfile.vuepress
  docs/0-GettingStarted/0-Development.md
  docs/0-GettingStarted/1-Build.md
  docs/1-Tutorials/HygenTemplateErstellen.md
  docs/1-Tutorials/KomponentenErstellen.md
  docs/1-Tutorials/StorybookDokuErstellen.md
  docs/1-Tutorials/TestsSchreiben.md
  docs/4-Tools.md
  docs/storybook/README.md
  lint-staged.config.js
  package-lock.json
  package.json
  startup.sh
  yarn.lock
Labels: ready to merge

#245 Update stable
  .gitignore
  .travis.yml
  .vscode/settings.json
  deploy/Dockerfile.nuxt
  deploy/Dockerfile.storybook
  deploy/Dockerfile.vuepress
  docs/.vuepress/config.js
  docs/0-GettingStarted/0-Development.md
  docs/0-GettingStarted/1-Build.md
  docs/1-Tutorials/HygenTemplateErstellen.md
  docs/1-Tutorials/KomponentenErstellen.md
  docs/1-Tutorials/StorybookDokuErstellen.md
  docs/1-Tutorials/TestsSchreiben.md
  docs/4-Tools.md
  docs/storybook/README.md
  docs/storybook/UserHas.md
  lint-staged.config.js
  package-lock.json
  package.json
  src/components/UserHasPermission.unit.js
  src/components/UserHasPermission.vue
  src/components/UserHasRole.unit.js
  src/components/UserHasRole.vue
  startup.sh
  stories/.storybook/config.js
  stories/.storybook/store.js
  stories/UserHas.stories.js
  tests/unit/setup.js
  yarn.lock
Labels: ready to merge, size/M

#250 hotfix - API_URL
  nuxt.config.js
Labels: ready to merge, size/XS

#251 remove some packages
  package-lock.json
  package.json
Labels: size/XS

#254 update deployment scripts
  .travis.yml
  deploy/Dockerfile.client
  deploy/Dockerfile.fast.storybook
  deploy/Dockerfile.fast.vuepress
  deploy/compose-client.dummy
  deploy/compose-storybook.dummy
  deploy/compose-vuepress.dummy
  deploy/deploy.sh
  deploy/pull-deploy.sh
Labels: size/L

#230 AW/Top and Sidebar - Adaption to current client style
  .gitignore
  jest.config.js
  package-lock.json
  package.json
  src/assets/img/logo/logo-image-mono.svg
  src/assets/img/logo/logo-transparent-mono-48-48.svg
  src/components/CourseCard/index.vue
  src/components/DropdownMenu.vue
  src/components/HelpDropdown.unit.js
  src/components/HelpDropdown.vue
  src/components/MenuLink.vue
  src/components/MenuQrCode.unit.js
  src/components/MenuQrCode.vue
  src/components/PopupIcon.unit.js
  src/components/PopupIcon.vue
  src/components/PopupIconInitials.unit.js
  src/components/PopupIconInitials.vue
  src/components/TheSidebar.unit.js
  src/components/TheSidebar.vue
  src/components/TheTopBar.unit.js
  src/components/TheTopBar.vue
  src/components/UserHasPermission.vue
  src/components/UserHasRole.unit.js
  src/components/UserHasRole.vue
  src/components/UserRole.unit.js
  src/components/UserRole.vue
  src/components/ui/BaseIcon.unit.js
  src/components/ui/BaseIcon.vue
  src/components/ui/BaseLink.vue
  src/components/ui/BaseQrCode.unit.js
  src/components/ui/BaseQrCode.vue
  src/layouts/default.vue
  src/pages/administration/index.vue
  src/pages/administration/students.vue
  src/pages/login.vue
  src/plugins/global.js
  src/store/README.md
  src/store/auth.js
  src/themes/brb/assets/img/logo/logo-image-mono.svg
  src/themes/default/styles/variables/_sizes.scss
  src/themes/default/styles/variables/_typography.scss
  src/themes/open/assets/img/logo/logo-image-mono.svg
  src/utils/sidebarBaseItems.js
  stories/base.stories.js
  stories/misc.stories.js
Labels: ready to merge, size/XXL

#262 forgot to push (top and sidebar)
  src/components/PopupIconInitials.vue
  src/components/TheTopBar.vue
Labels: size/XS
