Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2019-12, with the labels that each got.

#379 add margin bottom to inputs
  src/components/base/BaseInput/BaseInput.stories.js
  src/components/base/BaseInput/BaseInput.vue
Labels: ready to merge, size/M

#380 remove border from date picker
  src/components/base/BaseInput/BaseInput.stories.js
  src/components/base/BaseInput/BaseInputCalendar.vue
Labels: ready to merge, size/M

#374 validate params.id to be a valid mongoId
  src/pages/news/_id/index.vue
Labels: ready to merge, size/XS

#384 add badges for deployments
  README.md
Labels: ready to merge, size/S

#383 adapted focus styles for buttons and general elements
  src/components/base/BaseButton.scss
  src/themes/default/styles/utility.scss
Labels: ready to merge, size/M

#382 feature/multi os tests
  .github/workflows/test.yml
  .mergify.yml
  .travis.yml
  src/components/molecules/CourseTimes.unit.js
Labels: ready to merge, size/M

#387 disable news detail page
  src/serverMiddleware/routes.js
Labels: size/XS

#376 Add BaseDialog Confirm
  package-lock.json
  package.json
  src/components/base/BaseDialog/BaseDialog.stories.js
  src/components/base/BaseDialog/BaseDialog.unit.js
  src/components/base/BaseDialog/BaseDialog.vue
  src/components/base/BaseDialog/index.unit.js
  src/components/base/BaseModal.stories.js
  src/components/molecules/ModalBodyInfo.vue
  src/themes/default/styles/utility/_typography.scss
  stories/base.stories.js
  tests/unit/setup.js
Labels: ready to merge, size/L

#389 hotfix/staging-deploy - add $SYSTEM to api url
  deploy/compose-client_brb.dummy
  deploy/compose-client_default.dummy
  deploy/compose-client_n21.dummy
  deploy/compose-client_open.dummy
Labels: ready to merge, size/XS

#390 feature/single proxy error
  docs/0-GettingStarted/1-Build.md
  src/serverMiddleware/proxy.js
Labels: ready to merge, size/S

#366 Getting store data in Course View
  src/pages/courses/_id/index.vue
  src/store/course-groups.js
  src/store/homeworks.js
  src/store/lessons.js
Labels: ready to merge, size/M

#353 add news create & edit page
  .eslintrc.js
  .travis.yml
  jest.config.js
  locale/de.json
  src/components/legacy/PopupIconInitials.vue
  src/components/legacy/TheTopBar.vue
  src/components/molecules/FormActions.stories.js
  src/components/molecules/FormActions.unit.js
  src/components/molecules/FormActions.vue
  src/components/molecules/TextEditor.unit.js
  src/components/molecules/TextEditor.vue
  src/components/organisms/FormNews.stories.js
  src/components/organisms/FormNews.unit.js
  src/components/organisms/FormNews.vue
  src/pages/news/_id/edit.vue
  src/pages/news/_id/index.vue
  src/pages/news/index.vue
  src/pages/news/new.vue
  src/serverMiddleware/routes.js
  src/store/auth.js
  tests/general.unit.js
  tests/unit/setup.js
Labels: ready to merge, size/XXL

#395 remove padding from BaseCard and add it to other components which nee…
  src/components/base/BaseCard.vue
  src/components/molecules/CourseCard/index.vue
  src/pages/schools.vue
  src/pages/teams/index.vue
Labels: ready to merge, size/S

#394 Feature/sc 2844 create news production ready
  locale/de.json
  src/components/base/BaseInput/BaseInput.stories.js
  src/components/base/BaseInput/BaseInputDefault.vue
  src/components/molecules/TextEditor.vue
  src/components/organisms/FormNews.vue
  src/pages/news/new.vue
  src/plugins/directives.js
Labels: ready to merge, size/L

#345 Vue lern store
  locale/de.json
  locale/en.json
  src/components/molecules/ContentCard.unit.js
  src/components/molecules/ContentCard.vue
  src/components/molecules/ContentEmptyState.unit.js
  src/components/molecules/ContentEmptyState.vue
  src/components/molecules/Searchbar.vue
  src/mixins/infiniteScrolling.js
  src/pages/content/index.vue
  src/serverMiddleware/routes.js
  src/static/empty-state/emptyStateSvg_teacher_female.svg
  src/static/empty-state/emptyStateSvg_teacher_female_hand_raised.svg
  src/static/empty-state/emptyStateSvg_teacher_male.svg
  src/static/empty-state/emptyStateSvg_teacher_male_hand_down.svg
  src/store/content.js
  src/utils/multiline-ellipsis.scss
Labels: ready to merge, size/XXL

#403 Fix Linter CI
  .github/workflows/test.yml
  jest.config.js
  src/components/molecules/TextEditor.vue
  src/components/organisms/FormNews.unit.js
  tests/general.unit.js
Labels: size/S

#402 extend Lokalise Tutorial
  docs/1-Tutorials/Localization.md
Labels: size/M

#397 Feature/sc 2273 mint ec willkommenspaket
  locale/de.json
  locale/en.json
  package-lock.json
  package.json
  src/assets/img/logo/logo-image-color.svg
  src/assets/img/mint-ec-ghost/by-sa.svg
  src/components/base/BaseLink.vue
  src/components/legacy/LegacyFooter.stories.js
  src/components/legacy/LegacyFooter.unit.js
  src/components/legacy/LegacyFooter.vue
  src/components/legacy/NavigationBar.stories.js
  src/components/legacy/NavigationBar.unit.js
  src/components/legacy/NavigationBar.vue
  src/components/molecules/MintEcFooter.unit.js
  src/components/molecules/MintEcFooter.vue
  src/components/molecules/MintEcLinkContainer.stories.js
  src/components/molecules/MintEcLinkContainer.unit.js
  src/components/molecules/MintEcLinkContainer.vue
  src/components/molecules/MintEcPageHeader.stories.js
  src/components/molecules/MintEcPageHeader.unit.js
  src/components/molecules/MintEcPageHeader.vue
  src/components/molecules/RenderHtmlMintEc.unit.js
  src/components/molecules/RenderHtmlMintEc.vue
  src/components/organisms/DropdownMenu.vue
  src/layouts/loggedoutFullWidth.vue
  src/pages/courses/index.vue
  src/pages/mint-ec/_article.vue
  src/serverMiddleware/routes.js
  src/store/ghost.js
  src/themes/default/styles/utility/_spacing.scss
  src/themes/default/styles/utility/_typography.scss
  src/themes/default/styles/variables/_breakpoints.scss
  src/themes/default/styles/variables/_colors.scss
  src/themes/default/styles/variables/_typography.scss
Labels: ready to merge, size/XXL

#411 Fix typos
  docs/4-Tools.md
Labels: docs, size/XS

#410 Feature/#201 surge teardown
  .github/workflows/surge-teardown.yml
  package-lock.json
Labels: ready to merge, size/S

#416 cleanup vscode config
  .vscode/settings.json
Labels: size/M
