Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2019-10, with the labels that each got.

#283 Update TestsSchreiben.md
  docs/1-Tutorials/TestsSchreiben.md
Labels: size/XS

#294 VUE-74 - Footer from legacy client
  src/components/TheFooter.unit.js
  src/components/TheFooter.vue
  src/store/auth.js
  src/utils/documents.js
Labels: ready to merge, size/L

#304 Demo User Banner Component
  .nvmrc
  package-lock.json
  src/components/legacy/DemoBanner.vue
  src/layouts/default.vue
  src/plugins/authenticate.js
  src/store/auth.js
  stories/misc.stories.js
Labels: ready to merge, size/M

#308 Feature/text editor
  jest.config.js
  package-lock.json
  package.json
  src/components/molecules/TextEditor.stories.js
  src/components/molecules/TextEditor.unit.js
  src/components/molecules/TextEditor.vue
  stories/.storybook/config.js
Labels: ready to merge

#313 add proxy error page
  src/components/templates/ErrorPage.unit.js
  src/components/templates/ErrorPage.vue
  src/layouts/loggedout.vue
  src/pages/error/proxy.vue
  src/plugins/authenticate.js
  src/plugins/authenticate.unit.js
  src/serverMiddleware/proxy.js
  src/serverMiddleware/routes.js
Labels: ready to merge, size/M

#302 VUE-75 Base Modals
  src/components/base/BaseButton.vue
  src/components/base/BaseDialog/BaseDialog.vue
  src/components/base/BaseModal.unit.js
  src/components/base/BaseModal.vue
  src/components/molecules/ModalBodyInfo.unit.js
  src/components/molecules/ModalBodyInfo.vue
  src/components/molecules/ModalFooter.unit.js
  src/components/molecules/ModalFooter.vue
  src/components/molecules/ModalFooterActions.unit.js
  src/components/molecules/ModalFooterActions.vue
  src/components/molecules/ModalFooterBorder.unit.js
  src/components/molecules/ModalFooterBorder.vue
  src/components/molecules/ModalFooterConfirm.unit.js
  src/components/molecules/ModalFooterConfirm.vue
  stories/Modals.stories.js
  stories/base.stories.js
Labels: ready to merge, size/M

#310 General UI Layout Cleanup (TopNav, SideNav, Footer)
  docs/0-GettingStarted/1-Build.md
  nuxt.config.js
  src/components/legacy/TheFooter.vue
  src/components/legacy/TheSidebar.vue
  src/components/legacy/TheTopBar.vue
  src/layouts/default.vue
  src/store/auth.js
  src/utils/sidebarBaseItems.js
Labels: ready to merge, size/M

#317 VUE-86 Loading spinner
  .prettierrc.js
  src/components/base/BaseSpinner.unit.js
  src/components/base/BaseSpinner.vue
  stories/base.stories.js
Labels: ready to merge, size/L

#314 add integration test runs
  .travis.yml
  .vscode/settings.json
  startup.sh
Labels: ready to merge, size/S

#318 added vue-swatches package, including story in storybook
  docs/storybook/ColorPicker.md
  package-lock.json
  package.json
  src/components/atoms/ColorPicker.stories.js
  src/components/atoms/ColorPicker.unit.js
  src/components/atoms/ColorPicker.vue
Labels: ready to merge, size/M

#311 Impressum page
  src/components/base/BaseLink.vue
  src/pages/impressum.vue
  src/serverMiddleware/routes.js
  src/themes/default/styles/utility/_typography.scss
Labels: ready to merge, size/S

#321 add sentry error logging
  deploy/compose-client.dummy
  docs/0-GettingStarted/1-Build.md
  nuxt.config.js
  package-lock.json
  package.json
  sentry.config.js
  src/plugins/sentry.js
Labels: ready to merge

#322 Build All Themes on Travis
  .travis.yml
Labels: ready to merge, size/S

#325 Lokalise: Translations update
  locale/de.json
  locale/en.json
Labels: size/S

#326 Lokalise: Translations update
  locale/de.json
  locale/en.json
Labels: size/M

#327 Lokalise: Translations update
  locale/de.json
  locale/en.json
Labels: size/XS

#330 Feature/template cleanup
  _templates/new/component/component.ejs.t
  _templates/new/component/doc.ejs.t
  _templates/new/component/prompt.js
  _templates/new/component/stories.ejs.t
  _templates/new/component/unit.ejs.t
  docs/1-Tutorials/APIRequests.md
  src/store/classes.js
  src/store/content-search.js
  src/store/courses.js
  src/store/federal-states.js
  src/store/news.js
  src/store/public-teachers.js
  src/store/roles.js
  src/store/schools.js
  src/store/teams.js
  src/store/users.js
Labels: size/M
