Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2019-11, with the labels that each got.

#324 Feature/themed deployment
  .travis.yml
  deploy/build.sh
  deploy/buildAndDeployFilter.sh
  deploy/compose-client_brb.dummy
  deploy/compose-client_default.dummy
  deploy/compose-client_n21.dummy
  deploy/compose-client_open.dummy
  deploy/decryptSecrets.sh
  deploy/deploy.sh
Labels: ready to merge

#320 Fix Course Creation Wizard
  src/components/base/BaseSelect.vue
  src/components/molecules/CourseTimes.unit.js
  src/components/molecules/CourseTimes.vue
  src/components/organisms/CourseWizard/StepData.unit.js
  src/components/organisms/CourseWizard/StepData.vue
  src/components/organisms/CourseWizard/StepDone.vue
  src/components/organisms/CourseWizard/StepMembers.unit.js
  src/components/organisms/CourseWizard/StepMembers.vue
  src/components/organisms/CourseWizard/index.unit.js
  src/components/organisms/CourseWizard/index.vue
  src/pages/courses/create.vue
  src/store/users.js
Labels: ready to merge, size/XL

#228 VUE-54 - Styling der Inputkomponenten
  docs/1-Tutorials/TestsSchreiben.md
  src/assets/icons/create.svg
  src/assets/icons/invisible.svg
  src/assets/icons/success.svg
  src/assets/icons/visible.svg
  src/assets/icons/warning.svg
  src/components/base/BaseBlockquote.unit.js
  src/components/base/BaseButton.unit.js
  src/components/base/BaseCard.unit.js
  src/components/base/BaseInput/BaseInput.stories.js
  src/components/base/BaseInput/BaseInput.unit.js
  src/components/base/BaseInput/BaseInput.vue
  src/components/base/BaseInput/BaseInputCalendar.vue
  src/components/base/BaseInput/BaseInputCheckbox.unit.js
  src/components/base/BaseInput/BaseInputCheckbox.vue
  src/components/base/BaseInput/BaseInputDefault.unit.js
  src/components/base/BaseInput/BaseInputDefault.vue
  src/components/base/BaseInput/BaseInputRadio.vue
  src/components/base/BaseLink.unit.js
  src/components/base/BaseModal.unit.js
  src/components/base/BaseTextarea.stories.js
  src/components/base/BaseTextarea.unit.js
  src/components/base/BaseTextarea.vue
  src/components/legacy/PopupIcon.unit.js
  src/components/legacy/PopupIconInitials.unit.js
  src/components/organisms/DropdownMenu.unit.js
  src/mixins/userIsTabbing.js
  src/mixins/userIsTabbing.unit.js
  src/themes/default/styles/variables/_sizes.scss
  stories/base.stories.js
  tests/unit/commonTests.js
Labels: ready to merge, size/XL

#335 Feature/nuxt version
  docs/5-FAQ/0-Issues.md
  docs/5-FAQ/5-Setup.md
  git-info.js
  nuxt.config.js
  src/pages/impressum.vue
  src/pages/imprint.vue
Labels: ready to merge, size/M

#332 Feature/vue 120/theming for instances
  src/components/templates/impressum.vue
  src/pages/impressum.vue
  src/themes/brb/assets/img/logo/logo-image-mono.svg
  src/themes/brb/assets/img/logo/logo-transparent-mono-48-48.svg
  src/themes/brb/components/legacy/TheFooter.vue
  src/themes/brb/components/templates/impressum.vue
  src/themes/n21/assets/img/logo/logo-image-mono.png
  src/themes/n21/assets/img/logo/logo-image-mono.svg
  src/themes/n21/assets/img/logo/logo-transparent-mono-48-48.svg
  src/themes/n21/components/legacy/TheFooter.vue
  src/themes/n21/components/templates/impressum.vue
  src/themes/n21/styles/variables.scss
  src/themes/n21/styles/variables/_colors.scss
  src/themes/open/assets/img/logo/logo-image-mono.svg
  src/themes/open/components/legacy/TheFooter.vue
  src/themes/open/styles/variables/_colors.scss
  src/themes/open/templates/impressum.vue
Labels: ready to merge

#338 add page permission check
  docs/1-Tutorials/Localization.md
  docs/1-Tutorials/PagePermissionCheck.md
  jest.config.js
  locale/de.json
  locale/en.json
  nuxt.config.js
  src/middleware/permission-check.js
  tests/middleware/permission-check.unit.js
Labels: ready to merge, size/L

#339 Vue 87/rework course index grid
  locale/de.json
  locale/en.json
  src/components/base/BaseGrid.stories.js
  src/components/base/BaseGrid.unit.js
  src/components/base/BaseGrid.vue
  src/components/base/BaseTitle.stories.js
  src/components/base/BaseTitle.unit.js
  src/components/base/BaseTitle.vue
  src/components/molecules/CourseCard/CourseCardFooter.unit.js
  src/components/molecules/CourseCard/CourseCardFooter.vue
  src/components/molecules/CourseCard/index.unit.js
  src/components/molecules/CourseCard/index.vue
  src/components/molecules/CoursesGrid.unit.js
  src/components/molecules/CoursesGrid.vue
  src/layouts/default.vue
  src/layouts/legacyLoggedIn.vue
  src/pages/courses/index.vue
  src/store/users.js
  src/themes/default/styles/variables/_breakpoints.scss
  src/utils/TestUtil.js
  stories/CourseCard.stories.js
Labels: ready to merge, size/XL

#346 Simple FAB button
  docs/storybook/molecules/FloatingFab.md
  src/components/atoms/PulsatingDot.stories.js
  src/components/base/BaseButton.vue
  src/components/base/BaseGrid.stories.js
  src/components/base/BaseGrid.vue
  src/components/base/BaseIcon.vue
  src/components/base/BaseTextarea.stories.js
  src/components/base/BaseTitle.stories.js
  src/components/molecules/CourseCard/index.vue
  src/components/molecules/FloatingFab.stories.js
  src/components/molecules/FloatingFab.unit.js
  src/components/molecules/FloatingFab.vue
  src/components/molecules/Searchbar.stories.js
  src/layouts/default.vue
  src/pages/content/index.vue
  src/pages/courses/create.vue
  src/pages/courses/index.vue
  src/pages/news/_id/edit.vue
  src/pages/news/_id/index.vue
  src/pages/news/index.vue
  src/pages/news/new.vue
  src/pages/nuxtversion.vue
  src/pages/teams/index.vue
  src/themes/default/styles/variables/_layers.scss
  stories/CourseCard.stories.js
  stories/Onboarding.stories.js
  stories/ProgressRing.stories.js
  stories/base.stories.js
  stories/misc.stories.js
Labels: ready to merge, size/L

#354 cherrypick from #351 and #353
  src/components/base/BaseBreadcrumb.vue
Labels: ready to merge, size/XS

#355 button hotfix from #301
  src/components/base/BaseButton.unit.js
  src/components/base/BaseButton.vue
Labels: ready to merge, size/S

#356 select first Tab if no selection predefined
  src/components/organisms/Tabs/Tabs.vue
Labels: ready to merge, size/XS

#357 cherrypick menubutton hotfix from #301
  src/components/legacy/TheTopBar.vue
Labels: ready to merge, size/XS

#351 improve storybook template
  _templates/new/component/doc.ejs.t
  _templates/new/component/prompt.js
  _templates/new/component/stories.ejs.t
Labels: ready to merge, size/S

#350 add prettier paths to config
  .vscode/settings.json
Labels: ready to merge, size/XS

#361 changed /impressum route to /imprint
  src/components/legacy/TheFooter.vue
  src/pages/imprint.vue
  src/serverMiddleware/routes.js
  src/themes/brb/components/legacy/TheFooter.vue
  src/themes/n21/components/legacy/TheFooter.vue
  src/themes/open/components/legacy/TheFooter.vue
Labels: ready to merge

#362 Reorganizing Code-Base, Stories, Components, etc.
  docs/storybook/TemplateTabs.md
  src/components/atoms/CardTab.unit.js
  src/components/atoms/CardTab.vue
  src/components/atoms/ProfilePicture.stories.js
  src/components/atoms/Tab.unit.js
  src/components/atoms/Tab.vue
  src/components/base/BaseCard.vue
  src/components/base/BaseGrid.stories.js
  src/components/base/BaseTextarea.stories.js
  src/components/base/BaseTitle.stories.js
  src/components/molecules/CourseCard/index.unit.js
  src/components/molecules/CourseCard/index.vue
  src/components/molecules/LandingCTA.stories.js
  src/components/molecules/LandingCTA.vue
  src/components/organisms/StepProgress.stories.js
  src/components/organisms/Tabs/Tabs.stories.js
  src/components/organisms/Tabs/Tabs.unit.js
  stories/CourseCard.stories.js
  stories/Onboarding.stories.js
  stories/TemplateTabs.stories.js
  stories/base.stories.js
  stories/misc.stories.js
Labels: ready to merge

#358 plugins directory restructuring
  src/plugins/directives.js
  src/plugins/filter.js
  src/plugins/filter.unit.js
  src/plugins/global.js
  stories/.storybook/mockComponents.js
Labels: ready to merge, size/M

#359 Vue-22 news detail page
  locale/de.json
  src/pages/news/_id/index.vue
  src/serverMiddleware/routes.js
Labels: ready to merge, size/M

#349 add release info to sentry error logging
  sentry.config.js
  src/plugins/sentry.js
Labels: ready to merge, size/XS

#352 add sort example for news service
  docs/1-Tutorials/APIRequests.md
Labels: ready to merge, size/S

#363 added the fab to news index
  src/pages/news/index.vue
Labels: ready to merge, size/XS

#364 fixing fullscreen mode
  src/layouts/legacyLoggedIn.vue
Labels: ready to merge, size/XS

#367 removed duplicate line of code
  src/layouts/legacyLoggedIn.vue
Labels: ready to merge, size/XS

#368 Always Upload integration-test report
  .travis.yml
Labels: size/XS

#369 changed link handling fab button
  src/pages/courses/index.vue
  src/pages/news/index.vue
Labels: ready to merge, size/S

#371 add RenderHtml Component
  docs/storybook/helpers/RenderHtml.md
  src/components/helpers/RenderHtml.stories.js
  src/components/helpers/RenderHtml.unit.js
  src/components/helpers/RenderHtml.vue
  stories/UserHas.stories.js
Labels: ready to merge, size/L

#372 Update default values
  docs/0-GettingStarted/1-Build.md
Labels: ready to merge, size/XS

#375 Feature/ButtonLink
  src/components/base/BaseButton.scss
  src/components/base/BaseButton.unit.js
  src/components/base/BaseButton.vue
  src/components/base/BaseLink.vue
  src/components/legacy/TheSidebar.vue
  src/components/molecules/FloatingFab.vue
  src/pages/courses/index.vue
  src/pages/news/_id/index.vue
  src/pages/news/index.vue
Labels: ready to merge, size/L
