Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2019-07, with the labels that each got.

#215 VUE-55 StepProgressBar für R-G-Schwäche angepasst
  src/components/StepProgress.vue
Labels: ready to merge

#227 Update pull_request_template.md
  .github/pull_request_template.md
Labels: ready to merge

#238 updated travis config
  .travis.yml
Labels: size/XS

#240 added docker credentials
  deploy/deploy.sh
Labels: size/XS

#241 fix yarn start script, added login to fallback and redirect protectio…
  package.json
  src/server/routes.js
  src/store/auth.js
Labels: ready to merge, size/XS

#242 update stable
  deploy/deploy.sh
  package.json
  src/server/routes.js
  src/store/auth.js
Labels: ready to merge, size/XS

#232 use travis build stages
  .travis.yml
  docs/.vuepress/config.js
  package.json
  yarn.lock
Labels: ready to merge, size/M

#243 Adding Docker Deploy Config
  deploy/Dockerfile.nuxt
  startup.sh
Labels: ready to merge, size/S
