Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2019-09, with the labels that each got.

#266 change font-weight for headlines to normal
  src/themes/default/styles/utility/_typography.scss
Labels: size/XS

#267 corrected storybook labels
  stories/typography.stories.js
Labels: size/S

#263 Documentation Update
  docs/1-Tutorials/APIRequests.md
Labels: ready to merge, size/L

#268 Feature/vue 68 adapt spacings
  src/components/CourseCard/CourseCardFooter.vue
  src/components/CourseCard/index.vue
  src/components/CourseTimes.vue
  src/components/CourseWizard/index.vue
  src/components/PopupIcon.vue
  src/components/PopupIconInitials.vue
  src/components/ui/BaseButton.vue
  src/components/ui/BaseTable.vue
  src/themes/default/styles/utility/_spacing.scss
  src/themes/default/styles/utility/_typography.scss
  src/themes/default/styles/variables/_spacing.scss
Labels: ready to merge, size/M

#273 adjust setup docs
  docs/0-GettingStarted/0-Development.md
Labels: size/XS

#271 Common issue documentation
  docs/5-FAQ.md
Labels: size/XS

#269 new story template
  _templates/new/story/component.ejs.t
  _templates/new/story/prompt.js
  docs/1-Tutorials/StorybookDokuErstellen.md
Labels: ready to merge, size/S

#279 Greenkeeper/vuepress 1.1.0
  package-lock.json
  package.json
Labels: size/XS

#274 VUE-40/Farbpalette
  aliases.config.js
  src/components/ui/BaseBreadcrumb.vue
  src/components/ui/BaseButton.vue
  src/components/ui/BaseInput/BaseInputCheckbox.vue
  src/components/ui/BaseInput/BaseInputRadio.vue
  src/themes/brb/styles/variables/_colors.scss
  src/themes/default/styles/variables/_colors.scss
  src/themes/default/styles/variables/_shadows.scss
  src/themes/n21/styles/variables/_colors.scss
  src/themes/open/styles/variables/_colors.scss
  stories/Colors.stories.js
  stories/base.stories.js
  stories/components/Color.vue
  stories/components/ColorOnText.vue
  stories/components/Elevation.vue
  stories/components/Gradient.vue
Labels: ready to merge, size/L

#281 'feature/vue 80/breadcrump
  src/components/ui/BaseBreadcrumb.unit.js
  src/components/ui/BaseBreadcrumb.vue
  stories/base.stories.js
Labels: ready to merge, size/L

#282 Update routes.js
  src/serverMiddleware/routes.js
Labels: size/XS
