Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2020-08, with the labels that each got.

#1210 SC-5938 - Quickfix uncheck registrierunglink by default
  src/components/organisms/FormCreateUser.vue
Labels: size/XS, waiting for review

#1189 SC-5882 - fix lernstore modal
  locale/de.json
  src/components/base/BaseModal.stories.js
  src/components/molecules/AddContentModal.vue
  src/components/molecules/LoadingModal.unit.js
  src/components/molecules/LoadingModal.vue
  src/components/organisms/AddContentButton.vue
  src/store/content.js
Labels: auto update, size/L, waiting for review

#1198 SC-5906 - fix icon on content card
  src/components/organisms/ContentCard.vue
Labels: ready to merge, size/XS

#1196 SC-5876 - restored the column data row
  src/pages/administration/students/index.vue
Labels: size/XS, waiting for review

#1197 Quickfix - print system instead of $1
  deploy/deploy.sh
Labels: ready to merge, size/XS

#1215 SC-5962 - Refresh table after deleting a teacher
  src/pages/administration/teachers/index.vue
Labels: ready to merge, size/XS

#1217 OPS-1014 - Change hotfix deployments for storybook and vuepress to the rigt stack
  deploy/deploy.sh
Labels: ready to merge, size/XS

#1216 SC-5742 - replaced the settings icons
  src/assets/icons/settings.svg
Labels: size/XS

#1167 SC-5543 - implement register link QR service
  locale/de.json
  locale/en.json
  src/pages/administration/students/index.vue
  src/store/users.js
Labels: auto update, ready to merge, size/M

#1247 Quickfix - increase threshold for search
  src/components/molecules/ContentSearchbar.vue
Labels: size/XS

#933 SC-5537 - move consent to user object
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
  tests/screenshot/__image_snapshots__/6-organisms-content-contentcard-contentcard_1-snap.png
Labels: auto update, size/S

#1149 SC-5665 - Change user creation/deletion to admin route
  src/components/organisms/FormCreateUser.unit.js
  src/components/organisms/FormCreateUser.vue
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
  src/store/users.js
  src/utils/service-template.js
Labels: size/M

#1266 Change domain names for blogs and email
  CHANGELOG.md
  http-headers.config.js
  locale/de.json
  locale/en.json
  package-lock.json
  package.json
  src/components/legacy/NavigationBar.stories.js
  src/components/legacy/NavigationBar.unit.js
  src/components/templates/CommonTermsOfUse.vue
  src/components/templates/impressum.vue
  src/pages/mint-ec/_article.vue
  src/themes/brb/components/templates/impressum.vue
  src/themes/n21/components/templates/CommonTermsOfUse.vue
  src/themes/open/templates/impressum.vue
  src/themes/thr/components/templates/impressum.vue
  src/utils/navbarBaseItems.js
  tests/screenshot/__image_snapshots__/6-organisms-content-contentcard-contentcard_1-snap.png
Labels: size/M

#1264 SC-6022 - Follow up: Column 'Einverständnis' has to be renamed to 'Re…
  CHANGELOG.md
  src/pages/administration/teachers/index.vue
Labels: ready to merge, size/XS

#1270 SC-6324 - quickfix add isExternal check to icon and hint
  src/pages/administration/teachers/index.vue
Labels: size/S

#1272 SC-5213 - move admin/helpdesk to helpdesk
  src/components/molecules/AdminTableLegend.vue
  src/utils/sidebarBaseItems.js
Labels: size/XS

#1254 SC-3515 - restore sort button infobox modal
  src/components/organisms/DataTable/TableHeadRow.vue
  src/pages/administration/students/index.vue
  tests/screenshot/__image_snapshots__/6-organisms-datatable-backenddatatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable-with-filters_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable_1-snap.png
Labels: ready to merge, size/L

#1285 SC-6095 - Add demo theme and adjust footer
  locale/de.json
  src/themes/demo/components/legacy/TheFooter.vue
  src/themes/demo/config.js
  src/themes/demo/styles/index.scss
  src/themes/demo/styles/utility.scss
  src/themes/demo/styles/utility/_breakpoints.scss
  src/themes/demo/styles/utility/_colors.scss
  src/themes/demo/styles/utility/_fonts.scss
  src/themes/demo/styles/utility/_resets.scss
  src/themes/demo/styles/utility/_spacing.scss
  src/themes/demo/styles/utility/_typography.scss
  src/themes/demo/styles/variables.scss
Labels: size/XL
