Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2020-04, with the labels that each got.

#758 AdminTables are not showing Edit Actions when externally managed anymore
  src/pages/administration/students/index.vue
Labels: size/S

#799 refactoring/controllableData Mixin
  CHANGELOG.md
  docs/1-Tutorials/OptionalyPropControllableData.md
  jsconfig.template.js
  src/components/organisms/DataTable/BackendDataTable.stories.js
  src/components/organisms/DataTable/BackendDataTable.unit.js
  src/components/organisms/DataTable/BackendDataTable.vue
  src/components/organisms/DataTable/DataTable.unit.js
  src/components/organisms/DataTable/DataTable.vue
  src/components/organisms/DataTable/TableHeadRow.stories.js
  src/components/organisms/DataTable/TableHeadRow.vue
  src/mixins/controllableData.js
  src/mixins/controllableData.unit.js
  src/utils/formatting.js
  src/utils/formatting.unit.js
Labels: ready to merge, size/L

#823 SC-3866/fixed teachers consent status
  locale/de.json
  src/pages/administration/teachers/index.vue
Labels: ready to merge, size/S

#806 Feature/SC-3638 Filter UI changes
  src/assets/icons/filter.svg
  src/components/organisms/DataFilter/DataFilter.stories.js
  src/components/organisms/DataFilter/DataFilter.vue
  src/components/organisms/DataFilter/DataFilterChips.stories.js
  src/components/organisms/DataFilter/DataFilterChips.vue
  src/components/organisms/DataFilter/DataFilterModal.vue
  src/components/organisms/DataFilter/DataFilterSelect.stories.js
  src/components/organisms/DataFilter/DataFilterSelect.vue
  src/components/organisms/DataTable/DataTable.data-factory.js
Labels: ready to merge, size/L

#827 docs: tutorial "Expendable Form"
  docs/1-Tutorials/ExpendableForm.md
Labels: ready to merge, size/M

#826 dependabot/Bump tiptap in bulk from x.x.6 to x.x.7
  package-lock.json
  package.json
  tests/screenshot/__image_snapshots__/4-base-ui-components-modals-autologout-warning_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datafilter-datafilter_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datafilter-datafilterchips_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datafilter-datafilterselect_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable-with-filters_1-snap.png
Labels: dependencies, waiting for review

#822 [SC-3823] Add event bus; refactoring autoLogout
  docs/1-Tutorials/HowToUseEventBus.md
  src/components/organisms/AutoLogoutWarning.unit.js
  src/components/organisms/AutoLogoutWarning.vue
  src/plugins/eventBus.js
  src/plugins/global.js
  src/store/autoLogout.js
Labels: proposal, ready to merge, size/L

#821 added class column to admin table
  locale/de.json
  src/pages/administration/teachers/index.vue
Labels: ready to merge, size/XS

#637 Vue-58 Add filter component to DataTable
  src/components/organisms/DataTable/DataTable.stories.js
Labels: ready to merge, size/XS

#844 Feature/SC-3889/Pagination-UI
  src/components/organisms/Pagination.unit.js
  src/components/organisms/Pagination.vue
Labels: ready to merge

#845 Changed Icons in TableHead Component
  src/components/organisms/DataTable/BackendDataTable.unit.js
  src/components/organisms/DataTable/TableHeadRow.vue
Labels: ready to merge, size/S

#847 SC-3910 | show floating action button only if user has permission to create/import student/teacher
  src/mixins/UserHasPermission.js
  src/pages/administration/students/index.vue
  src/pages/administration/students/new.vue
  src/pages/administration/teachers/index.vue
  src/pages/administration/teachers/new.vue
  src/utils/sidebarBaseItems.js
Labels: ready to merge, size/M

#846 implement sorting of admin tables
  src/components/organisms/DataTable/BackendDataTable.unit.js
  src/components/organisms/DataTable/BackendDataTable.vue
  src/components/organisms/DataTable/TableHeadRow.vue
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
Labels: ready to merge, size/M

#851 SC-3930 - fix navigation error for import page
  src/components/molecules/FabIcon.vue
Labels: ready to merge

#850 SC-3856 | Icon style in a selected table row
  src/components/organisms/DataTable/BackendDataTable.vue
  src/components/organisms/DataTable/TableDataRow.vue
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
Labels: ready to merge, size/S

#852 #140 storybook theme
  package-lock.json
  package.json
  stories/.storybook/main.js
  stories/.storybook/manager.js
  stories/.storybook/preview.js
  stories/.storybook/theme.js
Labels: ready to merge, size/M

#853 CS | Cleanup
  locale/de.json
  src/components/organisms/DataTable/BackendDataTable.unit.js
  src/components/organisms/DataTable/DataTable.unit.js
  src/components/organisms/Pagination.stories.js
  src/components/organisms/Pagination.unit.js
  src/components/organisms/Pagination.vue
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
Labels: proposal, ready to merge, size/M

#820 Feature/SC-3638/inputs for filter modal
  package-lock.json
  package.json
  src/components/base/BaseInput/BaseInputCalendar.vue
  src/components/molecules/ModalFooter.unit.js
  src/components/molecules/ModalFooter.vue
  src/components/molecules/ModalFooterActions.unit.js
  src/components/molecules/ModalFooterBorder.unit.js
  src/components/molecules/NewsCard.vue
  src/components/organisms/DataFilter/DataFilter.md
  src/components/organisms/DataFilter/DataFilterChips.vue
  src/components/organisms/DataFilter/DataFilterModal.stories.js
  src/components/organisms/DataFilter/DataFilterModal.vue
  src/components/organisms/DataFilter/DataFilterSelect.vue
  src/components/organisms/DataFilter/inputs/Checkbox.stories.js
  src/components/organisms/DataFilter/inputs/Checkbox.unit.js
  src/components/organisms/DataFilter/inputs/Checkbox.vue
  src/components/organisms/DataFilter/inputs/Default.stories.js
  src/components/organisms/DataFilter/inputs/Default.unit.js
  src/components/organisms/DataFilter/inputs/Default.vue
  src/components/organisms/DataFilter/inputs/Inputs.md
  src/components/organisms/DataFilter/inputs/Radio.stories.js
  src/components/organisms/DataFilter/inputs/Radio.unit.js
  src/components/organisms/DataFilter/inputs/Radio.vue
  src/components/organisms/DataTable/BackendDataTable.vue
  src/components/organisms/DataTable/DataTable.data-factory.js
  tests/screenshot/__image_snapshots__/6-organisms-datafilter-datafiltermodal_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datafilter-inputs-checkbox_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datafilter-inputs-default_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datafilter-inputs-radio_1-snap.png
Labels: ready to merge, size/L

#859 changed import icon
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
Labels: ready to merge

#858 skip role fetch for user create
  src/components/organisms/FormCreateUser.vue
Labels: ready to merge, size/S

#856 Feature/SC-3931/filter einbauen
  locale/de.json
  src/components/base/BaseInput/BaseInputCalendar.vue
  src/components/organisms/DataFilter/DataFilter.vue
  src/components/organisms/DataFilter/feathersQueryGenerator.js
  src/components/organisms/DataFilter/feathersQueryGenerator.unit.js
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
  src/utils/adminFilter.js
  tests/unit/__snapshots__/components/organisms/DataFilter/feathersQueryGenerator.unit.js.snap
Labels: ready to merge, size/XL

#864 SC-3687 | added missing support for i18n on administration pages
  locale/de.json
  src/components/molecules/AdminTableLegend.vue
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
Labels: ready to merge, size/M

#836 webuntis fixes
  locale/de.json
  src/components/base/BaseIcon.vue
  src/components/base/BaseInput/BaseInput.stories.js
  src/components/base/BaseInput/BaseInputDefault.vue
  src/components/base/BaseTextarea.vue
  src/components/organisms/DataTable/BackendDataTable.unit.js
  src/components/organisms/DataTable/BackendDataTable.vue
  src/components/organisms/DataTable/DataTable.unit.js
  src/components/organisms/DatasourceRunWebuntis.vue
  src/components/organisms/FormDatasourceLoginWebuntis.vue
  src/pages/administration/datasources/_datasource/run/_run.vue
  src/pages/administration/datasources/index.vue
  src/pages/administration/datasources/new.vue
  src/pages/administration/datasources/webuntis/_id/edit.vue
  tests/screenshot/__image_snapshots__/4-base-ui-components-base-ui-base-breadcrumb_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-base-ui-base-icon_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-base-ui-base-select_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-base-ui-basetextarea_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-checkbox-array_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-date_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-default-default_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-default-disabled_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-default-error_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-default-success_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-default-title-input_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-default-with-icon_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-multiple_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-switch-array_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-time_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datafilter-inputs-default_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-backenddatatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable-with-filters_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tableheadrow_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-formcreateuser_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-formdatasourcelogin_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-pagination_1-snap.png
Labels: ready to merge

#879 SC-3877 | updated admintable sync hint
  locale/de.json
  src/components/molecules/AdminTableLegend.vue
Labels: ready to merge

#857 data privacy footer changes
  src/components/legacy/TheFooter.unit.js
  src/components/legacy/TheFooter.vue
  src/themes/brb/components/legacy/TheFooter.vue
  src/themes/open/components/legacy/TheFooter.vue
  src/themes/thr/components/legacy/TheFooter.vue
Labels: ready to merge, size/M

#880 feature/new admin routes
  src/components/organisms/FormCreateUser.unit.js
  src/components/organisms/FormCreateUser.vue
  src/pages/administration/students/new.vue
  src/serverMiddleware/routes.js
  src/store/registrationlink.js
Labels: size/M, waiting for review

#887 dependency updates
  README.md
  package-lock.json
  package.json
  serve.json
Labels: ready to merge

#888 Changed default color of checkbox
  src/components/base/BaseInput/BaseInputCheckbox.unit.js
  src/components/base/BaseInput/BaseInputCheckbox.vue
  src/components/organisms/DataTable/TableDataRow.vue
Labels: ready to merge, size/S

#865 Feature/SC-3964/design changes admin table
  locale/de.json
  package-lock.json
  package.json
  src/components/molecules/ContextMenu.vue
  src/components/organisms/DataFilter/DataFilter.vue
  src/components/organisms/DataFilter/DataFilterChips.vue
  src/components/organisms/DataFilter/DataFilterModal.vue
  src/components/organisms/DataFilter/DataFilterSelect.vue
  tests/screenshot/__image_snapshots__/6-organisms-datafilter-datafilter_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datafilter-datafilterchips_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datafilter-datafilterselect_1-snap.png
Labels: ready to merge, size/S

#886 Changed Filter arrangement
  package-lock.json
  package.json
  src/components/organisms/DataFilter/DataFilter.vue
  src/components/organisms/DataFilter/DataFilterLayout.unit.js
  src/components/organisms/DataFilter/DataFilterLayout.vue
  tests/screenshot/__image_snapshots__/6-organisms-datafilter-datafilter_1-snap.png
Labels: ready to merge, size/M

#908 SC-4014 - fix footer links
  nuxt.config.js
  src/components/legacy/TheFooter.unit.js
  src/components/legacy/TheFooter.vue
  src/themes/brb/components/legacy/TheFooter.vue
  src/themes/n21/components/legacy/TheFooter.vue
  src/themes/open/components/legacy/TheFooter.vue
  src/themes/thr/components/legacy/TheFooter.vue
  src/utils/documents.js
Labels: ready to merge, size/M

#878 SC-3978 - Teacher are not allowed to delete users
  src/mixins/UserHasPermission.js
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
Labels: ready to merge, size/S

#912 SC-3664 - Feedback CSV Import
  src/layouts/legacyLoggedIn.vue
  src/mixins/toastsFromQueryString.js
  src/mixins/toastsFromQueryString.unit.js
  src/pages/administration/students/index.vue
  src/serverMiddleware/proxy.js
  src/serverMiddleware/proxy.unit.js
Labels: ready to merge, size/L

#890 SC-4008 - generateRegistrationLink refactoring
  src/components/organisms/FormCreateUser.unit.js
  src/components/organisms/FormCreateUser.vue
  src/store/registrationlink.js
Labels: ready to merge, size/S

#901 SC-438 - persist filters, pagination and more for session
  docs/1-Tutorials/WorkingWithOurUistate.md
  src/components/organisms/DataFilter/DataFilter.vue
  src/layouts/legacyLoggedIn.vue
  src/pages/administration/datasources/index.vue
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
  src/plugins/global.js
  src/plugins/uiState.js
  src/store/auth.js
  src/store/uiState.js
Labels: ready to merge, size/L

#915 SC-4085 - Admin-Table-SideScrolling
  src/layouts/loggedInFull.vue
Labels: ready to merge, size/XS

#931 VUE-185 - add-backdrop
  package-lock.json
  package.json
  src/components/atoms/CardTab.vue
  src/components/base/BaseModal.vue
  src/components/molecules/FabIcon.vue
  src/components/molecules/MintEcPageHeader.vue
  tests/screenshot/__image_snapshots__/4-base-ui-components-modals-action_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-modals-dialog_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-modals-info_1-snap.png
Labels: ready to merge, size/S

#932 SC-4108 - Change nuxt client favicon to schul-cloud-favicon
  nuxt.config.js
  src/static/favicon.ico
  src/static/favicon.png
Labels: ready to merge

#923 SC-4103 - Table-Layout-Improvements
  src/assets/icons/sort-down.svg
  src/assets/icons/sort-up.svg
  src/assets/icons/sort.svg
  src/components/organisms/DataFilter/DataFilterSelect.vue
  src/components/organisms/DataTable/BackendDataTable.vue
  src/components/organisms/DataTable/TableDataRow.vue
  src/components/organisms/DataTable/TableHeadRow.vue
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
  tests/screenshot/__image_snapshots__/6-organisms-datafilter-datafilterselect_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-backenddatatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable-with-filters_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tableheadrow_1-snap.png
Labels: ready to merge, size/S

#939 Update DataTable MockData to use Seed
  src/components/organisms/DataTable/DataTable.data-factory.js
  tests/screenshot/__image_snapshots__/6-organisms-datatable-backenddatatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable-with-filters_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
Labels: size/XS

#940 Quickfix - Reduce Screenshot test threshold
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-checkbox-array_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-checkbox-boolean_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-switch-array_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-switch-boolean_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datafilter-datafilter_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datafilter-inputs-checkbox_1-snap.png
  tests/screenshot/all.screenshot.js
Labels: ready to merge, size/XS

#941 Quickfix - enable eslint jest/no-try-expect rule
  .eslintrc.js
  src/components/base/BaseInput/BaseInput.unit.js
  src/components/molecules/ContextMenu.unit.js
Labels: ready to merge, size/S

#942 Quickfix - remove outdated lint rule
  .eslintrc.js
Labels: ready to merge, size/XS

#943 Quickfix - fix auto_merged label rules
  .mergify.yml
Labels: ready to merge, size/S

#944 Quickfix - collect coverage of more directories
  jest.config.js
Labels: ready to merge, size/S

#946 Bump @schul-cloud/lint-config from x.y.z to 1.0.0
  .prettierrc.js
  package-lock.json
  package.json
  src/components/legacy/PopupIconInitials.vue
Labels: dependencies, size/S

#947 Bump puppeteer from 2.1.1 to 3.0.2
  .github/workflows/pr-automation-comment-reaction.yml
  .github/workflows/test.yml
  package-lock.json
  package.json
Labels: dependencies, size/S
