Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2020-05, with the labels that each got.

#957 SC-4066 - Removed root to '/datenschutz' from footer'
  src/components/legacy/TheFooter.unit.js
  src/components/legacy/TheFooter.vue
  src/themes/brb/components/legacy/TheFooter.vue
  src/themes/open/components/legacy/TheFooter.vue
  src/themes/thr/components/legacy/TheFooter.vue
Labels: ready to merge, size/S

#965 SC-3513 - Filter chips fixed on mobile devices
  src/components/organisms/DataFilter/DataFilterChips.vue
Labels: auto_merged, size/S

#971 SC-3513 - sorting by classes and consent
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
Labels: size/XS, waiting for review
