Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2020-10, with the labels that each got.

#1332 SC-6021 - fallback icons for EdgeHTML
  CHANGELOG.md
  locale/de.json
  locale/en.json
  package-lock.json
  package.json
  src/assets/icons/arrow_drop_down.svg
  src/assets/icons/check.svg
  src/assets/icons/check_box.svg
  src/assets/icons/check_box_outline_blank.svg
  src/assets/icons/close.svg
  src/assets/icons/edit.svg
  src/assets/icons/indeterminate_check_box.svg
  src/assets/icons/info.svg
  src/assets/icons/keyboard_arrow_down.svg
  src/assets/icons/keyboard_arrow_right.svg
  src/components/base/BaseBreadcrumb.unit.js
  src/components/base/BaseIcon.vue
  tests/screenshot/__image_snapshots__/5-molecules-admintablelegend-default_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-backenddatatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable-with-filters_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable_1-snap.png
Labels: auto update, size/M, waiting for review

#1396 SC-6357 - prevent double loading
  CHANGELOG.md
  src/components/organisms/DataTable/BackendDataTable.vue
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
Labels: size/S

#1398 hotfix/1/SC-6932 - Fix
  locale/de.json
  locale/en.json
  src/components/legacy/TheSidebar.unit.js
  src/components/legacy/TheSidebar.vue
  src/components/legacy/TheTopBar.vue
  src/layouts/legacyLoggedIn.vue
  src/utils/sidebarBaseItems.js
Labels: size/S

#1400 hotfix/1/SC-6932 - Fix
  locale/de.json
  locale/en.json
  src/components/legacy/TheSidebar.unit.js
  src/components/legacy/TheSidebar.vue
  src/components/legacy/TheTopBar.vue
  src/layouts/legacyLoggedIn.vue
  src/utils/sidebarBaseItems.js
Labels: WIP, size/S

#1399 hotfix/1/SC-6932 - Fix
  locale/de.json
  locale/en.json
  src/components/legacy/TheSidebar.unit.js
  src/components/legacy/TheSidebar.vue
  src/components/legacy/TheTopBar.vue
  src/layouts/legacyLoggedIn.vue
  src/utils/sidebarBaseItems.js
Labels: ready to merge, size/S

#1325 SC-6137 - illustration 404 Page not found
  src/assets/img/pageNotFound.svg
  src/components/templates/ErrorPage.vue
Labels: auto update, size/S, waiting for review

#1401 SC-6953 - ui issues blue info modal
  src/components/organisms/DataTable/TableHeadRow.vue
Labels: size/XS, waiting for review

#1402 SC-5964 - rename filter notification
  locale/de.json
  locale/en.json
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
  src/utils/adminFilter.js
Labels: changes requested, size/M, waiting for review

#1409 hotfix/1/SC-6932 - version bump
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/XS

#1397 SC-6278 - validate create user forms
  locale/de.json
  nuxt.config.js
  package-lock.json
  package.json
  src/components/atoms/InfoMessage.stories.js
  src/components/atoms/InfoMessage.unit.js
  src/components/atoms/InfoMessage.vue
  src/components/base/BaseInput/BaseInput.stories.js
  src/components/base/BaseInput/BaseInput.vue
  src/components/base/BaseInput/BaseInputCheckbox.vue
  src/components/base/BaseInput/BaseInputDefault.vue
  src/components/base/BaseInput/BaseInputRadio.vue
  src/components/organisms/FormCreateUser.unit.js
  src/components/organisms/FormCreateUser.vue
  src/pages/administration/students/new.vue
  src/pages/administration/teachers/new.vue
  src/plugins/vuelidate.js
  stories/.storybook/mockComponents.js
  tests/screenshot/__image_snapshots__/3-atoms-errormessage-error-message_1-snap.png
  tests/screenshot/__image_snapshots__/3-atoms-infomessage-error-message_1-snap.png
  tests/screenshot/__image_snapshots__/3-atoms-infomessage-info-message_1-snap.png
  tests/screenshot/__image_snapshots__/3-atoms-infomessage-success-message_1-snap.png
  tests/screenshot/__image_snapshots__/3-atoms-infomessage-warning-message_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-default-validation_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-switch-array_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-switch-boolean_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
  tests/unit/setup.js
Labels: size/L

#1407 SC-6549 - fix missing sidebar items
  CHANGELOG.md
  locale/de.json
  locale/en.json
  src/utils/sidebarBaseItems.js
Labels: auto update, size/S, waiting for review

#1416 SC-7198 - changes links in login page
  CHANGELOG.md
  locale/de.json
  locale/en.json
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
Labels: size/S

#1391 SC-6510 - Feature/ make use of merlin content
  locale/de.json
  locale/en.json
  src/assets/icons/hashtag.svg
  src/assets/icons/open_new_window.svg
  src/components/molecules/AddContentModal.vue
  src/components/organisms/AddContentButton.vue
  src/components/organisms/LernstoreDetailView.vue
Labels: auto update, size/M

#1415 SC-6831 - fixes search icon behavior on lernstore
  CHANGELOG.md
  src/components/molecules/ContentSearchbar.vue
  tests/screenshot/__image_snapshots__/5-molecules-content-contentsearchbar-contentsearchbar_1-snap.png
Labels: auto_merged, size/S

#1418 SC-7092 - last minute issues
  locale/de.json
  src/components/organisms/DataFilter/DataFilterModal.vue
  src/utils/adminFilter.js
Labels: size/S

#1164 Feature/calender page
  nuxt.config.js
  package-lock.json
  package.json
  src/components/organisms/Calendar/AppointmentModal.vue
  src/pages/calendar/index.vue
  src/plugins/full-calendar.js
  src/serverMiddleware/routes.js
  src/store/calendar.js
Labels: auto update, size/XL

#1427 Quickfix - Remove content from routes, which causes tests to fail
  src/serverMiddleware/routes.js
  src/store/calendar.js
Labels: size/XS

#1419 feature/SC-7025 - create new component tapbar
  src/assets/icons/gruppen.svg
  src/assets/icons/lerninhalte.svg
  src/assets/icons/tools.svg
  src/components/atoms/Tab.unit.js
  src/components/atoms/Tab.vue
  src/components/organisms/Tabs/Tabs.stories.js
  src/components/organisms/Tabs/Tabs.unit.js
  src/components/organisms/Tabs/Tabs.vue
  tests/screenshot/__image_snapshots__/5-molecules-tabs-tabs_1-snap.png
Labels: waiting for review

#1262 SC-3788 - matrix messenger integration
  .vscode/settings.json
  docs/0-GettingStarted/1-Build.md
  http-headers.config.js
  nuxt.config.js
  src/components/organisms/Messenger/Messenger.unit.js
  src/components/organisms/Messenger/Messenger.vue
  src/layouts/legacyLoggedIn.vue
  src/store/auth.js
  src/store/messenger.js
  tests/store/messenger.unit.js
  tests/unit/setup.js
Labels: auto update, size/XL, waiting for review

#1436 SC-7381 - quickfix/increase consent limit request
  CHANGELOG.md
  src/pages/administration/students/consent.vue
Labels: size/XS, waiting for review

#1412 SC-6060 - Analyse and fix top errors in sentry
  CHANGELOG.md
  package-lock.json
Labels: size/XS, waiting for review

#1428 SC-7339 - quickfix/change consent permission
  CHANGELOG.md
  src/pages/administration/students/consent.vue
Labels: size/XS, waiting for review

#1440 SC-7025 - Adjust new styles on tab bar
  src/components/atoms/Tab.vue
  src/components/organisms/Tabs/Tabs.stories.js
  src/components/organisms/Tabs/Tabs.vue
  tests/screenshot/__image_snapshots__/5-molecules-tabs-singletab_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-tabs-tabcontent_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-tabs-tabs_1-snap.png
Labels: waiting for review

#1449 SC-6293 - restricts Lern-Store with permission
  CHANGELOG.md
  src/pages/content/_id/index.vue
  src/pages/content/index.vue
  src/store/auth.js
  src/utils/sidebarBaseItems.js
Labels: size/S, waiting for review

#1450 Feature/SC-7447 - add warning text leaving sc
  CHANGELOG.md
  locale/de.json
  locale/en.json
  package-lock.json
  src/components/organisms/LernstoreDetailView.vue
Labels: auto update, ready to merge, size/S

#1466 SC-6708 - added data-testids for the new admin tables
  CHANGELOG.md
  src/components/molecules/ContextMenu.vue
  src/components/molecules/FabIcon.vue
  src/components/organisms/DataFilter/DataFilterSelect.vue
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
  src/utils/adminFilter.js
Labels: size/S

#1471 SC-7505 - skip loading roles until api service is unblocked
  src/store/auth.js
Labels: size/S

#1464 SC-7447 - quickfix/add-conditional-rendering-text-for-brandenburg
  CHANGELOG.md
  locale/de.json
  locale/en.json
  src/components/organisms/LernstoreDetailView.vue
Labels: auto update, ready to merge, size/S

#1468 Hotfix/5/SC-7447 - leave text
  CHANGELOG.md
  locale/de.json
  locale/en.json
  package.json
  src/components/organisms/LernstoreDetailView.vue
Labels: ready to merge, size/M

#1473 SC-7482 - enable loading of route
  src/store/auth.js
Labels: ready to merge, size/S

#1423 SC-7020 - editor document item
  CHANGELOG.md
  src/assets/img/courses/draft.svg
  src/components/atoms/PulsatingDot.vue
  src/components/molecules/TaskItem.stories.js
  src/components/molecules/TaskItem.unit.js
  src/components/molecules/TaskItem.vue
  src/serverMiddleware/routes.js
  tests/screenshot/__image_snapshots__/5-molecules-taskitem-with-image-(triple)_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-taskitem-with-knobs_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-taskitem-with-pulsating-dot_1-snap.png
Labels: size/L, waiting for review

#1474 SC-7108 - create a component header
  locale/de.json
  src/components/base/BaseHeader.stories.js
  src/components/base/BaseHeader.unit.js
  src/components/base/BaseHeader.vue
  src/components/molecules/ContextMenu.stories.js
  src/components/molecules/ContextMenu.vue
  src/components/molecules/CourseHeader.stories.js
  src/components/molecules/CourseHeader.unit.js
  src/components/molecules/CourseHeader.vue
  tests/screenshot/__image_snapshots__/4-base-ui-components-baseheader-with-some-actions_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-baseheader-without-context-menu-actions_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-courseheader-default_1-snap.png
Labels: size/L, waiting for review

#1476 IMP-160 renaming integration-tests repo end-to-…
  .github/workflows/test.yml
  CHANGELOG.md
  docs/0-GettingStarted/0-Development.md
  docs/0-GettingStarted/1-Build.md
  docs/0-GettingStarted/4-Workflow.md
  docs/1-Tutorials/FallbackRoutingForOldClient.md
  docs/1-Tutorials/WritingTests/EndToEndTests.md
  docs/1-Tutorials/WritingTests/IntegrationTests.md
  docs/1-Tutorials/WritingTests/UnitTests.md
  docs/2-Styles/0-Variables.md
  docs/3-BeginnerGuide/0-Einfuehrung.md
  docs/3-BeginnerGuide/1-Was-kannst-Du-fuer-die-Schul-Cloud-tun.md
Labels: size/M
