Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2020-07, with the labels that each got.

#1045 SC-4652 - User Interface for Account
  locale/de.json
  nuxt.config.js
  src/assets/icons/mail-check.svg
  src/assets/icons/mail-error.svg
  src/components/base/BaseModal.stories.js
  src/components/base/BaseModal.vue
  src/components/legacy/NavigationBar.stories.js
  src/components/legacy/NavigationBar.unit.js
  src/components/legacy/NavigationBar.vue
  src/components/molecules/AccountCard.stories.js
  src/components/molecules/AccountCard.unit.js
  src/components/molecules/AccountCard.vue
  src/components/molecules/InfoModalFullWidth.vue
  src/components/organisms/FormEditUserData.vue
  src/layouts/loggedoutFullLayout.vue
  src/layouts/loggedoutFullWidth.vue
  src/layouts/loggedoutNavbarLogo.vue
  src/middleware/externally-managed-check.js
  src/pages/account/email/edit.vue
  src/pages/account/index.vue
  src/pages/account/name/edit.vue
  src/pages/account/password/edit.vue
  src/pages/activation/_activationCode/index.vue
  src/serverMiddleware/routes.js
  src/store/activation.js
  src/utils/service-template.js
  tests/middleware/externally-managed-check.unit.js
  tests/screenshot/__image_snapshots__/5-molecules-accountcard-default_1-snap.png
Labels: ready to merge, size/XXL

#1092 Quickfix - Update look of Icon Story
  stories/components/IconCard.vue
  stories/icons.stories.js
Labels: proposal, ready to merge, size/M

#1056 OPS-737 - Fixed the filter logic on create trigger
  .github/workflows/update_version.yml
Labels: size/XS, waiting for review

#1108 SC-4399 - move-to-organisms
  src/components/organisms/ContentCard.stories.js
  src/components/organisms/ContentCard.unit.js
  src/components/organisms/ContentCard.vue
  src/pages/content/index.vue
  tests/screenshot/__image_snapshots__/6-organisms-content-contentcard-contentcard_1-snap.png
Labels: waiting for review

#1109 SC-5354 - adjusted-NotificationModal-to-get-any-color
  src/components/molecules/NotificationModal.stories.js
  src/components/molecules/NotificationModal.unit.js
  src/components/molecules/NotificationModal.vue
  src/components/organisms/AddContentButton.vue
Labels: size/S, waiting for review

#1111 SC-5478 - fix-tab-name
  src/components/organisms/LernstoreDetailView.vue
Labels: size/XS

#1088 SC-4982 - add-explanation-to-qr-code-pop-up
  locale/de.json
  locale/en.json
  src/components/legacy/MenuQrCode.unit.js
  src/components/legacy/MenuQrCode.vue
  src/components/legacy/PopupIcon.vue
Labels: ready to merge, size/M

#1104 SC-5337 - Finishing login for multi instances
  src/components/legacy/NavigationBar.vue
Labels: ready to merge, size/XS

#1099 SC-5256 - New-admin-tables-checkbox-error
  src/components/organisms/DataTable/BackendDataTable.unit.js
  src/components/organisms/DataTable/DataTable.data-factory.js
  src/components/organisms/DataTable/DataTable.unit.js
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
  tests/screenshot/__image_snapshots__/3-atoms-profilepicture-profile-picture_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-base-ui-base-breadcrumb_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-base-ui-basebutton_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-basechip-default_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-date_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-modals-action_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-modals-default_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-modals-dialog_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-admintablelegend-default_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-contextmenu-with-icons_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-datasourcecard-with-subtitle_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-datasourcecard-without-subtitle_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-infobox-infobox_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datafilter-datafilter_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datafilter-datafilterchips_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datafilter-datafilterselect_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-backenddatatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable-with-filters_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-formcreateuser_1-snap.png
Labels: size/M

#1122 rollback and fix lodash to version 4.17.15
  package.json
Labels: size/XS

#1121 SC-5494 - Changed link in navigation bar
  package-lock.json
  src/components/legacy/NavigationBar.stories.js
  src/components/legacy/NavigationBar.unit.js
  src/utils/navbarBaseItems.js
Labels: ready to merge, size/XS

#1118 SC-5491 - edusharing-footer
  package.json
  src/components/molecules/ContentEduSharingFooter.vue
  src/components/molecules/ContentEmptyState.vue
  src/components/molecules/ContentSearchbar.vue
  src/layouts/loggedInFull.vue
  src/pages/content/index.vue
  src/plugins/global.js
  tests/screenshot/__image_snapshots__/5-molecules-content-contentedusharingfooter-contentedusharingfooter_1-snap.png
Labels: size/L, waiting for review

#1120 SC-5492 - detailview-from-course
  src/pages/content/index.vue
Labels: size/XS, waiting for review

#1129 Hotfix 25.0.1 sc-5529 SC-5494
  CHANGELOG.md
  README.md
  deploy/deploy.sh
  docs/3-BeginnerGuide/0-Einfuehrung.md
  docs/3-BeginnerGuide/1-Was-kannst-Du-fuer-die-Schul-Cloud-tun.md
  docs/3-BeginnerGuide/2-Das-Ticketsystem.md
  docs/3-BeginnerGuide/3-Vorbereitung-für-Entwickler.md
  docs/README.md
  locale/de.json
  locale/en.json
  package-lock.json
  package.json
  src/assets/img/logo/README.md
  src/components/legacy/LegacyFooter.vue
  src/components/molecules/LandingCTA.stories.js
  src/components/organisms/CourseWizard/StepDone.vue
  src/layouts/loggedoutFullWidth.vue
  src/themes/default/config.js
  stories/.storybook/theme.js
  stories/mockData/CourseCard.js
  tests/screenshot/__image_snapshots__/5-molecules-admintablelegend-default_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-onboarding-landing-cta_1-snap.png
Labels: size/M

#1128 SC-5517 - hover-bug
  src/components/molecules/ModalFooterConfirm.vue
  src/components/molecules/NotificationModal.vue
Labels: size/M, waiting for review

#1115 SC-5265 - lernstore-arrow-back-window
  locale/de.json
  src/layouts/legacyLoggedIn.vue
  src/layouts/loggedInFull.vue
  src/pages/content/index.vue
Labels: ready to merge, size/L

#1124 SC-5345 - edusharing-content
  nuxt.config.js
  package-lock.json
  src/components/organisms/AddContentButton.vue
  src/components/organisms/ContentCard.unit.js
  src/components/organisms/ContentCard.vue
  src/components/organisms/LernstoreDetailView.unit.js
  src/components/organisms/LernstoreDetailView.vue
  src/serverMiddleware/routes.js
  src/store/content.js
  src/utils/helpers.js
  stories/mockData/Resource.js
  tests/screenshot/__image_snapshots__/5-molecules-admintablelegend-default_1-snap.png
Labels: size/M

#1123 SC-5513 - Center Icons on ContentCard
  src/components/organisms/ContentCard.vue
  tests/screenshot/__image_snapshots__/6-organisms-content-contentcard-contentcard_1-snap.png
Labels: ready to merge, size/XS

#1112 SC-5480 - fixed selection population bug
  locale/de.json
  src/components/molecules/AddContentModal.vue
  src/store/content.js
Labels: ready to merge, size/M

#1141 SC-5427 - rename MODE_LERNSTORE to LERNSTORE_MODE for
  docs/0-GettingStarted/1-Build.md
  nuxt.config.js
  src/serverMiddleware/routes.js
Labels: size/XS

#1146 SC-5486 - fixing the font scaling issue for the themes
  src/themes/brb/styles/variables.scss
  src/themes/open/styles/variables.scss
  src/themes/thr/styles/variables.scss
Labels: ready to merge, size/XS

#1147 SC-5535 - Change default limit to 25
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
Labels: size/XS, waiting for review

#1152 Hotfix/1/sc 5653
  .github/issue_template.md
  CHANGELOG.md
  docs/3-BeginnerGuide/0-Einfuehrung.md
  docs/3-BeginnerGuide/1-Was-kannst-Du-fuer-die-Schul-Cloud-tun.md
  package-lock.json
  package.json
  src/components/molecules/MintEcFooter.vue
Labels: size/S

#1155 SC-4717 - CSP Envs
  deploy/compose-client_default.dummy
Labels: ready to merge, size/XS

#1157 SC-5538 - Refresh users table after deleting the user
  src/pages/administration/students/index.vue
Labels: ready to merge, size/XS

#1087 Quickfix - add 'Fortbildungen' to topbar
  src/assets/icons/fortbildung.svg
  src/components/base/BaseIcon.vue
  src/components/legacy/HelpDropdown.unit.js
  src/components/legacy/HelpDropdown.vue
  src/layouts/legacyLoggedIn.vue
  tests/screenshot/__image_snapshots__/4-base-ui-components-base-ui-base-icon_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-base-ui-basetextarea_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-default-error_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-default-success_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-content-contentsearchbar-contentsearchbar_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-coursecard-coursecard_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-formdatasourcelogin_1-snap.png
Labels: size/M, waiting for review

#1160 SC-4925 - change-administration-to-verwaltung
  src/utils/sidebarBaseItems.js
Labels: size/XS, waiting for review

#1158 SC-4717 - disabled old deployment of docker-compose file.
  deploy/deploy.sh
Labels: ready to merge, size/XS

#1156 SC-5542 - Order of table headers
  locale/de.json
  src/pages/administration/students/index.vue
Labels: ready to merge, size/S

#1119 Quickfix - Added Update Screenshot Documentation
  docs/0-GettingStarted/4-Workflow.md
  tests/screenshot/__image_snapshots__/5-molecules-legacyfooter-default_1-snap.png
Labels: proposal, ready to merge, size/S

#1145 SC-4275 - SC International Nuxt Theming
  .github/workflows/test.yml
  .travis.yml
  deploy/compose-client_int.dummy
  deploy/deploy.sh
  src/components/base/BaseInput/BaseInputDefault.vue
  src/themes/int/assets/img/logo/logo-image-mono.svg
  src/themes/int/components/legacy/TheFooter.vue
  src/themes/int/config.js
  src/themes/int/styles/index.scss
  src/themes/int/styles/variables.scss
  src/themes/int/styles/variables/_colors.scss
  tests/screenshot/__image_snapshots__/6-organisms-formnews-edit_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-formnews-new_1-snap.png
Labels: ready to merge, size/L

#1168 SC-5802 add content/redirect as exception for the router
  src/serverMiddleware/routes.js
Labels: changes requested, size/XS, waiting for review

#1171 SC-5765 - General Logo Fix Nuxt
  src/assets/img/logo/logo-image-mono.svg
  src/components/legacy/TheSidebar.vue
  src/themes/int/assets/img/logo/logo-image-mono.svg
  src/themes/n21/assets/img/logo/logo-image-mono.svg
  src/themes/n21/assets/img/logo/logo-transparent-mono-48-48.svg
  tests/screenshot/__image_snapshots__/6-organisms-content-contentcard-contentcard_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-content-lernstoredetailview-lernstoredetailview_1-snap.png
Labels: size/S

#1169 SC-5756 - add isExternal logic to admin tables
  locale/de.json
  src/pages/administration/students/index.vue
Labels: size/XS, waiting for review

#1170 SC-5802 - Fixes for the Edusharing
  src/components/organisms/ContentCard.vue
  src/components/organisms/LernstoreDetailView.unit.js
  src/components/organisms/LernstoreDetailView.vue
  stories/mockData/Resource.js
  tests/screenshot/__image_snapshots__/5-molecules-legacyfooter-default_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-content-contentcard-contentcard_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-content-lernstoredetailview-lernstoredetailview_1-snap.png
Labels: size/M

#1175 Quickfix - fix navbar
  src/layouts/loggedoutFullWidth.vue
Labels: size/S

#898 SC-3976 - consent info
  locale/de.json
  src/components/molecules/InfoBox.vue
  src/components/organisms/DataTable/BackendDataTable.unit.js
  src/components/organisms/DataTable/BackendDataTable.vue
  src/components/organisms/DataTable/DataTable.unit.js
  src/components/organisms/DataTable/TableHeadRow.vue
  src/pages/administration/students/index.vue
  tests/screenshot/__image_snapshots__/5-molecules-infobox-infobox_1-snap.png
Labels: ready to merge, size/L

#1174 Quickfix - auto update label
  .mergify.yml
Labels: size/XS

#1165 Quickfix - news not published later
  package-lock.json
  package.json
  src/components/base/BaseInput/BaseInput.vue
  src/components/base/BaseInput/BaseInputCalendar.vue
  src/components/base/BaseInput/BaseInputDefault.unit.js
  src/components/base/BaseInput/BaseInputDefault.vue
  src/components/organisms/FormNews.vue
  src/layouts/loggedoutFullWidth.vue
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-date_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-time_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-formcreateuser_1-snap.png
Labels: size/XS

#1180 SC-5840 - Fix Package Version Styles
  package-lock.json
  package.json
  stories/DesignTokens.stories.js
  tests/screenshot/__image_snapshots__/5-molecules-infobox-infobox_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-content-contentcard-contentcard_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-content-lernstoredetailview-lernstoredetailview_1-snap.png
Labels: ready to merge, size/XS

#1181 SC-5812 - fix request pollution
  src/components/molecules/ContentSearchbar.vue
Labels: ready to merge, size/M

#1159 SC-5536 - persist sorting in current session
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
  src/store/uiState.js
Labels: ready to merge, size/S

#1172 SC-4115 - date picker issue
  src/components/base/BaseInput/BaseInputDefault.vue
  tests/screenshot/__image_snapshots__/4-base-ui-components-base-ui-basetextarea_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-date_1-snap.png
Labels: ready to merge, size/XS

#1195 Quickfix - fixed comma in LernStoreDetailView
  src/components/organisms/LernstoreDetailView.vue
Labels: ready to merge, size/XS
