Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2020-09, with the labels that each got.

#1295 SC-5410 - language dropdown for user
  CHANGELOG.md
  locale/de.json
  locale/en.json
  src/assets/icons/flag_Deutsch.svg
  src/assets/icons/flag_English.svg
  src/components/organisms/LanguageSwitcher.unit.js
  src/components/organisms/LanguageSwitcher.vue
  src/pages/account/index.vue
  src/pages/account/locale/edit.vue
  src/serverMiddleware/routes.js
Labels: size/L, waiting for review

#1287 SC-6360 - change-icon-on-contentCard-in-lernstore
  src/components/organisms/ContentCard.vue
  tests/screenshot/__image_snapshots__/6-organisms-content-contentcard-contentcard_1-snap.png
Labels: auto update, ready to merge, size/S

#1292 SC-6472 - fix bulkQr in teachers table and add filtered actions
  src/pages/administration/teachers/index.vue
Labels: size/M, waiting for review

#1269 SC-5612 - Search bar for admintables
  locale/de.json
  locale/en.json
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
Labels: size/L

#1291 SC-6474 - filter out edit key from column data
  CHANGELOG.md
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
Labels: size/S, waiting for review

#1294 SC-6478 - changed link in the legend, external schools
  src/components/molecules/AdminTableLegend.vue
Labels: size/XS

#1296 SC-5944 - changed the wording for registrations
  locale/de.json
  src/components/molecules/AdminTableLegend.stories.js
Labels: size/S

#1293 SC-5815 - fixed the safari overflow issue
  src/components/organisms/DataTable/TableHeadRow.vue
  src/layouts/legacyLoggedIn.vue
Labels: size/XS

#1046 SC-3704 - Analog-consent
  locale/de.json
  locale/en.json
  package-lock.json
  package.json
  src/assets/img/hpi.png
  src/assets/img/safely_connected.png
  src/components/base/BaseInput/BaseInputCalendar.vue
  src/components/organisms/DataTable/BackendDataTable.vue
  src/components/organisms/DataTable/TableDataRow.vue
  src/mixins/generatePassword.js
  src/pages/administration/students/consent.vue
  src/pages/administration/students/index.vue
  src/serverMiddleware/routes.js
  src/store/bulkConsent.js
  src/utils/documents.js
  tests/screenshot/__image_snapshots__/4-base-ui-components-base-ui-base-select_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-base-ui-basebutton_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-base-ui-basecard_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-admintablelegend-default_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-content-contentemptystate-contentemptystate_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-contextmenu-with-icons_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-contextmenu-without-icons_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-datasourcecard-with-context-menu_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-datasourcecard-with-knobs_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-minteclinkcontainer-default_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-content-lernstoredetailview-lernstoredetailview_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-backenddatatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable-with-filters_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-rowselectionbar_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-pagination_1-snap.png
  tests/screenshot/__image_snapshots__/7-others-misc-dropdownmenumintec_1-snap.png
Labels: size/M

#1303 SC-6587 - quickfix - teachers table external school checks
  src/pages/administration/teachers/index.vue
Labels: size/S, waiting for review

#1301 SC-6509 - updates url content element field
  src/components/organisms/AddContentButton.vue
  src/components/organisms/LernstoreDetailView.vue
Labels: auto update, ready to merge, size/XS, waiting for review

#1297 SC-6241 - include birthday in create-student-request. Refactor FormCrea…
  .vscode/launch.json
  src/components/organisms/FormCreateUser.stories.js
  src/components/organisms/FormCreateUser.unit.js
  src/components/organisms/FormCreateUser.vue
  src/pages/administration/students/new.vue
  src/pages/administration/teachers/new.vue
  src/store/users.js
Labels: auto update, ready to merge, size/L, waiting for review

#1286 SC-5987 - SC-5410 language switcher in nuxt. You can find it on user account page
  CHANGELOG.md
  locale/de.json
  locale/en.json
  nuxt.config.js
  src/assets/icons/flag_Deutsch.svg
  src/assets/icons/flag_English.svg
  src/components/organisms/LanguageSwitcher.unit.js
  src/components/organisms/LanguageSwitcher.vue
  src/middleware/language-switch.js
  src/pages/account/index.vue
  src/pages/account/locale/edit.vue
  src/plugins/i18n.js
  src/serverMiddleware/routes.js
  src/store/auth.js
  src/store/i18n.js
  stories/LanguageSwitcher.stories.js
  tests/unit/setup.js
Labels: auto update, size/L, waiting for review

#1307 SC-6600 - quickfix restore birth date column
  src/pages/administration/students/index.vue
Labels: auto_merged, size/S

#1308 SC-6632 - change wording Abmelden to Logout
  locale/de.json
  src/components/legacy/TheTopBar.unit.js
  src/components/legacy/TheTopBar.vue
Labels: size/XS

#1311 SC-6667 - quickfix filter name for teachers table
  locale/de.json
  src/utils/adminFilter.js
Labels: size/S

#1316 SC-6618 - add test IDs for integration tests
  src/components/organisms/DataTable/BackendDataTable.vue
  src/components/organisms/DataTable/TableHeadRow.vue
Labels: size/XS

#1322 SC-6701 - mint-ec URL (Hotfix 24.4.1)
  CHANGELOG.md
  package-lock.json
  package.json
  src/store/ghost.js
Labels: size/XS, waiting for review

#1327 SC-6704 - sidebar test IDs
  src/components/legacy/TheSidebar.vue
Labels: size/XS

#1326 OPS-1109 - removed deployment on testenvironment.
  deploy/deploy.sh
Labels: auto update, auto_merged, size/XS

#1331 SC-5695 - modal footer refactor
  src/components/molecules/ModalFooterConfirm.unit.js
  src/components/molecules/ModalFooterConfirm.vue
  src/components/molecules/NotificationModal.stories.js
  src/components/molecules/NotificationModal.vue
Labels: size/M, waiting for review

#1323 SC-6628 - Changing backend url endpoint while analog consenting
  CHANGELOG.md
  locale/de.json
  locale/en.json
  src/pages/administration/students/consent.vue
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
  src/store/bulkConsent.js
Labels: size/L

#1334 SC-6603 - set limits and pattern to calendar input
  src/components/base/BaseInput/BaseInputDefault.vue
  src/pages/administration/students/consent.vue
  src/pages/administration/students/new.vue
Labels: size/S, waiting for review

#1328 SC-6684 - text change
  locale/de.json
  locale/en.json
  src/utils/adminFilter.js
Labels: auto update, ready to merge, size/M

#1336 SC-5814 - adjust base grid
  src/components/base/BaseGrid.vue
  tests/screenshot/__image_snapshots__/2-layouts-basegrid-custom-column-width_1-snap.png
  tests/screenshot/__image_snapshots__/2-layouts-basegrid-default-grid_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-coursecard-coursecard-getting-old-data-format_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-coursecard-coursecard_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-legacyfooter-default_1-snap.png
Labels: auto update, size/S, waiting for review

#1344 SC-6779 - quickfix - remove analogue consent action
  src/pages/administration/teachers/index.vue
Labels: size/XS

#1349 SC-6743 - quickfix/change query parameter
  src/pages/administration/students/consent.vue
Labels: size/XS

#1347 SC-6744 - Quickfix-sort-list-of-users-for-consenting
  src/pages/administration/students/consent.vue
  src/store/bulkConsent.js
Labels: size/M

#1352 SC-6775-Quickfix-layout issue with birthdate line inside analogue consent part
  src/pages/administration/students/consent.vue
Labels: size/S

#1353 SC-6608 - change search bar design
  locale/de.json
  package-lock.json
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
Labels: size/L

#1355 SC-6746 - add warning modal for consent download
  locale/de.json
  src/pages/administration/students/consent.vue
Labels: size/M

#1362 SC-6808 - added testid for qa team to test lernstore
  src/pages/content/index.vue
Labels: size/XS, waiting for review

#1361 SC-6070 - new brb logo fix
  src/assets/icons/brb.svg
Labels: size/XS, waiting for review

#1345 SC-6785 - flag-icons of Germany and Great Britain were exchange
  src/assets/icons/flag_Deutsch.svg
  src/assets/icons/flag_English.svg
Labels: auto update, size/XS, waiting for review

#1363 SC-6316 - remove icon in LDAP
  src/components/molecules/AdminTableLegend.vue
Labels: auto update, ready to merge, size/XS

#1367 SC-6839-Quickfix-search input from search bar entered in students table is taken over to teachers table
  src/pages/administration/teachers/index.vue
Labels: size/XS

#1368 SC-6843-Quickfix-Trim white spaces in the searchbar text
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
Labels: size/XS

#1369 SC-6682 - decreases search time in lern-store
  CHANGELOG.md
  locale/de.json
  locale/en.json
  src/components/molecules/ContentSearchbar.vue
  src/pages/content/index.vue
  tests/screenshot/__image_snapshots__/5-molecules-admintablelegend-default_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-content-states-contentemptystate_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-backenddatatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable-with-filters_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
Labels: auto update, ready to merge, size/S

#1371 SC-6860 - quickfix-remove qr error message
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
Labels: size/S

#1366 SC-6836 - html lang value
  locale/en.json
Labels: size/XS, waiting for review

#1372 Quickfix - Update docs regarding the store usage
  docs/1-Tutorials/APIRequests.md
Labels: size/S

#1343 SC-6386 - change-icons-in-storybook
  src/assets/icons/doublecheck.svg
  src/assets/icons/ic_default.svg
  src/assets/icons/ic_link.svg
  src/assets/icons/ic_video.svg
Labels: a11y, auto update, bug, ready to merge, size/XS

#1378 SC-6806 - add warning to consent download
  src/pages/administration/students/consent.vue
Labels: size/M

#1376 hotfix/1/SC-6932 - Add missing translations to sidebar in nuxt client
  CHANGELOG.md
  locale/de.json
  locale/en.json
  src/layouts/legacyLoggedIn.vue
  src/utils/sidebarBaseItems.js
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
Labels: size/L, waiting for review

#1387 updated package, package-lock, changelog
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/XS

#1383 SC-6481 - extend consent notification
  locale/de.json
  src/components/organisms/DataTable/BackendDataTable.vue
  src/components/organisms/DataTable/TableHeadRow.vue
  src/pages/administration/students/index.vue
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
Labels: size/M

#1390 SC-6957 - quickfix/remove teacher's edit button
  src/pages/administration/teachers/index.vue
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
Labels: size/XS

#1389 SC-6548 - implements favicon according theme
  nuxt.config.js
  src/static/themes/brb/favicon.png
  src/static/themes/default/favicon.png
  src/static/themes/int/favicon.png
  src/static/themes/n21/favicon.png
  src/static/themes/open/favicon.png
  src/static/themes/thr/favicon.png
Labels: waiting for review

#1374 SC-5964 - renamed notification messages
  locale/de.json
Labels: size/XS
