Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2020-12, with the labels that each got.

#1580 SC-7543 - ldap submit data page
  CHANGELOG.md
  locale/de.json
  locale/en.json
  src/components/organisms/Ldap/LdapClassesSection.unit.js
  src/components/organisms/Ldap/LdapClassesSection.vue
  src/components/organisms/Ldap/LdapConnectionSection.vue
  src/components/organisms/Ldap/LdapRolesSection.unit.js
  src/components/organisms/Ldap/LdapRolesSection.vue
  src/components/organisms/Ldap/LdapUsersSection.vue
  src/pages/administration/ldap/activate.unit.js
  src/pages/administration/ldap/activate.vue
  src/pages/administration/ldap/config.unit.js
  src/pages/administration/ldap/config.vue
  src/pages/administration/ldap/ldap-config.vue
  src/serverMiddleware/routes.js
  src/store/ldap-config.js
  src/store/ldap-config.unit.js
  src/utils/ldapConstants.js
  src/utils/ldapErrorHandling.js
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
Labels: size/XXL

#1596 SC-8158 - ldap initial data load fix
  CHANGELOG.md
  src/pages/administration/ldap/activate.unit.js
  src/pages/administration/ldap/activate.vue
  src/pages/administration/ldap/config.unit.js
  src/pages/administration/ldap/config.vue
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
Labels: auto update, auto_merged, ready to merge, size/L

#1597 SC-8169 - classes section clear inputs event
  CHANGELOG.md
  locale/de.json
  src/components/organisms/Ldap/LdapClassesSection.vue
  src/pages/administration/ldap/config.vue
Labels: auto update, auto_merged, size/S

#1593 SC-7023 - redirect, edit and delete actions for the task item
  .eslintrc.js
  CHANGELOG.md
  docs/2-Styles/0-Variables.md
  locale/de.json
  locale/en.json
  package-lock.json
  package.json
  src/components/base/BaseButton.scss
  src/components/base/BaseHeader.vue
  src/components/molecules/DeleteModal.stories.js
  src/components/molecules/DeleteModal.unit.js
  src/components/molecules/DeleteModal.vue
  src/components/molecules/ModalBodyInfo.vue
  src/components/molecules/TaskItem.stories.js
  src/components/molecules/TaskItem.unit.js
  src/components/molecules/TaskItem.vue
  src/components/organisms/Tabs/Tabs.vue
  src/pages/courses/_id/index.unit.js
  src/pages/courses/_id/index.vue
  src/pages/courses/index.vue
  src/serverMiddleware/routes.js
  src/store/courses.js
  src/store/courses.unit.js
  src/themes/default/styles/variables.scss
  src/themes/demo/styles/variables.scss
  stories/.storybook/manager-head.html
  tests/screenshot/__image_snapshots__/4-base-ui-components-base-ui-basebutton_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-dialog-default_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-modals-autologout-warning_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-modals-delete-modal_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-modals-info_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-formactions-default_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-navigationbar-default_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-tabs-tabs_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-taskitem-with-knobs-and-delete-modal_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-taskitem-with-pulsating-dot_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datafilter-datafiltermodal_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-dropdownmenu_1-snap.png
  tests/screenshot/__image_snapshots__/7-others-misc-toast_1-snap.png
Labels: auto update, size/XXL, waiting for review

#1606 Feature/SC-8219 - Datetime correction on students consent page
  CHANGELOG.md
  src/pages/administration/students/consent.vue
  src/plugins/datetime.js
  src/store/bulkConsent.js
Labels: auto update, auto_merged, ready to merge, size/M

#1605 SC-7824 - Set proper emails and labelf for data protection
  CHANGELOG.md
  locale/de.json
  locale/en.json
  src/components/legacy/LegacyFooter.vue
  src/pages/mint-ec/_article.vue
  src/themes/n21/components/templates/CommonTermsOfUse.vue
  tests/screenshot/__image_snapshots__/5-molecules-legacyfooter-default_1-snap.png
Labels: auto update, ready to merge, size/M

#1599 Feature/SC-8022 - collection view
  CHANGELOG.md
  locale/de.json
  locale/en.json
  package-lock.json
  package.json
  src/components/organisms/AddContentButton.vue
  src/components/organisms/ContentCard.stories.js
  src/components/organisms/ContentCard.unit.js
  src/components/organisms/ContentCard.vue
  src/components/organisms/LernstoreCollectionDetailView.vue
  src/components/organisms/LernstoreDetailView.vue
  src/pages/content/_id/index.vue
  src/pages/content/index.vue
  src/store/content.js
  src/utils/helpers.js
  stories/mockData/Collection.js
  stories/mockData/Resource.js
  tests/screenshot/__image_snapshots__/6-organisms-content-lernstorecollectiondetailview-lernstorecollectiondetailview_1-snap.png
Labels: auto update, ready to merge, size/XL

#1591 SC-7053 - added typescript dependencies and config
  .eslintrc.js
  .gitignore
  .vscode/settings.json
  CHANGELOG.md
  aliases.config.js
  jest.config.js
  jsconfig.template.js
  nuxt.config.js
  package-lock.json
  package.json
  src/components/base/BaseDialog/DialogProgrammatic.d.ts
  src/components/organisms/FormNews.unit.js
  src/components/organisms/FormNews.vue
  src/plugins/i18n.d.ts
  src/plugins/i18n.js
  src/plugins/user.d.ts
  stories/.storybook/main.js
  tsconfig.template.js
  vue-shim.d.ts
Labels: size/L

#1614 SC-7686 - Fix naming convention for Lern Store
  CHANGELOG.md
  locale/de.json
  locale/en.json
  src/components/organisms/LernstoreDetailView.vue
Labels: ready to merge, size/S

#1618 SC-8094 - writes unit tests for collections feature
  src/components/organisms/ContentCard.unit.js
  src/components/organisms/LernstoreCollectionDetailView.unit.js
  src/components/organisms/LernstoreCollectionDetailView.vue
Labels: size/M, waiting for review

#1621 SC-7824 - changed address in the Common Terms Of Use
  CHANGELOG.md
  src/components/templates/CommonTermsOfUse.vue
Labels: size/XS, waiting for review
