Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2020-11, with the labels that each got.

#1482 Bugfix/SC-2710 - fix test tz
  src/plugins/datetime.js
  tests/plugins/datetime.unit.js
Labels: ready to merge, size/M

#1485 SC-5476 - rename env vars to be consistent with old client and server
  CHANGELOG.md
  http-headers.config.js
  nuxt.config.js
  src/store/messenger.js
Labels: size/M

#1475 OPS-1508 - RAM and CPU Limit Docker Compse file
  CHANGELOG.md
  deploy/compose-client_brb.dummy
  deploy/compose-client_default.dummy
  deploy/compose-client_int.dummy
  deploy/compose-client_n21.dummy
  deploy/compose-client_open.dummy
  deploy/compose-client_thr.dummy
Labels: auto update, ready to merge, size/M

#1501 Quickfix - Updated package "@tryghost/content-api"
  package-lock.json
  package.json
Labels: size/XS

#1470 SC-7461 - tabbar shadow underline
  .gitignore
  src/components/organisms/Tabs/Tabs.vue
  tests/screenshot/__image_snapshots__/5-molecules-tabs-tabcontent_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-tabs-tabs_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
Labels: waiting for review

#1527 SC-7768 - fixed resizing of the task item icon
  src/components/molecules/TaskItem.vue
  tests/screenshot/__image_snapshots__/5-molecules-taskitem-with-knobs_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-taskitem-with-pulsating-dot_1-snap.png
Labels: size/XS, waiting for review

#1530 SC-7557 - fixes lernstore modal width
  CHANGELOG.md
  src/components/molecules/AddContentModal.vue
Labels: auto update, ready to merge, size/XS

#1510 SC-7628 - implement classes section
  CHANGELOG.md
  locale/de.json
  src/components/base/BaseInput/BaseInputCheckbox.vue
  src/components/organisms/Ldap/LdapClassesSection.unit.js
  src/components/organisms/Ldap/LdapClassesSection.vue
  src/components/organisms/Ldap/LdapConnectionSection.unit.js
  src/components/organisms/Ldap/LdapConnectionSection.vue
  src/components/organisms/Ldap/LdapRolesSection.vue
  src/components/organisms/Ldap/LdapUsersSection.unit.js
  src/components/organisms/Ldap/LdapUsersSection.vue
  src/pages/administration/ldap/ldap-config.vue
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-checkbox-array_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-checkbox-boolean_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-switch-array_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-switch-boolean_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-modals-action_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-infobox-infobox_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-tabs-tabs_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datafilter-inputs-checkbox_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-ldap-page-ldap-roles-section-ldaprolessection_1-snap.png
Labels: size/XL

#1528 SC-6788 - exchange-wrong-icons-in-storybook
  src/assets/icons/brb.svg
  src/assets/icons/calender.svg
  src/assets/icons/clear.svg
  src/assets/icons/clock.svg
  src/assets/icons/create.svg
  src/assets/icons/delete.svg
  src/assets/icons/fortbildung.svg
  src/assets/icons/gruppen.svg
  src/assets/icons/hpi.svg
  src/assets/icons/mint-ec.svg
  src/assets/icons/n21.svg
  src/assets/icons/open_HPI.svg
  src/assets/icons/search.svg
  src/assets/icons/sort-down.svg
  src/assets/icons/sort-up.svg
  src/assets/icons/sort.svg
  src/assets/icons/success.svg
  src/assets/icons/tasks.svg
  src/assets/icons/thr.svg
  src/assets/icons/tools.svg
  src/assets/icons/user.svg
  tests/screenshot/__image_snapshots__/4-base-ui-components-base-ui-base-icon_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-content-contentsearchbar-contentsearchbar_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-ui-components-molecules-ui-instancetile-instancetile_1-snap.png
Labels: auto update, ready to merge, size/M, waiting for review

#1529 SC-7768 - removed breakpoint desktop
  src/components/molecules/TaskItem.vue
  tests/screenshot/__image_snapshots__/5-molecules-taskitem-with-knobs_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-taskitem-with-pulsating-dot_1-snap.png
Labels: size/XS, waiting for review

#1541 SC-7798 - add permission check to ldap-config
  CHANGELOG.md
  src/pages/administration/ldap/ldap-config.vue
Labels: size/XS

#1518 SC-7489 - LDAP input validation
  CHANGELOG.md
  locale/de.json
  locale/en.json
  src/components/organisms/Ldap/LdapClassesSection.unit.js
  src/components/organisms/Ldap/LdapClassesSection.vue
  src/components/organisms/Ldap/LdapConnectionSection.unit.js
  src/components/organisms/Ldap/LdapConnectionSection.vue
  src/components/organisms/Ldap/LdapRolesSection.unit.js
  src/components/organisms/Ldap/LdapRolesSection.vue
  src/components/organisms/Ldap/LdapUsersSection.unit.js
  src/components/organisms/Ldap/LdapUsersSection.vue
  src/pages/administration/ldap/ldap-config.vue
  src/utils/ldapValidationRegex.js
Labels: size/XL, waiting for review

#1547 SC-7845 - added / fixed changelog github action
  .github/workflows/require_changelog.yml
  CHANGELOG.md
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
Labels: size/M, waiting for review

#1542 SC-7673 - nuxt error handling demo
  CHANGELOG.md
  src/components/templates/ErrorPage.vue
  src/layouts/error.vue
  src/pages/administration/students/new.vue
  src/plugins/axios.js
  src/store/error.js
  src/store/users.js
  src/utils/service-template.js
Labels: size/L

#1560 SC-5473 - create data-testids for testing purposes.
  CHANGELOG.md
  src/components/base/BaseSelect.vue
  src/components/molecules/AddContentModal.vue
  stories/base.stories.js
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
Labels: ready to merge, size/L

#1559 Feature/SC-7796 - Input fields border jumps
  CHANGELOG.md
  package-lock.json
  src/components/base/BaseInput/BaseInputDefault.vue
  tests/screenshot/__image_snapshots__/3-atoms-infomessage-success-message_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-base-ui-basetextarea_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-default-error_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-default-success_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-multiple_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-coursecard-coursecard_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-courseheader-default_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-searchbar-searchbar_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-backenddatatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable-with-filters_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-formcreateuser_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-formdatasourcelogin_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-ldap-page-ldap-roles-section-ldaprolessection_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-pagination_1-snap.png
Labels: WIP

#1567 SC-6992 - changed header name for login-instances page
  CHANGELOG.md
  src/pages/login-instances/index.vue
Labels: size/XS, waiting for review

#1568 SC - 7795 - text fixes ldap page
  locale/de.json
  src/components/organisms/Ldap/LdapClassesSection.vue
Labels: ready to merge, size/S

#1566 SC-6825 - change collapsable icons
  CHANGELOG.md
  src/components/organisms/DropdownMenuMintEc.vue
Labels: auto update, ready to merge, size/XS

#1579 Feature/SC-7880 - fix client side input validation errors
  src/components/organisms/Ldap/LdapClassesSection.vue
  src/utils/ldapValidationRegex.js
Labels: size/XS

#1577 SC-7791 - add icons to ldap page
  locale/de.json
  src/assets/icons/account_tree.svg
  src/assets/icons/admin_panel_settings.svg
  src/assets/icons/class.svg
  src/assets/icons/person_ignore.svg
  src/assets/icons/student.svg
  src/assets/icons/teacher.svg
  src/assets/icons/uid.svg
  src/assets/icons/uuid.svg
  src/components/organisms/Ldap/LdapClassesSection.vue
  src/components/organisms/Ldap/LdapConnectionSection.vue
  src/components/organisms/Ldap/LdapRolesSection.vue
  src/components/organisms/Ldap/LdapUsersSection.vue
Labels: ready to merge, size/L

#1582 SC-7492 - fixes unstable search label in lernstore
  CHANGELOG.md
  src/pages/content/index.vue
Labels: ready to merge, size/XS
