Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2020-01, with the labels that each got.

#413 Title Input Component refactoring for news
  locale/de.json
  src/components/base/BaseButton.scss
  src/components/base/BaseInput/BaseInput.stories.js
  src/components/base/BaseInput/BaseInputDefault.unit.js
  src/components/base/BaseInput/BaseInputDefault.vue
  src/components/molecules/TitleInput.stories.js
  src/components/molecules/TitleInput.unit.js
  src/components/molecules/TitleInput.vue
  src/components/organisms/FormNews.unit.js
  src/components/organisms/FormNews.vue
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-base-inputs-default-title-input-1-snap.png
Labels: size/L

#415 Dockerfile für k8s securityContext aufbereitet
  deploy/Dockerfile.client
Labels: ready to merge

#414 hotfix/mint ec error page
  src/pages/mint-ec/_article.vue
  src/store/ghost.js
Labels: ready to merge, size/M

#419 Feature/VUE-BaseGrid-ColumnGap
  src/components/base/BaseGrid.vue
Labels: ready to merge, size/S

#421 apply falcos changes from ops247 to a new fresh branch
  .travis.yml
Labels: size/XS

#423 npm audit fix
  package-lock.json
  package.json
Labels: bug, dependencies

#424 renamed Dropdownmenu to DropdownMenuMintEc and test
  docs/storybook/helpers/RenderHtml.md
  src/components/organisms/DropdownMenuMintEc.unit.js
  src/components/organisms/DropdownMenuMintEc.vue
  src/pages/mint-ec/_article.vue
  stories/misc.stories.js
Labels: ready to merge

#428 raise npm fail level
  .github/workflows/security-audit.yml
Labels: ready to merge, size/XS

#365 BaseChip and ChipFilter Components
  src/components/base/BaseChip.stories.js
  src/components/base/BaseChip.unit.js
  src/components/base/BaseChip.vue
  src/components/molecules/ChipFilter.unit.js
  src/components/molecules/ChipFilter.vue
  src/pages/courses/index.vue
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-base-basechip-default-1-snap.png
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-misc-dropdownmenumintec-1-snap.png
Labels: ready to merge, size/L

#337 Feature/external lint config
  .eslintrc.js
  .prettierrc.js
  package-lock.json
  package.json
  src/pages/courses/index.vue
  stylelint.config.js
Labels: ready to merge, size/L

#249 New Table Features: Filtering, Sorting and upgraded Pagination
  docs/5-FAQ/5-Setup.md
  src/components/base/BaseInput/BaseInput.stories.js
  src/components/base/BaseInput/BaseInput.unit.js
  src/components/base/BaseInput/BaseInputCheckbox.vue
  src/components/base/BaseInput/BaseInputRadio.vue
  src/components/base/BaseSelect.unit.js
  src/components/base/BaseSelect.vue
  src/components/base/BaseTable.unit.js
  src/components/base/BaseTable.vue
  src/components/base/BaseTable/BaseTable.unit.js
  src/components/base/BaseTable/BaseTable.vue
  src/components/base/BaseTable/FilterMenu.vue
  src/components/base/BaseTable/FilterModal.stories.js
  src/components/base/BaseTable/FilterModal.vue
  src/components/base/BaseTable/RowSelectionBar.vue
  src/components/base/BaseTable/columns.js
  src/components/base/BaseTable/data.js
  src/components/base/BaseTable/testdata.js
  src/components/base/BaseTable/testfilters.js
  src/components/base/BaseTextarea.unit.js
  src/components/organisms/CourseWizard/StepData.unit.js
  src/components/organisms/CourseWizard/StepData.vue
  src/components/organisms/CourseWizard/StepMembers.vue
  src/components/organisms/DropdownMenu.stories.js
  src/components/organisms/DropdownMenu.unit.js
  src/components/organisms/DropdownMenu.vue
  src/components/organisms/Pagination.stories.js
  src/components/organisms/Pagination.unit.js
  src/components/organisms/Pagination.vue
  src/mixins/defaultFilters.js
  src/mixins/defaultFilters.unit.js
  src/pages/administration/index.vue
  src/pages/administration/students.vue
  src/pages/administration/teams.vue
  src/pages/teams/_id/index.vue
  src/serverMiddleware/routes.js
  src/store/users.js
  src/themes/default/styles/utility.scss
  src/themes/default/styles/utility/_spacing.scss
  src/utils/helpers.js
  src/utils/service-template.js
  stories/base.stories.js
  stories/mockData/BaseTable.js
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-base-base-ui-base-table-1-snap.png
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-base-modals-filtermodal-1-snap.png
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-misc-dropdownmenumintec-1-snap.png
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-organisms-dropdownmenu-1-snap.png
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-organisms-pagination-1-snap.png
  tests/unit/setup.js
Labels: size/XXL

#429 refactor Searchbar tests
  src/components/molecules/Searchbar.unit.js
Labels: ready to merge, size/M

#430 Add security audit badge to README
  README.md
Labels: ready to merge, size/XS

#432 jest/no-expect-resolves
  .eslintrc.js
  tests/middleware/permission-check.unit.js
Labels: ready to merge, size/S

#435 removed !important statements from margins
  src/themes/default/styles/utility/_spacing.scss
Labels: ready to merge, size/M

#433 Lint/jest/prefer to have length
  .eslintrc.js
  src/components/base/BaseInput/BaseInputCheckbox.unit.js
  src/components/base/BaseSelect.unit.js
  src/components/base/BaseTable/BaseTable.unit.js
  src/components/legacy/TheFooter.unit.js
  src/components/legacy/TheSidebar.unit.js
  src/components/legacy/TheTopBar.unit.js
  src/components/molecules/ChipFilter.unit.js
  src/components/molecules/CourseTimes.unit.js
  src/components/molecules/CoursesGrid.unit.js
  src/components/molecules/TextEditor.unit.js
  src/components/organisms/CourseWizard/StepData.unit.js
  src/components/organisms/CourseWizard/StepMembers.unit.js
  src/components/organisms/CourseWizard/index.unit.js
  src/components/organisms/Pagination.unit.js
  src/components/organisms/StepProgress.unit.js
  src/components/organisms/Tabs/Tabs.unit.js
  src/serverMiddleware/proxy.unit.js
Labels: ready to merge, size/L

#440 enable jest/prefer-spy-on rule
  .eslintrc.js
  src/components/base/BaseLink.unit.js
  src/components/legacy/MenuQrCode.unit.js
  src/components/molecules/MintEcFooter.vue
  src/components/molecules/TextEditor.unit.js
  src/components/organisms/CourseWizard/StepData.unit.js
  src/components/organisms/FormNews.unit.js
  src/plugins/authenticate.unit.js
Labels: ready to merge, size/M

#441 enable jest/prefer strict equal rule
  .eslintrc.js
  src/components/base/BaseLink.unit.js
  src/components/base/BaseSelect.unit.js
  src/components/base/BaseSpinner.unit.js
  src/components/base/BaseTable/BaseTable.unit.js
  src/components/legacy/TheTopBar.unit.js
  src/components/molecules/TextEditor.unit.js
  src/components/organisms/DropdownMenu.unit.js
  src/components/organisms/FormNews.unit.js
  src/components/organisms/Pagination.unit.js
Labels: ready to merge, size/L

#442 enable jest/no-truthy-falsy rule
  .eslintrc.js
  src/components/base/BaseInput/BaseInputCheckbox.unit.js
  src/components/base/BaseInput/BaseInputHidden.unit.js
  src/components/base/BaseInput/BaseInputRadio.unit.js
  src/components/base/BaseSelect.unit.js
  src/components/base/BaseTextarea.unit.js
  src/components/base/BaseVideo.unit.js
  src/components/molecules/TextEditor.unit.js
Labels: ready to merge, size/L

#431 Feature/ VUE-ContentCard-Menu
  locale/de.json
  locale/en.json
  src/components/molecules/ContentCard.stories.js
  src/components/molecules/ContentCard.unit.js
  src/components/molecules/ContentCard.vue
  src/components/molecules/ContextMenu.stories.js
  src/components/molecules/ContextMenu.unit.js
  src/components/molecules/ContextMenu.vue
  src/components/organisms/FormNews.vue
  src/pages/content/index.vue
  src/store/content.js
  src/themes/default/styles/utility.scss
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-molecules-contextmenu-with-icons-1-snap.png
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-molecules-contextmenu-without-icons-1-snap.png
Labels: ready to merge, size/L

#448 Empty State Component
  src/assets/img/emptystate-graph.svg
  src/components/molecules/EmptyState.stories.js
  src/components/molecules/EmptyState.unit.js
  src/components/molecules/EmptyState.vue
Labels: ready to merge, size/M

#447 Feature/SC-3198/datasource card
  src/assets/img/logo/logo-webuntis.svg
  src/components/molecules/DatasourceCard.stories.js
  src/components/molecules/DatasourceCard.unit.js
  src/components/molecules/DatasourceCard.vue
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-molecules-datasourcecard-with-knobs-1-snap.png
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-molecules-datasourcecard-with-subtitle-1-snap.png
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-molecules-datasourcecard-without-subtitle-1-snap.png
Labels: ready to merge, size/M

#453 update nodesass to fix security audit
  package-lock.json
  package.json
Labels: dependencies, ready to merge

#450 add basic thr color theme
  .travis.yml
  deploy/compose-client_thr.dummy
  deploy/deploy.sh
  src/themes/thr/assets/img/logo/logo-image-mono.svg
  src/themes/thr/assets/img/logo/logo-transparent-mono-48-48.svg
  src/themes/thr/config.js
  src/themes/thr/styles/index.scss
  src/themes/thr/styles/variables.scss
  src/themes/thr/styles/variables/_colors.scss
Labels: size/S

#444 enable `jest/require-top-level-describe` rule
  .eslintrc.js
  package-lock.json
  package.json
  src/components/base/BaseDialog/BaseDialog.unit.js
  src/components/molecules/CourseTimes.unit.js
  src/components/molecules/ModalFooter.unit.js
  src/components/molecules/ModalFooterActions.unit.js
  src/components/molecules/ModalFooterBorder.unit.js
  src/components/molecules/ModalFooterConfirm.unit.js
  src/components/molecules/TextEditor.unit.js
  src/components/organisms/CourseWizard/StepData.unit.js
Labels: size/XL

#454 update lint configs + adjust some tests to match rules
  .eslintrc.js
  package-lock.json
  package.json
  src/components/base/BaseDialog/index.unit.js
  src/components/base/BaseLink.unit.js
  src/components/base/BaseModal.unit.js
  src/components/legacy/LegacyFooter.unit.js
  src/components/legacy/NavigationBar.unit.js
  src/components/molecules/ChipFilter.unit.js
  src/components/molecules/CourseTimes.unit.js
  src/components/molecules/TextEditor.unit.js
  src/components/organisms/FormNews.unit.js
  src/components/templates/ErrorPage.unit.js
  tests/general.unit.js
Labels: dependencies, refactoring, size/M

#456 dependencies/prettier
  docs/1-Tutorials/Localization.md
  package-lock.json
  package.json
  src/components/molecules/CourseCard/index.vue
  src/pages/courses/create.vue
  src/pages/teams/_id/members.vue
  src/pages/teams/index.vue
  src/store/users.js
Labels: dependencies, size/M

#455 do not run integration tests on greenkeeper branch builds
  .travis.yml
Labels: greenkeeper, size/XS

#464 feature/auto dependency update
  .mergify.yml
  .pullapprove.yml
Labels: size/L

#449 Feature/sc 3227 datasource icons
  src/assets/icons/datasource-add.svg
  src/assets/icons/datasource-check.svg
  src/assets/icons/datasource-error.svg
  src/assets/icons/datasource-export.svg
  src/assets/icons/datasource-import.svg
  src/assets/icons/datasource-remove.svg
  src/assets/icons/datasource-sync.svg
  src/assets/icons/datasource.svg
Labels: ready to merge, size/XS

#470 Clear Auth Store after Logout
  src/store/auth.js
Labels: ready to merge, size/XS

#462 dependencies eslint
  package-lock.json
  package.json
Labels: dependencies, ready to merge, size/XS

#481 added placeholder image alt text as prop to emptyState
  src/components/molecules/EmptyState.stories.js
  src/components/molecules/EmptyState.unit.js
  src/components/molecules/EmptyState.vue
Labels: ready to merge

#463 SC-3226/Loading-Modal
  src/components/atoms/CenterSlot.unit.js
  src/components/atoms/CenterSlot.vue
  src/components/base/BaseDialog/BaseDialog.vue
  src/components/base/BaseModal.stories.js
  src/components/base/BaseSpinner.unit.js
  src/components/base/BaseSpinner.vue
  src/components/molecules/LoadingModal.unit.js
  src/components/molecules/LoadingModal.vue
  src/components/molecules/ModalBodyInfo.unit.js
  src/components/molecules/ModalBodyInfo.vue
  src/themes/default/styles/variables/_breakpoints.scss
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-molecules-contentcard-default-1-snap.png
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-molecules-emptystate-default-1-snap.png
  tests/screenshot/ignoredStories.js
Labels: ready to merge

#502 SC-3278 - Empty state page
  locale/de.json
  src/components/molecules/EmptyState.stories.js
  src/components/molecules/EmptyState.vue
  src/pages/administration/datasources/index.vue
Labels: ready to merge

#500 Added datasources to sidebar
  src/utils/sidebarBaseItems.js
Labels: ready to merge

#510 convert all slots to new syntax
  src/components/base/BaseDialog/BaseDialog.vue
  src/components/base/BaseInput/BaseInput.stories.js
  src/components/base/BaseInput/BaseInput.unit.js
  src/components/base/BaseInput/BaseInput.vue
  src/components/base/BaseModal.stories.js
  src/components/base/BaseTextarea.vue
  src/components/molecules/NewsCard.vue
  src/pages/schools.vue
  src/pages/teams/index.vue
  tests/unit/commonTests.js
Labels: ready to merge, size/L

#492 SC-3278, SC-3279, SC-3280 - datasource overview & new page
  locale/de.json
  src/assets/img/datasources/logo-ldap.svg
  src/assets/img/datasources/logo-rss.png
  src/assets/img/datasources/logo-webuntis.png
  src/assets/img/logo/README.md
  src/assets/img/logo/logo-webuntis.svg
  src/components/base/BaseButton.scss
  src/components/molecules/DatasourceCard.stories.js
  src/components/molecules/DatasourceCard.unit.js
  src/pages/administration/datasources/index.vue
  src/pages/administration/datasources/new.vue
  src/store/datasources.js
Labels: ready to merge, size/L

#513 Feature/sc 3199 datasource context menu
  locale/de.json
  src/components/molecules/ContentCard.vue
  src/components/molecules/ContextMenu.unit.js
  src/components/molecules/ContextMenu.vue
  src/components/molecules/DatasourceCard.stories.js
  src/components/molecules/DatasourceCard.vue
  src/pages/administration/datasources/index.vue
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-molecules-datasourcecard-with-context-menu-1-snap.png
Labels: ready to merge

#522 added aria-label to FAB/BaseButton
  locale/de.json
  src/components/base/BaseButton.vue
  src/components/molecules/FloatingFab.stories.js
  src/components/molecules/FloatingFab.unit.js
  src/components/molecules/FloatingFab.vue
  src/pages/administration/datasources/index.vue
  src/pages/content/index.vue
  src/pages/courses/index.vue
  src/pages/news/index.vue
Labels: ready to merge, size/S

#535 DOCKERTAG-Value in Quotes
  .travis.yml
Labels: ready to merge

#537 add lokalise badge
  README.md
Labels: ready to merge

#521 update storybook v.5.3.9
  _templates/new/component/stories.ejs.t
  package-lock.json
  package.json
  src/components/atoms/ColorPicker.stories.js
  src/components/atoms/PulsatingDot.stories.js
  src/components/base/BaseChip.stories.js
  src/components/base/BaseContentContainer.stories.js
  src/components/base/BaseDialog/BaseDialog.stories.js
  src/components/base/BaseGrid.stories.js
  src/components/base/BaseInput/BaseInput.stories.js
  src/components/base/BaseModal.stories.js
  src/components/base/BaseTable/FilterModal.stories.js
  src/components/base/BaseTextarea.stories.js
  src/components/base/BaseTitle.stories.js
  src/components/helpers/RenderHtml.stories.js
  src/components/legacy/LegacyFooter.stories.js
  src/components/legacy/NavigationBar.stories.js
  src/components/molecules/ContentCard.stories.js
  src/components/molecules/ContextMenu.stories.js
  src/components/molecules/DatasourceCard.stories.js
  src/components/molecules/EmptyState.stories.js
  src/components/molecules/FloatingFab.stories.js
  src/components/molecules/FormActions.stories.js
  src/components/molecules/LandingCTA.stories.js
  src/components/molecules/MintEcLinkContainer.stories.js
  src/components/molecules/MintEcPageHeader.stories.js
  src/components/molecules/Searchbar.stories.js
  src/components/molecules/TextEditor.stories.js
  src/components/molecules/TitleInput.stories.js
  src/components/organisms/FormNews.stories.js
  src/components/organisms/StepProgress.stories.js
  src/components/organisms/Tabs/Tabs.stories.js
  stories/.storybook/manager.js
  stories/.storybook/preview.js
  stories/CourseCard.stories.js
  stories/LanguageSwitcher.stories.js
  stories/ProgressRing.stories.js
  stories/Styles.stories.js
  stories/UserHas.stories.js
  stories/base.stories.js
  stories/misc.stories.js
  stories/typography.stories.js
  tests/screenshot/globalSetup.js
  tests/screenshot/stories.stories.js
Labels: ready to merge

#536 SC-3282 | Show Number of already added datasources when adding a new one
  locale/de.json
  src/pages/administration/datasources/index.vue
  src/pages/administration/datasources/new.vue
Labels: ready to merge, size/M

#548 Changed order of links in Navi
  src/layouts/loggedoutFullWidth.vue
Labels: ready to merge, size/XS
