Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2020-06, with the labels that each got.

#1026 OPS-610 - Github actions for test edit
  .github/workflows/test.yml
Labels: size/XS, waiting for review

#1028 SC-4761 - Fix-failing-tests-and-add-additonal-dependency-for-testing
  .gitignore
  docs/0-GettingStarted/1-Build.md
  jest.config.js
  package-lock.json
  package.json
  src/components/atoms/Tab.unit.js
  src/components/atoms/Tab.vue
  src/components/base/BaseBreadcrumb.unit.js
  src/components/base/BaseInput/BaseInput.unit.js
  src/components/base/BaseInput/BaseInputDefault.unit.js
  src/components/base/BaseInput/BaseInputHidden.unit.js
  src/components/base/BaseModal.unit.js
  src/components/base/BaseQrCode.unit.js
  src/components/base/BaseSelect.unit.js
  src/components/base/BaseVideo.unit.js
  src/components/legacy/HelpDropdown.unit.js
  src/components/legacy/MenuQrCode.unit.js
  src/components/legacy/NavigationBar.unit.js
  src/components/legacy/TheSidebar.unit.js
  src/components/legacy/TheSidebar.vue
  src/components/molecules/ContextMenu.unit.js
  src/components/molecules/CourseCard/CourseCardFooter.unit.js
  src/components/molecules/MintEcPageHeader.unit.js
  src/components/molecules/TextEditor.unit.js
  src/components/organisms/CourseWizard/index.unit.js
  src/components/organisms/CourseWizard/index.vue
  src/components/organisms/DataTable/BackendDataTable.unit.js
  src/components/organisms/DropdownMenu.unit.js
  src/components/organisms/DropdownMenuMintEc.unit.js
  src/components/organisms/Tabs/Tabs.unit.js
  src/components/organisms/Tabs/Tabs.vue
  tests/unit/jestMatchers.js
Labels: ready to merge, size/L

#1035 SC-4577 - datenschutz per school
  CHANGELOG.md
  locale/de.json
  src/components/templates/CommonTermsOfUse.vue
  src/pages/TermsOfUse.vue
  src/plugins/authenticate.js
  src/serverMiddleware/routes.js
  src/store/terms-and-conditions.js
  src/themes/n21/components/legacy/TheFooter.vue
  src/themes/n21/components/templates/CommonTermsOfUse.vue
Labels: size/L

#1029 SC-4652 - white modal
  src/components/base/BaseModal.stories.js
  src/components/base/BaseModal.vue
  src/components/molecules/InfoModalFullWidth.vue
  src/pages/account/email/edit.vue
  src/pages/account/index.vue
  src/pages/activation/_activationCode/index.vue
  src/serverMiddleware/routes.js
  src/store/activation.js
  src/utils/service-template.js
Labels: WIP, size/L

#1047 SC-5089 - navbar-consistent-in-nuxt
  src/components/legacy/NavigationBar.stories.js
  src/components/legacy/NavigationBar.unit.js
  src/components/legacy/NavigationBar.vue
  src/utils/navbarBaseItems.js
  tests/screenshot/__image_snapshots__/5-molecules-navigationbar-default_1-snap.png
Labels: size/M

#1052 SC-4717 - content security policy for new schulcloud client
  docs/ContentSecurityPolicy.md
  http-headers.config.js
  nuxt.config.js
  src/serverMiddleware/csp/cors.js
  src/serverMiddleware/csp/security_headers.js
Labels: ready to merge, size/L

#1062 Quickfix - Update pr-automation-comment-reaction.yml
  .github/workflows/pr-automation-comment-reaction.yml
Labels: size/XS

#1063 Quickfix - Create pr-automation-auto-approve.yml
  .github/workflows/pr-automation-auto-approve.yml
Labels: size/S

#1059 SC-5201 - fix-navbar-items
  src/components/legacy/NavigationBar.vue
  src/utils/navbarBaseItems.js
Labels: size/S, waiting for review

#1064 Update pr-automation-auto-approve.yml with SC-Bot-Token
  .github/workflows/pr-automation-auto-approve.yml
Labels: size/XS

#955 SC-3686 - use registration link service
  locale/de.json
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
  src/store/users.js
Labels: ready to merge, size/M

#1050 Quickfix - save some ci time
  .github/workflows/test.yml
Labels: ready to merge, size/XS

#1049 VUE-195 - fix button design hover
  src/components/base/BaseButton.scss
Labels: size/XS

#1089 SC-4998 - MINT EC Cards
  src/assets/icons/mint-ec.svg
  src/pages/login-instances/index.vue
Labels: size/XS, waiting for review

#1083 SC-5180 - adding-lernstore-to-storybook
  src/components/molecules/AddContentModal.vue
  src/components/molecules/ContentCard.stories.js
  src/components/molecules/ContentCard.vue
  src/components/molecules/ContentEmptyState.stories.js
  src/components/molecules/NotificationModal.stories.js
  src/components/organisms/AddContentButton.vue
  src/components/organisms/LernstoreDetailView.stories.js
  src/components/organisms/LernstoreDetailView.vue
  stories/mockData/Resource.js
Labels: size/L, waiting for review

#1074 SC-2769 - clickable-tags-searchbar-improvement
  docs/0-GettingStarted/1-Build.md
  locale/de.json
  src/assets/img/edusharing/SC_Search-Results_Empty-State.svg
  src/components/molecules/AddContentModal.vue
  src/components/molecules/ContentCard.stories.js
  src/components/molecules/ContentCard.vue
  src/components/molecules/ContentEmptyState.stories.js
  src/components/molecules/ContentEmptyState.vue
  src/components/molecules/ContentSearchbar.vue
  src/components/molecules/EdusharingFooter.vue
  src/components/molecules/NotificationModal.stories.js
  src/components/organisms/AddContentButton.vue
  src/components/organisms/LernstoreDetailView.stories.js
  src/components/organisms/LernstoreDetailView.vue
  src/pages/content/index.vue
  stories/mockData/Resource.js
Labels: has conflicts, size/L, waiting for review

#1091 SC-5338 - Fix- login-instances links
  locale/de.json
  src/pages/login-instances/index.vue
Labels: ready to merge, size/XS

#1081 VUE-196 - add backgroundColor to ModalFooterConfirm
  src/components/base/BaseModal.stories.js
  src/components/molecules/ModalFooterConfirm.unit.js
  src/components/molecules/ModalFooterConfirm.vue
Labels: ready to merge, size/S

#1060 SC-2763 - add-content-menu
  CHANGELOG.md
  docs/0-GettingStarted/1-Build.md
  locale/de.json
  package-lock.json
  package.json
  src/assets/icons/ic_default-circle.svg
  src/assets/icons/ic_default.svg
  src/assets/icons/ic_move-to.svg
  src/assets/icons/ic_pdf-circle.svg
  src/assets/icons/ic_pdf.svg
  src/assets/icons/ic_sound-circle.svg
  src/assets/icons/ic_sound.svg
  src/assets/icons/ic_video-circle.svg
  src/assets/icons/ic_video.svg
  src/assets/icons/ic_word-circle.svg
  src/assets/icons/ic_word.svg
  src/assets/img/edusharing/SC_Search-Results_Empty-State.svg
  src/components/base/NotificationModal.stories.js
  src/components/base/NotificationModal.unit.js
  src/components/base/NotificationModal.vue
  src/components/molecules/AddContentModal.vue
  src/components/molecules/ContentCard.stories.js
  src/components/molecules/ContentCard.vue
  src/components/molecules/ContentEmptyState.stories.js
  src/components/molecules/ContentEmptyState.vue
  src/components/molecules/ContentSearchbar.unit.js
  src/components/molecules/ContentSearchbar.vue
  src/components/molecules/EdusharingFooter.vue
  src/components/molecules/ModalBodyInfo.vue
  src/components/molecules/ModalFooterConfirm.vue
  src/components/organisms/AddContentButton.vue
  src/components/organisms/LernstoreDetailView.stories.js
  src/components/organisms/LernstoreDetailView.vue
  src/layouts/legacyLoggedIn.vue
  src/mixins/contentMeta.js
  src/pages/content/index.vue
  src/serverMiddleware/routes.js
  src/store/content.js
  stories/mockData/Resource.js
  tests/screenshot/__image_snapshots__/4-base-ui-components-base-ui-base-collapsible_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-modals-info_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-modals-notificationmodal_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-contentcard-default_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-contentemptystate-contentemptystate_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-contentsearchbar-contentsearchbar_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-edusharingfooter-edusharingfooter_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-notificationmodal-notificationmodal_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-tabs-tabs_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-lernstoredetailview-lernstoredetailview_1-snap.png
Labels: size/XXL, waiting for review
