Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2020-03, with the labels that each got.

#696 added spacings to design tokens in storybook
  stories/DesignTokens.stories.js
Labels: waiting for review

#695 Sc 2762 edusharing branding
  locale/de.json
  locale/en.json
  src/assets/icons/ic_image-circle.svg
  src/assets/img/edusharing/edusharing-logo.svg
  src/components/molecules/ContentSearchbar.vue
  src/components/molecules/EdusharingFooter.stories.js
  src/components/molecules/EdusharingFooter.unit.js
  src/components/molecules/EdusharingFooter.vue
  src/pages/content/index.vue
Labels: size/L

#699 imprint reset typo to default
  src/components/templates/impressum.vue
  src/themes/brb/components/templates/impressum.vue
  src/themes/n21/components/templates/impressum.vue
  src/themes/open/templates/impressum.vue
  src/themes/thr/components/templates/impressum.vue
Labels: ready to merge, size/S

#713 Feature/fix font loading
  src/assets/fonts/PT_Sans-Narrow-Web-Bold.eot
  src/assets/fonts/PT_Sans-Narrow-Web-Bold.svg
  src/assets/fonts/PT_Sans-Narrow-Web-Bold.ttf
  src/assets/fonts/PT_Sans-Narrow-Web-Bold.woff
  src/assets/fonts/PT_Sans-Narrow-Web-Bold.woff2
  src/assets/fonts/PT_Sans-Narrow-Web-Regular.eot
  src/assets/fonts/PT_Sans-Narrow-Web-Regular.svg
  src/assets/fonts/PT_Sans-Narrow-Web-Regular.ttf
  src/assets/fonts/PT_Sans-Narrow-Web-Regular.woff
  src/assets/fonts/PT_Sans-Narrow-Web-Regular.woff2
  src/assets/fonts/PT_Sans-Web-Bold.eot
  src/assets/fonts/PT_Sans-Web-Bold.svg
  src/assets/fonts/PT_Sans-Web-Bold.ttf
  src/assets/fonts/PT_Sans-Web-Bold.woff
  src/assets/fonts/PT_Sans-Web-Bold.woff2
  src/assets/fonts/PT_Sans-Web-Regular.eot
  src/assets/fonts/PT_Sans-Web-Regular.svg
  src/assets/fonts/PT_Sans-Web-Regular.ttf
  src/assets/fonts/PT_Sans-Web-Regular.woff
  src/assets/fonts/PT_Sans-Web-Regular.woff2
  src/assets/img/empty-state/emptyStateSvg_teacher_female.svg
  src/assets/img/empty-state/emptyStateSvg_teacher_female_hand_raised.svg
  src/assets/img/empty-state/emptyStateSvg_teacher_male.svg
  src/assets/img/empty-state/emptyStateSvg_teacher_male_hand_down.svg
  src/components/molecules/ContentEmptyState.vue
  src/themes/default/styles/utility/_fonts.scss
  src/themes/default/styles/variables/_typography.scss
  stories/.storybook/preview-head.html
  stories/.storybook/webpack.config.js
Labels: ready to merge

#715 added icon outline buttons
  docs/3-BeginnerGuide/3-Vorbereitung-für-Entwickler.md
  src/components/base/BaseButton.vue
  stories/base.stories.js
Labels: waiting for review

#712 Moved default styles to schul-cloud/styles package
  docs/2-Styles/0-Variables.md
  package-lock.json
  package.json
  src/components/base/BaseCollapsible.vue
  src/themes/default/styles/utility.scss
  src/themes/default/styles/utility/_breakpoints.scss
  src/themes/default/styles/utility/_colors.scss
  src/themes/default/styles/utility/_typography.scss
  src/themes/default/styles/variables.scss
  src/themes/default/styles/variables/_colors.scss
  src/themes/default/styles/variables/_durations.scss
  src/themes/default/styles/variables/_layers.scss
  src/themes/default/styles/variables/_shadows.scss
  src/themes/default/styles/variables/_sizes.scss
  src/themes/default/styles/variables/_spacing.scss
  src/themes/default/styles/variables/_typography.scss
  stories/icons.stories.js
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-checkbox-array_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-checkbox-boolean_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-switch-array_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-switch-boolean_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-modals-action_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-modals-default_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-modals-dialog_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-modals-info_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-formdatasourcelogin_1-snap.png
Labels: proposal, ready to merge, size/L

#716 hotfix/22.2.2
  package-lock.json
  package.json
  src/layouts/legacyLoggedIn.vue
Labels: size/XS

#719 Test/backend data table
  src/components/organisms/DataTable/BackendDataTable.stories.js
  src/components/organisms/DataTable/BackendDataTable.unit.js
  src/components/organisms/DataTable/BackendDataTable.vue
  src/components/organisms/DataTable/DataTable.data-factory.js
  src/components/organisms/DataTable/DataTable.unit.js
  src/components/organisms/DataTable/DataTable.vue
  src/components/organisms/DataTable/RowSelectionBar.vue
Labels: waiting for review

#735 Feature/SC-3624 expendable FAB
  docs/storybook/molecules/FloatingFab.md
  src/components/base/BaseButton.scss
  src/components/molecules/FabFloating.stories.js
  src/components/molecules/FabFloating.unit.js
  src/components/molecules/FabFloating.vue
  src/components/molecules/FabIcon.stories.js
  src/components/molecules/FabIcon.unit.js
  src/components/molecules/FabIcon.vue
  src/components/molecules/FloatingFab.stories.js
  src/components/molecules/FloatingFab.unit.js
  src/components/molecules/FloatingFab.vue
  src/pages/administration/datasources/index.vue
  src/pages/content/index.vue
  src/pages/courses/index.vue
  src/pages/news/index.vue
  tests/screenshot/__image_snapshots__/5-molecules-fabfloating-default_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-fabicon-multiple-actions_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-fabicon-single-action_1-snap.png
Labels: ready to merge, size/XL

#734 Students Admin Page with Backend-datatable
  locale/de.json
  locale/en.json
  src/components/organisms/DatasourceRunWebuntis.vue
  src/components/organisms/FormDatasourceLogin.vue
  src/pages/administration/students.vue
  src/serverMiddleware/routes.js
  src/store/users.js
Labels: ready to merge, size/L

#739 add add_student fab
  locale/de.json
  src/pages/administration/students.vue
Labels: ready to merge, size/M

#741 Edited click handling expandable fab students
  locale/de.json
  src/pages/administration/students.vue
Labels: ready to merge, size/S

#733 SC-3626/Row-Selection-Bar
  src/components/molecules/ContentCard.stories.js
  src/components/molecules/MintEcLinkContainer.stories.js
  src/components/organisms/DataTable/BackendDataTable.vue
  src/components/organisms/DataTable/RowSelectionBar.vue
  src/components/organisms/DataTable/TableDataRow.vue
  tests/screenshot/__image_snapshots__/5-molecules-contentcard-default_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-minteclinkcontainer-default_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-backenddatatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-rowselectionbar_1-snap.png
Labels: ready to merge, size/S

#742 SC-3513 added edit button, save current page to localStorage
  src/components/base/BaseButton.scss
  src/components/organisms/DataTable/BackendDataTable.vue
  src/pages/administration/students.vue
Labels: ready to merge, size/S

#750 bugfix praseInt for localStorage get
  src/pages/administration/students.vue
Labels: ready to merge

#755 SC-3633 | added autologout env to docs
  docs/0-GettingStarted/1-Build.md
Labels: ready to merge, size/XS

#751 added permission check for single tab
  src/components/atoms/Tab.vue
  src/components/helpers/UserHasPermission.unit.js
  src/components/helpers/UserHasPermission.vue
  src/components/organisms/Tabs/Tabs.stories.js
  src/components/organisms/Tabs/Tabs.vue
  src/mixins/UserHasPermission.js
Labels: ready to merge, size/M

#747 feature/SC-3631 student table actions
  docs/1-Tutorials/WritingTests/UnitTests.md
  jest.config.js
  locale/de.json
  package-lock.json
  package.json
  src/components/base/BaseIcon.vue
  src/mixins/infiniteScrolling.js
  src/mixins/print.js
  src/mixins/print.unit.js
  src/mixins/uid.js
  src/mixins/userIsTabbing.js
  src/pages/administration/students.vue
  src/serverMiddleware/routes.js
  src/utils/service-template.js
Labels: ready to merge, size/L

#748 Service Template Reset Action
  src/utils/service-template.js
Labels: proposal, ready to merge, size/S

#757 Mergify: configuration update
  .mergify.yml
Labels: ready to merge, size/XS

#512 Feature/sc 3287 prepare for enable datasources
  src/layouts/legacyLoggedIn.vue
Labels: size/XS, waiting for review

#771 run and commit lint on lint fail
  .github/workflows/test.yml
  .vscode/settings.json
Labels: waiting for review

#740 Info Box component
  src/components/base/BaseButton.scss
  src/components/base/BaseButton.vue
  src/components/molecules/InfoBox.stories.js
  src/components/molecules/InfoBox.unit.js
  src/components/molecules/InfoBox.vue
  stories/base.stories.js
  tests/screenshot/__image_snapshots__/5-molecules-infobox-infobox_1-snap.png
Labels: ready to merge, size/S

#768 Feature/sc 3039 lokalise logo integration
  locale/de.json
  locale/en.json
  src/assets/img/lokalise_logo.svg
  src/components/legacy/TheFooter.unit.js
  src/components/legacy/TheFooter.vue
  src/themes/brb/components/legacy/TheFooter.vue
  src/themes/open/components/legacy/TheFooter.vue
  src/themes/thr/components/legacy/TheFooter.vue
Labels: ready to merge

#759 add unit tests to print methods
  jest.config.js
  src/mixins/print.js
  src/mixins/print.unit.js
  tests/unit/__snapshots__/mixins/print.unit.js.snap
  tests/unit/snapshotResolver.js
Labels: ready to merge

#756 Legend footer for admin tables
  locale/de.json
  src/assets/icons/doublecheck.svg
  src/assets/icons/sync-symbol.svg
  src/components/molecules/AdminTableLegend.stories.js
  src/components/molecules/AdminTableLegend.vue
  src/pages/administration/students.vue
  src/themes/default/styles/utility/_spacing.scss
Labels: ready to merge, size/L

#783 added findTeachers fct to users store
  src/store/users.js
Labels: ready to merge, size/XS

#749 Feature/sc 3621/create user form
  locale/de.json
  src/components/organisms/FormCreateUser.stories.js
  src/components/organisms/FormCreateUser.unit.js
  src/components/organisms/FormCreateUser.vue
  src/pages/administration/students/index.vue
  src/pages/administration/students/new.vue
  src/store/users.js
Labels: ready to merge, size/L

#796 [Fix] test; failing due to daylight saving time
  src/components/organisms/FormNews.unit.js
Labels: size/XS

#697 Vue 58 integrate universal filter ui into filter menu
  package-lock.json
  package.json
  src/components/organisms/DataFilter/DataFilter.md
  src/components/organisms/DataFilter/DataFilter.stories.js
  src/components/organisms/DataFilter/DataFilter.vue
  src/components/organisms/DataFilter/defaultFilters.js
  src/components/organisms/DataFilter/defaultFilters.unit.js
  src/components/organisms/DataFilter/feathersQueryGenerator.js
  src/components/organisms/DataFilter/feathersQueryGenerator.unit.js
  src/components/organisms/DataTable/BackendDataTable.stories.js
  src/components/organisms/DataTable/BackendDataTable.vue
  src/components/organisms/DataTable/DataTable.data-factory.js
  src/components/organisms/DataTable/DataTable.stories.js
  tests/screenshot/__image_snapshots__/5-molecules-admintablelegend-default_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable-with-filters_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-datafilter_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-formcreateuser_1-snap.png
  tests/unit/__snapshots__/components/organisms/DataFilter/feathersQueryGenerator.unit.js.snap
Labels: ready to merge

#790 add tests to infiniteScrolling mixin
  src/mixins/infiniteScrolling.js
  src/mixins/infiniteScrolling.unit.js
  src/mixins/print.unit.js
  src/pages/content/index.vue
Labels: ready to merge

#791 add unit tests to uid mixin
  src/mixins/uid.unit.js
Labels: ready to merge

#788 use github actions instead of travis for integration tests
  .github/workflows/test.yml
  .travis.yml
Labels: size/M

#746 SC-3040 | Auto-Logout Warning
  locale/de.json
  nuxt.config.js
  src/components/base/BaseModal.stories.js
  src/components/base/BaseModal.unit.js
  src/components/base/BaseModal.vue
  src/components/organisms/AutoLogoutWarning.unit.js
  src/components/organisms/AutoLogoutWarning.vue
  src/layouts/legacyLoggedIn.vue
  src/store/accounts.js
  src/store/autoLogout.js
  stories/.storybook/mockComponents.js
Labels: ready to merge, size/L

#800 symlink changelog in docs to CHANGELOG file so it is shown in the docs
  .prettierignore
  CHANGELOG.md
  docs/Changelog.md
  package.json
Labels: ready to merge, size/M
