Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2020-02, with the labels that each got.

#514 SC- 3284/Status overviewcard
  locale/de.json
  locale/en.json
  src/components/molecules/DatasourceCard.vue
  src/pages/administration/datasources/index.vue
Labels: ready to merge

#572 refactoring/BaseTable
  package-lock.json
  package.json
  src/components/base/BaseButton.scss
  src/components/base/BaseInput/BaseInput.vue
  src/components/base/BaseInput/BaseInputCheckbox.vue
  src/components/base/BaseTable/BaseTable.unit.js
  src/components/base/BaseTable/BaseTable.vue
  src/components/base/BaseTable/FilterMenu.vue
  src/components/base/BaseTable/FilterModal.stories.js
  src/components/base/BaseTable/FilterModal.vue
  src/components/base/BaseTable/columns.js
  src/components/base/BaseTable/data.js
  src/components/base/BaseTable/testdata.js
  src/components/base/BaseTable/testfilters.js
  src/components/organisms/DataTable/BackendDataTable.stories.js
  src/components/organisms/DataTable/BackendDataTable.unit.js
  src/components/organisms/DataTable/BackendDataTable.vue
  src/components/organisms/DataTable/DataTable.data-factory.js
  src/components/organisms/DataTable/DataTable.stories.js
  src/components/organisms/DataTable/DataTable.unit.js
  src/components/organisms/DataTable/DataTable.vue
  src/components/organisms/DataTable/RowSelectionBar.stories.js
  src/components/organisms/DataTable/RowSelectionBar.unit.js
  src/components/organisms/DataTable/RowSelectionBar.vue
  src/components/organisms/DataTable/TableDataRow.stories.js
  src/components/organisms/DataTable/TableDataRow.unit.js
  src/components/organisms/DataTable/TableDataRow.vue
  src/components/organisms/DataTable/TableHeadRow.stories.js
  src/components/organisms/DataTable/TableHeadRow.unit.js
  src/components/organisms/DataTable/TableHeadRow.vue
  src/components/organisms/Pagination.vue
  src/mixins/defaultFilters.js
  src/mixins/defaultFilters.unit.js
  src/utils/helpers.js
  stories/base.stories.js
  stories/mockData/BaseTable.js
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-6-organisms-datatable-backenddatatable-1-snap.png
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-6-organisms-datatable-datatable-1-snap.png
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-6-organisms-datatable-subcomponents-rowselectionbar-1-snap.png
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-6-organisms-datatable-subcomponents-tabledatarow-1-snap.png
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-6-organisms-datatable-subcomponents-tableheadrow-1-snap.png
Labels: size/XXL, waiting for review

#549 SC-3305 | add pagination to datasource overview page
  locale/de.json
  src/pages/administration/datasources/index.vue
Labels: size/M

#574 Feature/datasource login component
  locale/de.json
  locale/en.json
  package-lock.json
  package.json
  src/assets/icons/lock.svg
  src/assets/icons/server.svg
  src/assets/icons/user.svg
  src/assets/img/datasources/logo-ldap.svg
  src/assets/img/datasources/logo-rss.png
  src/assets/img/datasources/logo-rss.svg
  src/assets/img/datasources/logo-webuntis-text.svg
  src/components/base/BaseContentContainer.unit.js
  src/components/base/BaseContentContainer.vue
  src/components/base/BaseInput/BaseInputDefault.vue
  src/components/molecules/DatasourceCard.vue
  src/components/molecules/EmptyState.vue
  src/components/organisms/FormDatasourceLogin.stories.js
  src/components/organisms/FormDatasourceLogin.unit.js
  src/components/organisms/FormDatasourceLogin.vue
  src/pages/administration/datasources/add.vue
  src/pages/administration/datasources/index.vue
  src/pages/administration/datasources/ldap/new.vue
  src/pages/administration/datasources/rss/new.vue
  src/pages/administration/datasources/webuntis/_id/edit.vue
  src/pages/administration/datasources/webuntis/new.vue
  src/serverMiddleware/routes.js
  src/themes/default/styles/utility.scss
  src/themes/default/styles/utility/_typography.scss
Labels: WIP, waiting for review

#570 Title limit in datasource card
  src/components/molecules/DatasourceCard.vue
Labels: ready to merge, size/XS

#593 datasources fixed flows, removed translation duplicates
  locale/de.json
  src/components/organisms/FormDatasourceLogin.vue
  src/pages/administration/datasources/index.vue
Labels: ready to merge

#576 add screenshot tests and changes to storybook
  src/components/organisms/FormDatasourceLogin.stories.js
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-6-organisms-formdatasourcelogin-1-snap.png
Labels: ready to merge

#592 Fix number of already added datasources
  src/pages/administration/datasources/add.vue
  src/pages/administration/datasources/index.vue
  src/pages/administration/datasources/webuntis/new.vue
Labels: ready to merge, size/XS

#600 moved integration-test script from gist into repo
  .travis.yml
Labels: size/XS, waiting for review

#610 require tests to test something
  jest.config.js
  package.json
  src/components/molecules/ContextMenu.unit.js
  src/components/molecules/ContextMenu.vue
  tests/unit/requireAssertions.js
Labels: ready to merge

#602 feature/VUE-173, VUE-176 DataTable refactoring
  .vscode/launch.json
  src/components/organisms/DataTable/BackendDataTable.stories.js
  src/components/organisms/DataTable/BackendDataTable.unit.js
  src/components/organisms/DataTable/BackendDataTable.vue
  src/components/organisms/DataTable/DataTable.data-factory.js
  src/components/organisms/DataTable/DataTable.stories.js
  src/components/organisms/DataTable/DataTable.unit.js
  src/components/organisms/DataTable/DataTable.vue
  src/components/organisms/DataTable/RowSelectionBar.unit.js
  src/components/organisms/DataTable/TableDataRow.unit.js
  src/components/organisms/DataTable/TableHeadRow.unit.js
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-4-base-ui-components-base-ui-base-table-1-snap.png
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-6-organisms-datatable-backenddatatable-1-snap.png
  tests/screenshot/__image_snapshots__/all-screenshot-js-screenshots-6-organisms-datatable-datatable-1-snap.png
Labels: ready to merge, size/XL

#611 Feature/sc 3324 preselect of data
  src/components/organisms/DataTable/DataTable.stories.js
  src/components/organisms/DataTable/DataTable.vue
  src/components/organisms/DataTable/TableDataRow.vue
  src/components/organisms/DatasourceRunWebuntis.stories.js
  src/components/organisms/DatasourceRunWebuntis.vue
  src/components/organisms/Pagination.vue
  src/serverMiddleware/routes.js
  src/store/webuntis-metadata.js
Labels: ready to merge, size/XL

#571 feature/SC-3284/add pending status helpers
  src/pages/administration/datasources/index.vue
  src/store/datasources.js
  src/utils/helpers.js
  src/utils/service-template.js
Labels: ready to merge, size/L

#613 redirect to error login when import failed
  locale/de.json
  src/pages/administration/datasources/index.vue
  src/pages/administration/datasources/webuntis/new.vue
Labels: ready to merge, size/M

#633 Feature/vue 178 data table slot tests
  src/components/organisms/DataTable/DataTable.vue
  src/components/organisms/FormDatasourceLogin.unit.js
Labels: size/L, waiting for review

#636 fix scroll on checkbox toggle
  src/components/base/BaseInput/BaseInputCheckbox.vue
Labels: ready to merge

#635 feature/VUE-178 add slot pass through tests
  src/components/organisms/DataTable/DataTable.unit.js
  src/components/organisms/DataTable/TableDataRow.vue
Labels: ready to merge, size/M

#634 feature @vue/test-utils upgrade
  package-lock.json
  package.json
  src/components/atoms/ProgressRing.unit.js
  src/components/base/BaseCollapsible.unit.js
  src/components/base/BaseDialog/BaseDialog.unit.js
  src/components/base/BaseInput/BaseInputCheckbox.unit.js
  src/components/base/BaseInput/BaseInputDefault.unit.js
  src/components/base/BaseInput/BaseInputRadio.unit.js
  src/components/base/BaseModal.unit.js
  src/components/base/BaseTextarea.unit.js
  src/components/helpers/RenderHtml.unit.js
  src/components/legacy/PopupIcon.unit.js
  src/components/legacy/PopupIconInitials.unit.js
  src/components/molecules/ContextMenu.unit.js
  src/components/molecules/Searchbar.unit.js
  src/components/molecules/TextEditor.unit.js
  src/components/organisms/CourseWizard/index.unit.js
  src/components/organisms/DropdownMenu.unit.js
  src/components/organisms/DropdownMenuMintEc.unit.js
  src/components/organisms/Tabs/Tabs.unit.js
  src/components/organisms/Tabs/Tabs.vue
  tests/unit/setup.js
  tests/unit/stubs.js
Labels: ready to merge, size/L

#649 SC-3435 - Vertical Center Sort Icon
  src/components/organisms/DataTable/TableHeadRow.vue
Labels: ready to merge, size/XS

#638 Update DataTable selection color
  src/components/organisms/DataTable/RowSelectionBar.vue
  src/components/organisms/DataTable/TableDataRow.vue
  src/themes/default/styles/variables/_colors.scss
  tests/screenshot/__image_snapshots__/6-organisms-datatable-backenddatatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-rowselectionbar_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
Labels: ready to merge

#641 Feature/SC-3438 DataTable select bugfixes
  babel.config.js
  package-lock.json
  package.json
  src/components/organisms/DataTable/DataTable.vue
Labels: ready to merge, size/M

#639 Feature/sc 3432 preselect all
  src/components/organisms/DatasourceRunWebuntis.vue
Labels: ready to merge, size/S

#648 feature/SC-3433 data table sort hint
  src/components/organisms/DataTable/TableHeadRow.unit.js
  src/components/organisms/DataTable/TableHeadRow.vue
  tests/screenshot/__image_snapshots__/6-organisms-datatable-backenddatatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tableheadrow_1-snap.png
Labels: ready to merge

#640 SC-3307 configurable 401 redirect
  nuxt.config.js
  src/components/legacy/TheFooter.vue
  src/layouts/legacyLoggedIn.vue
  src/plugins/authenticate.js
  src/utils/documents.js
Labels: size/M

#612 Responsive Button Component
  package-lock.json
  package.json
  src/components/base/BaseButton.scss
  src/components/base/BaseButton.unit.js
  src/components/base/BaseButton.vue
  src/components/legacy/PopupIcon.vue
  src/components/legacy/TheTopBar.vue
  src/components/molecules/ContentCard.vue
  src/components/molecules/ContextMenu.stories.js
  src/components/molecules/DatasourceCard.stories.js
  src/components/molecules/DatasourceCard.vue
  src/components/molecules/ResponsiveIconButton.stories.js
  src/components/molecules/ResponsiveIconButton.unit.js
  src/components/molecules/ResponsiveIconButton.vue
  src/components/molecules/TextEditor.vue
  src/pages/administration/datasources/add.vue
  src/pages/administration/datasources/index.vue
  src/plugins/global.js
  stories/base.stories.js
  tests/unit/setup.js
Labels: ready to merge, size/L

#650 remove unused dependencies
  package.json
  stories/.storybook/webpack.config.js
  tests/screenshot/__image_snapshots__/5-molecules-responsivebutton-default_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-backenddatatable_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-datatable_1-snap.png
Labels: ready to merge

#392 VUE-Insights-dashboard
  nuxt.config.js
  package-lock.json
  package.json
  src/components/base/BaseCard.vue
  src/components/molecules/InsightsCard.unit.js
  src/components/molecules/InsightsCard.vue
  src/components/molecules/InsightsCharts.unit.js
  src/components/molecules/InsightsCharts.vue
  src/pages/insights/index.vue
  src/serverMiddleware/routes.js
  src/store/insights.js
  src/utils/insights/activityByRoleChart.js
  src/utils/insights/avgInteractTime.js
  src/utils/insights/avgPageLoadedChart.js
  src/utils/insights/uniquePageCountChart.js
  src/utils/insights/weeklyActiveUsersChart.js
  src/utils/insights/weeklyActivityChart.js
Labels: ready to merge, size/XL

#653 SC-3442 datasources: added attribute new-pwd, avoids pre-fill username in ff, chrome, safari
  src/pages/administration/datasources/webuntis/new.vue
Labels: size/XS

#661 feature/SC-3434 use round material icons
  src/components/base/BaseIcon.vue
Labels: ready to merge, size/XS

#656 update to node LTS with renewed package-lock.json
  .nvmrc
  lint-staged.config.js
  package-lock.json
  package.json
Labels: waiting for review

#660 feature/SC-3441 "x/y Datensätze importiert"
  locale/de.json
  src/components/organisms/DatasourceRunWebuntis.vue
Labels: ready to merge, size/S

#666 bugfix Context Menu in LernStore
  src/components/base/BaseButton.scss
  src/components/molecules/ContextMenu.vue
Labels: size/S, waiting for review

#663 feature/SC-3437 checkbox refactoring
  src/components/base/BaseInput/BaseInput.stories.js
  src/components/base/BaseInput/BaseInput.unit.js
  src/components/base/BaseInput/BaseInputCheckbox.stories.js
  src/components/base/BaseInput/BaseInputCheckbox.unit.js
  src/components/base/BaseInput/BaseInputCheckbox.vue
  src/components/organisms/DataTable/TableDataRow.vue
Labels: ready to merge, size/L

#669 feature/remove sinon dependency
  package-lock.json
  package.json
  src/components/base/BaseDialog/BaseDialog.unit.js
  src/components/molecules/TextEditor.unit.js
  src/components/organisms/FormDatasourceLogin.unit.js
  src/components/organisms/FormNews.unit.js
  tests/unit/setup.js
Labels: ready to merge

#671 hotfix/22.2.1 - serve /nuxtversion page as json
  git-info.js
  nuxt.config.js
  package-lock.json
  package.json
  src/pages/nuxtversion.vue
  src/serverMiddleware/nuxtversion.js
Labels: waiting for review

#672 use travis branch version for nuxtversion just like in the other repos
  .dockerignore
  .gitignore
  deploy/build.sh
  src/serverMiddleware/nuxtversion.js
  src/serverMiddleware/nuxtversion.unit.js
Labels: ready to merge, size/S

#685 Bump @storybook/* from 5.3.13 to 5.3.14
  package-lock.json
  package.json
Labels: dependencies, size/S, waiting for review

#665 feature/SC-3436 some selected state in DataTables
  src/components/organisms/DataTable/BackendDataTable.vue
  src/components/organisms/DataTable/DataTable.unit.js
  src/components/organisms/DataTable/DataTable.vue
  src/components/organisms/DataTable/RowSelectionBar.stories.js
  src/components/organisms/DataTable/RowSelectionBar.vue
  src/components/organisms/DataTable/TableHeadRow.stories.js
  src/components/organisms/DataTable/TableHeadRow.vue
Labels: ready to merge, size/L

#668 feature/VUE-177 document DataTable
  src/components/organisms/DataTable/DataTable.md
  src/components/organisms/DataTable/DataTable.stories.js
  src/components/organisms/DataTable/DataTable.vue
Labels: ready to merge, size/L

#686 Design System h5, h6 bold, change in line-height-sm, story for line-heights
  src/themes/default/styles/utility/_typography.scss
  src/themes/default/styles/variables/_typography.scss
  stories/typography.stories.js
Labels: ready to merge, size/S

#659 feature/SC-3443 webuntis form reload bugfix
  _templates/new/component/prompt.js
  _templates/new/component/unit.ejs.t
  locale/de.json
  locale/en.json
  src/components/organisms/FormDatasourceLogin.vue
  src/components/organisms/FormDatasourceLoginWebuntis.unit.js
  src/components/organisms/FormDatasourceLoginWebuntis.vue
  src/pages/administration/datasources/webuntis/_id/edit.vue
  src/pages/administration/datasources/webuntis/new.vue
Labels: ready to merge, size/L

#662 Feature/sc 3477 change url
  locale/de.json
  src/pages/administration/datasources/new.vue
Labels: ready to merge
