Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2021-05, with the labels that each got.

#1595 Feature/ops 1559 enhance build pipeline
  .github/mergeable.yml
  .travis.yml
  CHANGELOG.md
  deploy/build.sh
  deploy/buildAndDeployFilter.sh
  deploy/deploy.sh
Labels: size/L, waiting for review

#1763 SC-9023 - Homeworks Dashboard
  .github/workflows/surge-teardown.yml
  locale/de.json
  locale/en.json
  locale/es.json
  package-lock.json
  src/assets/img/courses/task-new.svg
  src/assets/img/empty-state/tasks-empty.svg
  src/components/organisms/HomeworksList.stories.js
  src/components/organisms/HomeworksList.unit.js
  src/components/organisms/HomeworksList.vue
  src/pages/beta/dashboard.unit.js
  src/pages/beta/dashboard.vue
  src/serverMiddleware/routes.js
  src/store/homeworks.js
  src/store/homeworks.unit.js
  stories/.storybook/preview.js
  stories/mockData/Homeworks.js
  tests/unit/setup.js
Labels: changes requested, size/L, waiting for review

#1776 SC-9063 remove unsafe-inline from CSP
  CHANGELOG.md
  http-headers.config.js
  package-lock.json
  package.json
Labels: size/S

#1775 SC-9026 Show duedates in homeworks dashboard [Odyssey]
  locale/de.json
  locale/en.json
  locale/es.json
  src/components/organisms/HomeworksList.unit.js
  src/components/organisms/HomeworksList.vue
  src/plugins/datetime.js
  stories/mockData/Homeworks.js
  tests/plugins/datetime.unit.js
Labels: size/M

#1779 SC-9049 embed tasks in sidebar [Odyssey]
  locale/de.json
  locale/en.json
  locale/es.json
  src/components/legacy/TheSidebar.vue
  src/pages/tasks/open.unit.js
  src/pages/tasks/open.vue
  src/serverMiddleware/routes.js
  src/utils/sidebarBaseItems.js
Labels: ready to merge, waiting for review

#1777 sc-9065 - Integrate styles repo into nuxt client
  CHANGELOG.md
  package-lock.json
  package.json
  src/themes/default/styles/variables.scss
  src/themes/default/styles/variables/_breakpoints.scss
  src/themes/default/styles/variables/_colors.scss
  src/themes/default/styles/variables/_durations.scss
  src/themes/default/styles/variables/_layers.scss
  src/themes/default/styles/variables/_shadows.scss
  src/themes/default/styles/variables/_sizes.scss
  src/themes/default/styles/variables/_spacing.scss
  src/themes/default/styles/variables/_typography.scss
  src/themes/demo/styles/variables.scss
  src/themes/demo/styles/variables/_breakpoints.scss
  src/themes/demo/styles/variables/_colors.scss
  src/themes/demo/styles/variables/_durations.scss
  src/themes/demo/styles/variables/_layers.scss
  src/themes/demo/styles/variables/_shadows.scss
  src/themes/demo/styles/variables/_sizes.scss
  src/themes/demo/styles/variables/_spacing.scss
  src/themes/demo/styles/variables/_typography.scss
Labels: size/L

#1778 SC-9050 homeworks dashboard empty state [Odyssey]
  locale/de.json
  locale/en.json
  locale/es.json
  src/assets/img/empty-state/Task_Empty_State.svg
  src/components/molecules/vCustomEmptyState.stories.js
  src/components/molecules/vCustomEmptyState.unit.js
  src/components/molecules/vCustomEmptyState.vue
  src/components/organisms/HomeworksList.unit.js
  src/components/organisms/HomeworksList.vue
  src/pages/tasks/open.unit.js
  src/pages/tasks/open.vue
Labels: size/L

#1783 SC-9077 - store/use of store refactoring
  CHANGELOG.md
  src/components/organisms/DatasourceRunWebuntis.vue
  src/components/organisms/FormDatasourceLogin.unit.js
  src/components/organisms/FormDatasourceLogin.vue
  src/components/organisms/FormNews.vue
  src/pages/activation/_activationCode/index.vue
  src/pages/administration/datasources/_datasource/run/_run.vue
  src/pages/administration/datasources/index.vue
  src/pages/administration/datasources/new.vue
  src/pages/administration/datasources/webuntis/_id/edit.vue
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
  src/pages/mint-ec/_article.vue
  src/store/ghost.js
  src/store/users.js
  src/store/users.unit.js
  src/store/webuntis-metadata.js
Labels: changes requested, size/L, waiting for review

#1759 SC-9004 - nuxt env config
  CHANGELOG.md
  http-headers.config.js
  jest.config.js
  nuxt.config.js
  package-lock.json
  src/components/legacy/TheFooter.unit.js
  src/components/legacy/TheFooter.vue
  src/components/organisms/Messenger/MatrixMessenger.unit.js
  src/components/organisms/Messenger/MatrixMessenger.vue
  src/middleware/links-fallback.js
  src/pages/administration/students/consent.vue
  src/pages/administration/students/index.unit.js
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.unit.js
  src/pages/administration/teachers/index.vue
  src/plugins/authenticate.js
  src/plugins/authenticate.unit.js
  src/plugins/configInit.js
  src/serverMiddleware/csp/cors.js
  src/serverMiddleware/csp/security_headers.js
  src/store/auth.js
  src/store/autoLogout.js
  src/store/content.js
  src/store/env-config.js
  src/store/env-config.unit.js
  src/store/filePaths.js
  src/store/filePaths.unit.js
  src/store/messenger.js
  src/themes/brb/components/legacy/TheFooter.vue
  src/themes/demo/components/legacy/TheFooter.vue
  src/themes/int/components/legacy/TheFooter.vue
  src/themes/n21/components/templates/CommonTermsOfUse.vue
  src/themes/open/components/legacy/TheFooter.vue
  src/themes/thr/components/legacy/TheFooter.vue
  src/utils/documents.js
  tests/middleware/links-fallback.unit.js
  tests/unit/setup.js
Labels: WIP, size/XL

#1787 Feature/sc 9004 nuxt pipline
  .travis.yml
  CHANGELOG.md
  deploy/build.sh
  lint-staged.config.js
  package-lock.json
Labels: size/L

#1789 Feature/odyssey homeworks loading state
  src/components/organisms/HomeworksList.stories.js
  src/components/organisms/HomeworksList.unit.js
  src/components/organisms/HomeworksList.vue
  src/pages/tasks/open.unit.js
  src/pages/tasks/open.vue
  src/store/homeworks.js
  src/store/homeworks.unit.js
  src/utils/service-template.js
  tests/screenshot/__image_snapshots__/0-vuetify-homeworks-homeworkslist-homeworkslist_1-snap.png
  tests/screenshot/__image_snapshots__/0-vuetify-homeworks-homeworkslist-homeworkslistloading_1-snap.png
Labels: size/L
