Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2021-12, with the labels that each got.

#1977 BC-872 - add set-up node action to test workflow
  .github/workflows/test.yml
  CHANGELOG.md
Labels: waiting for review, run tests, run unstable tests

#1980 Hotfix/bc 904 fix course filter
  CHANGELOG.md
  src/store/tasks.ts
Labels: waiting for review

#1986 BC-741 - Sort and split ansible rols
  CHANGELOG.md
  ansible/roles/nuxt-client-core/tasks/main.yml
  ansible/roles/nuxt-client-core/templates/configmap-files.yml.j2
  ansible/roles/nuxt-client-core/templates/configmap.yml.j2
  ansible/roles/nuxt-client-core/templates/deployment.yml.j2
  ansible/roles/nuxt-client-core/templates/svc.yml.j2
  ansible/roles/nuxt-client-ldap/tasks/main.yml
  ansible/roles/nuxt-client-ldap/templates/deployment.yml.j2
  ansible/roles/nuxt-client-ldap/templates/svc.yml.j2
Labels: waiting for review

#1990 version 26.20.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: waiting for review

#1965 Feature/bc 609 finished tasks
  CHANGELOG.md
  locale/de.json
  locale/en.json
  locale/es.json
  src/assets/icons/task-finished.vue
  src/components/atoms/vCustomFab.unit.ts
  src/components/atoms/vCustomFab.vue
  src/components/molecules/vTaskItemStudent.unit.js
  src/components/molecules/vTaskItemStudent.vue
  src/components/molecules/vTaskItemTeacher.unit.js
  src/components/molecules/vTaskItemTeacher.vue
  src/components/organisms/TasksList.stories.js
  src/components/organisms/TasksList.unit.js
  src/components/organisms/TasksList.vue
  src/components/templates/TasksDashboardMain.vue
  src/components/templates/TasksDashboardStudent.unit.js
  src/components/templates/TasksDashboardStudent.vue
  src/components/templates/TasksDashboardTeacher.unit.js
  src/components/templates/TasksDashboardTeacher.vue
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
  src/store/finished-tasks.ts
  src/store/finished-tasks.unit.ts
  src/store/tasks.unit.ts
  src/themes/base/vuetify.options.js
Labels: run tests

#1989 BC-641 - fixed ripple effect bug
  CHANGELOG.md
  src/components/atoms/vCustomSwitch.unit.ts
  src/components/atoms/vCustomSwitch.vue
  src/components/organisms/administration/PrivacySettings.vue
Labels: run tests

#1987 Feature/bc 826 status finished tasks
  CHANGELOG.md
  src/components/molecules/vTaskItemStudent.vue
  src/components/molecules/vTaskItemTeacher.unit.js
  src/components/molecules/vTaskItemTeacher.vue
  src/components/templates/TasksDashboardMain.unit.js
  src/components/templates/TasksDashboardMain.vue
  src/components/templates/TasksDashboardStudent.unit.js
  src/components/templates/TasksDashboardStudent.vue
  src/components/templates/TasksDashboardTeacher.unit.js
  src/components/templates/TasksDashboardTeacher.vue
  src/store/finished-tasks.ts
  src/store/finished-tasks.unit.ts
  src/store/tasks.ts
  src/store/tasks.unit.ts
Labels: run tests

#1993 BC-942 - Fix the workflow file for the clan workflow
  .github/workflows/clean.yml
Labels: waiting for review

#1991 BC-920 removed changelog
  .github/workflows/require_changelog.yml
  CHANGELOG.md
Labels: waiting for review

#1995 BC-925 - fixing groupId
  locale/de.json
  locale/en.json
  locale/es.json
  src/pages/rooms-overview.unit.js
  src/pages/rooms-overview.vue
Labels: waiting for review, run tests

#1996 Feature/bc 922 rooms overview fab
  locale/de.json
  locale/en.json
  locale/es.json
  src/components/atoms/vCustomFab.vue
  src/components/templates/DefaultWireframe.vue
  src/components/templates/TasksDashboardMain.vue
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
  src/pages/rooms-overview.unit.js
  src/pages/rooms-overview.vue
  src/themes/base/styles/variables/_layers.scss
  tests/screenshot/__image_snapshots__/0-vuetify-atoms-vcustomfab-multiple-actions_1-snap.png
Labels: waiting for review

#1997 BC-830 - Showing archived course in the course list page
  src/components/atoms/vRoomAvatar.unit.ts
  src/components/atoms/vRoomAvatar.vue
  src/pages/rooms-list.unit.ts
  src/pages/rooms-list.vue
  src/serverApi/v3/api.ts
  src/store/rooms.ts
  src/store/rooms.unit.ts
  src/store/types/rooms.ts
Labels: waiting for review

#2001 BC-744 - BC-937 - Update the ansible group and host vars
  ansible/group_vars/all/nuxt-client.yml
  ansible/group_vars/brb/nuxt-client.yml
  ansible/group_vars/default/nuxt-client.yml
  ansible/group_vars/develop/nuxt-client.yml
  ansible/group_vars/nbc/nuxt-client.yml
  ansible/group_vars/reference/nuxt-client.yml
Labels: waiting for review

#1999 feature/BC-921 - Adding toggle drag&drop feature
  locale/de.json
  locale/en.json
  locale/es.json
  nuxt.config.js
  src/components/atoms/vCustomSwitch.vue
  src/components/atoms/vRoomAvatar.unit.ts
  src/components/atoms/vRoomAvatar.vue
  src/components/molecules/RoomModal.unit.ts
  src/components/molecules/RoomModal.vue
  src/components/molecules/vRoomGroupAvatar.unit.ts
  src/components/molecules/vRoomGroupAvatar.vue
  src/pages/rooms-overview.unit.js
  src/pages/rooms-overview.vue
Labels: waiting for review

#2000 bc-951 ux fixes rooms overview
  locale/de.json
  locale/en.json
  locale/es.json
  src/pages/rooms-list.vue
  src/pages/rooms-overview.vue
Labels: run tests

#2003 versionbump 26.21.0
  package-lock.json
  package.json
Labels: waiting for review

#1998 Feature/BC-882 - Adding course links to avatar components
  src/components/atoms/vRoomAvatar.unit.ts
  src/components/atoms/vRoomAvatar.vue
  src/pages/rooms-list.unit.ts
  src/pages/rooms-list.vue
  src/pages/rooms-overview.unit.js
  src/pages/rooms-overview.vue
  src/store/rooms.ts
  src/store/rooms.unit.ts
  src/store/types/rooms.ts
Labels: waiting for review

#2005 BC-781 - Update deploy and clean github workflow
  .github/workflows/clean.yml
  .github/workflows/push.yml
Labels: waiting for review

#2004 BC-980 - More empty spaces for courses on rooms-overview page
  src/components/atoms/vRoomAvatar.vue
  src/pages/rooms-overview.unit.js
  src/pages/rooms-overview.vue
Labels: waiting for review, changes requested

#1992 BC-643/BC-533 remove old task overview menu entry & navigate to new task overview
  locale/de.json
  locale/en.json
  locale/es.json
  nuxt.config.js
  src/components/atoms/vCustomFab.vue
  src/components/molecules/vTaskItemTeacher.vue
  src/components/templates/TasksDashboardMain.unit.js
  src/components/templates/TasksDashboardMain.vue
  src/middleware/redirects.js
  src/pages/tasks/index.unit.js
  src/pages/tasks/index.vue
  src/serverMiddleware/routes.js
  src/utils/sidebarBaseItems.js
Labels: waiting for review, run tests
