Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2021-01, with the labels that each got.

#1627 SC-8356 - authenticate docker hub requests
  .github/workflows/test.yml
  CHANGELOG.md
Labels: size/XS

#1628 SC-7762 - adds collection icon for Lern-Store card
  CHANGELOG.md
  locale/de.json
  locale/en.json
  src/assets/icons/ic_collection.svg
  src/components/organisms/ContentCard.stories.js
  src/components/organisms/ContentCard.unit.js
  src/components/organisms/ContentCard.vue
  src/mixins/contentMeta.js
  stories/mockData/Collection.js
  stories/mockData/Resource.js
  tests/screenshot/__image_snapshots__/6-organisms-content-contentcard-collectioncard_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-content-contentcard-contentcard_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-content-lernstoredetailview-lernstoredetailview_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
Labels: size/L, waiting for review

#1631 SC-8381 - changes welcome text for Lern-Store
  locale/de.json
  locale/en.json
  tests/screenshot/__image_snapshots__/5-molecules-content-states-contentinitialstate_1-snap.png
Labels: ready to merge, size/XS

#1632 SC-8323 - clear collection when querying
  CHANGELOG.md
  src/components/organisms/LernstoreCollectionDetailView.vue
  src/store/content.js
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
Labels: size/M

#1634 SC-8328 - adds back btn in Lern-Store
  CHANGELOG.md
  locale/de.json
  locale/en.json
  src/components/organisms/ContentCard.vue
  src/components/organisms/LernstoreCollectionDetailView.vue
  src/components/organisms/LernstoreDetailView.vue
  src/pages/content/_id/index.vue
  src/pages/content/index.vue
Labels: ready to merge, size/L

#1637 SC-8454 - delay search
  CHANGELOG.md
  package-lock.json
  package.json
  src/pages/content/index.vue
Labels: ready to merge, size/S

#1640 SC-8390 - adds Lern-Store collection flag
  CHANGELOG.md
  nuxt.config.js
  src/pages/content/_id/index.vue
  src/store/content.js
Labels: ready to merge, size/S

#1641 SC-8433 - changed text in Lern-Store
  CHANGELOG.md
  locale/de.json
  locale/en.json
Labels: ready to merge, size/XS

#1646 Kubectls experiments ssl
  .github/workflows/main.yml
  k8s/configmap.yaml
  k8s/ingress.yaml
Labels: size/S

#1645 SC-8514 - QR Code generation fails
  CHANGELOG.md
  locale/de.json
  locale/en.json
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
Labels: size/M

#1648 Adding support for branches with special characters
  .github/workflows/main.yml
Labels: size/S
