Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2021-10, with the labels that each got.

#1925 BC-364 - run unstable e2e tests
  .github/workflows/test_unstable_e2e.yml
  CHANGELOG.md
Labels: size/M, run unstable tests

#1923 feature/BC-382 - fixed console error and refactoring
  CHANGELOG.md
  src/components/atoms/vCustomSwitch.unit.ts
  src/components/atoms/vCustomSwitch.vue
  src/components/organisms/administration/AuthSystems.unit.js
  src/components/organisms/administration/AuthSystems.vue
  src/components/organisms/administration/GeneralSettings.vue
  src/components/organisms/administration/SchoolPolicies.vue
  src/components/organisms/vCustomDialog.unit.js
  src/components/organisms/vCustomDialog.vue
  src/pages/administration/school-settings.vue
  src/store/schools.ts
  src/store/schools.unit.ts
Labels: size/L, run tests

#1921 BC-312 - added new DefaultWireframe to task overview
  CHANGELOG.md
  src/components/templates/DefaultWireframe.stories.js
  src/components/templates/DefaultWireframe.vue
  src/components/templates/TasksDashboardMain.stories.js
  src/components/templates/TasksDashboardMain.unit.js
  src/components/templates/TasksDashboardMain.vue
  src/components/templates/TasksDashboardStudent.unit.js
  src/components/templates/TasksDashboardStudent.vue
  src/components/templates/TasksDashboardTeacher.unit.js
  src/components/templates/TasksDashboardTeacher.vue
  src/pages/tasks/assigned.vue
  src/pages/tasks/open.vue
  tests/screenshot/__image_snapshots__/0-vuetify-templates-defaultwireframe-content-width-with-breadcrumbs_1-snap.png
  tests/screenshot/__image_snapshots__/0-vuetify-templates-defaultwireframe-full-width-without-breadcrumbs_1-snap.png
  tests/screenshot/__image_snapshots__/0-vuetify-templates-defaultwireframe-with-breadcrumbs-and-custom-header_1-snap.png
  tests/screenshot/__image_snapshots__/0-vuetify-templates-tasksdashboard-tasks-dashboard-student_1-snap.png
  tests/screenshot/__image_snapshots__/0-vuetify-templates-tasksdashboard-tasks-dashboard-teacher_1-snap.png
Labels: size/L, run tests

#1919 Hotfix/bc 365 fix pagination
  CHANGELOG.md
  package-lock.json
  package.json
  src/store/tasks.js
Labels: size/S, waiting for review, run tests

#1939 OPS-2796 Changed login pages to new domains
  locale/de.json
  locale/en.json
  locale/es.json
  src/pages/login-instances/index.vue
Labels: size/S
