Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2021-02, with the labels that each got.

#1651 SC-8577 - hotfix/roles section validation fix
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/organisms/Ldap/LdapRolesSection.unit.js
  src/components/organisms/Ldap/LdapRolesSection.vue
Labels: size/M

#1652 SC-8600 - fix version
  package-lock.json
  package.json
Labels: size/XS

#1558 OPS-1508 - Updated limits for cpu and ram to the docker compose files
  CHANGELOG.md
  deploy/compose-client_brb.dummy
  deploy/compose-client_default.dummy
  deploy/compose-client_int.dummy
  deploy/compose-client_n21.dummy
  deploy/compose-client_open.dummy
  deploy/compose-client_thr.dummy
Labels: auto update, size/M, waiting for review

#1659 SC-8156 - introduce spanish to the client
  CHANGELOG.md
  locale/de.json
  locale/es.json
  src/components/organisms/DataTable/RowSelectionBar.vue
  src/plugins/i18n.js
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
Labels: size/M

#1642 SC-7937 - Adds checkboxes to collection items
  CHANGELOG.md
  src/components/base/BaseInput/BaseInputCheckbox.vue
  src/components/molecules/AddContentModal.unit.js
  src/components/molecules/AddContentModal.vue
  src/components/organisms/AddContentButton.vue
  src/components/organisms/ContentCard.stories.js
  src/components/organisms/ContentCard.unit.js
  src/components/organisms/ContentCard.vue
  src/components/organisms/LernstoreCollectionDetailView.unit.js
  src/components/organisms/LernstoreCollectionDetailView.vue
  src/components/organisms/LernstoreDetailView.unit.js
  src/components/organisms/LernstoreDetailView.vue
  src/store/content.js
  src/utils/helpers.js
  stories/mockData/Collection.js
  stories/mockData/CollectionElement.js
  stories/mockData/Resource.js
  tests/screenshot/__image_snapshots__/6-organisms-content-contentcard-collectioncard_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-content-contentcard-contentcard_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-content-contentcard-selectablecard_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-content-lernstoredetailview-lernstoredetailview_1-snap.png
Labels: size/XL

#1665 SC-8613 - LDAP-config-verify: Add checkbox to choose full or partial lo…
  CHANGELOG.md
  locale/de.json
  locale/en.json
  package-lock.json
  package.json
  src/pages/administration/ldap/activate.vue
  src/pages/administration/ldap/config.vue
  src/store/ldap-config.js
  src/store/ldap-config.unit.js
Labels: size/L, waiting for review

#1666 Revert "SC-8613 - LDAP-config-verify: Add checkbox to choose full or partial lo…"
  CHANGELOG.md
  locale/de.json
  locale/en.json
  package-lock.json
  package.json
  src/pages/administration/ldap/activate.vue
  src/pages/administration/ldap/config.vue
  src/store/ldap-config.js
  src/store/ldap-config.unit.js
Labels: size/L

#1662 SC-7944 - changes field for Lern-Store content id; adds a link to collection
  CHANGELOG.md
  src/components/organisms/AddContentButton.vue
  src/components/organisms/ContentCard.vue
  src/components/organisms/LernstoreDetailView.vue
  src/pages/content/index.vue
  stories/mockData/Resource.js
Labels: ready to merge, size/M

#1673 SC-8681 - remove consent column
  CHANGELOG.md
  src/components/molecules/AdminTableLegend.vue
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
Labels: auto update, auto_merged, ready to merge, size/S

#1674 SC-8666 - correcting the language json topic gender
  CHANGELOG.md
  locale/de.json
  locale/en.json
  src/utils/sidebarBaseItems.js
  tests/screenshot/__image_snapshots__/5-molecules-admintablelegend-default_1-snap.png
Labels: auto update, auto_merged, size/M, waiting for review

#1675 SC-8702 - disable the select all button
  CHANGELOG.md
  src/components/organisms/DataTable/BackendDataTable.unit.js
  src/components/organisms/DataTable/DataTable.unit.js
  src/components/organisms/DataTable/RowSelectionBar.vue
Labels: auto update, auto_merged, size/M

#1670 SC-7944 - fixes lern-store dates field
  CHANGELOG.md
  src/components/organisms/AddContentButton.vue
  src/components/organisms/LernstoreCollectionDetailView.vue
  src/components/organisms/LernstoreDetailView.vue
  src/plugins/datetime.js
Labels: ready to merge, size/M
