Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2021-03, with the labels that each got.

#1680 SC-8720 - add ellipsis to NAT rows
  CHANGELOG.md
  src/components/organisms/DataTable/TableDataRow.vue
  tests/screenshot/__image_snapshots__/5-molecules-admintablelegend-default_1-snap.png
Labels: size/XS

#1681 SC-8719 - fix pagination
  CHANGELOG.md
  src/components/organisms/Pagination.vue
Labels: auto update, ready to merge, size/XS

#1696 Release/26.0.2
  CHANGELOG.md
  locale/de.json
  locale/es.json
  package-lock.json
  package.json
  src/components/organisms/DataTable/RowSelectionBar.vue
  src/plugins/i18n.js
  src/serverMiddleware/routes.js
Labels: size/XL, waiting for review

#1698 Hotfix/3/SC-8822
  CHANGELOG.md
  locale/de.json
  locale/en.json
  locale/es.json
  package-lock.json
  package.json
  src/components/templates/impressum.vue
  src/themes/brb/components/templates/impressum.vue
  src/themes/open/templates/impressum.vue
  src/themes/thr/components/templates/impressum.vue
Labels: size/S

#1699 SC-8822 - add availability to phone number in imprint
  CHANGELOG.md
  locale/de.json
  locale/en.json
  locale/es.json
  package-lock.json
  package.json
Labels: size/S

#1706 SC-8791 - fix spelling mistake in NAT
  locale/de.json
Labels: ready to merge, size/XS

#1678 SC-8554 - fix qr code double role issue
  CHANGELOG.md
  src/pages/administration/teachers/index.vue
Labels: size/XS

#1708 SC-8708 - remove last and first name filter
  CHANGELOG.md
  src/utils/adminFilter.js
Labels: size/M, waiting for review

#1705 SC-8518 - layout issues with checkboxes and labels in filters and registration
  CHANGELOG.md
  src/components/base/BaseInput/BaseInputCheckbox.vue
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-checkbox-array_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-inputs-checkbox-boolean_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datafilter-inputs-checkbox_1-snap.png
Labels: size/XS, waiting for review

#1707 SC-8519 - Admin Table Bugfix - Set current date for filter, if there is no input
  CHANGELOG.md
  locale/de.json
  locale/en.json
  locale/es.json
  src/components/base/BaseInput/BaseInputDefault.vue
  src/components/molecules/ContextMenu.vue
  src/utils/adminFilter.js
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
Labels: ready to merge, size/M
