Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2021-06, with the labels that each got.

#1796 Add fetchAll util for get paginated resources from api
  .vscode/launch.json
  src/store/homeworks.js
  src/utils/fetchAll.js
  src/utils/fetchAll.unit.js
  src/utils/index.js
Labels: size/L, waiting for review

#1795 replace naming of project
  CHANGELOG.md
  README.md
  deploy/compose-client_brb.dummy
  deploy/compose-client_default.dummy
  deploy/compose-client_int.dummy
  deploy/compose-client_n21.dummy
  deploy/compose-client_open.dummy
  docs/0-GettingStarted/4-Workflow.md
  docs/3-BeginnerGuide/0-Einfuehrung.md
  docs/3-BeginnerGuide/1-Was-kannst-Du-fuer-die-Schul-Cloud-tun.md
  docs/storybook/README.md
  docs/storybook/typography.md
  http-headers.config.js
  package-lock.json
  package.json
  src/components/base/BaseBlockquote.unit.js
  src/components/base/BaseBreadcrumb.unit.js
  src/components/base/BaseLink.unit.js
  src/components/legacy/LegacyFooter.stories.js
  src/components/legacy/TheTopBar.unit.js
  src/components/molecules/AdminTableLegend.vue
  src/components/molecules/FabIcon.stories.js
  src/components/molecules/InstanceTile.stories.js
  src/components/molecules/MintEcLinkContainer.unit.js
  src/components/molecules/MintEcPageHeader.unit.js
  src/components/templates/CommonTermsOfUse.vue
  src/components/templates/impressum.vue
  src/pages/administration/ldap/config.unit.js
  src/pages/administration/ldap/config.vue
  src/store/ldap-config.unit.js
  src/themes/brb/components/templates/impressum.vue
  src/themes/open/templates/impressum.vue
  src/themes/thr/components/templates/impressum.vue
  stories/base.stories.js
  stories/mockData/Collection.js
  tests/screenshot/__image_snapshots__/4-base-ui-components-base-ui-base-link_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-base-ui-base-qrcode_1-snap.png
Labels: changes requested, size/L, waiting for review

#1794 Odyssey - add remaining time label to homeworksList
  locale/de.json
  locale/en.json
  locale/es.json
  src/assets/icons/hourglass-bottom-black.vue
  src/assets/icons/hourglass-disabled.vue
  src/components/organisms/DataTable/DataTable.data-factory.js
  src/components/organisms/HomeworksList.stories.js
  src/components/organisms/HomeworksList.unit.js
  src/components/organisms/HomeworksList.vue
  src/pages/tasks/open.unit.js
  src/pages/tasks/open.vue
  src/plugins/datetime.js
  src/store/homeworks.js
  src/themes/base/vuetify.options.js
  stories/mockData/Homeworks.js
  tests/plugins/datetime.unit.js
  tests/screenshot/__image_snapshots__/0-vuetify-homeworks-homeworkslist-homeworkslistloading_1-snap.png
Labels: size/XL, waiting for review

#1802 Decomposed dueDate hint chip
  locale/de.json
  locale/en.json
  locale/es.json
  src/components/molecules/VCustomChipTimeRemaining.vue
  src/components/molecules/vCustomChipTimeRemaining.stories.js
  src/components/molecules/vCustomChipTimeRemaining.unit.js
  src/components/organisms/HomeworksList.vue
  tests/screenshot/__image_snapshots__/0-vuetify-molecules-vcustomchiptimeremaining_1-snap.png
  tests/unit/__snapshots__/components/molecules/vCustomChipTimeRemaining.unit.js.snap
Labels: auto_merged, size/L, waiting for review

#1804 Wrote unit tests for the getters in homeworks.js and refactored mock data.
  src/store/homeworks.unit.js
  stories/mockData/Homeworks.js
Labels: size/L

#1803 Delete update_version.yml
  .github/workflows/update_version.yml
Labels: size/S, waiting for review

#1805 Feature/fix homeworks without due date
  src/components/organisms/HomeworksList.unit.js
  src/components/organisms/HomeworksList.vue
  src/pages/tasks/open.unit.js
  src/pages/tasks/open.vue
  src/store/homeworks.js
  src/store/homeworks.unit.js
  stories/mockData/Homeworks.js
Labels: size/L

#1793 SC-9090 - loading state and template refactoring
  CHANGELOG.md
  src/components/organisms/FormNews.vue
  src/pages/administration/ldap/activate.vue
  src/pages/administration/ldap/config.vue
  src/pages/content/_id/index.vue
  src/pages/content/index.vue
  src/pages/news/new.vue
  src/store/content.js
  src/store/ldap-config.js
  src/store/ldap-config.unit.js
  src/utils/adminFilter.js
  src/utils/service-template.js
Labels: size/L, waiting for review

#1808 SC-9144 - fixed build with env SC_THEME
  CHANGELOG.md
  deploy/Dockerfile.client
  deploy/build.sh
  package-lock.json
  package.json
Labels: ready to merge, size/S

#1798 Feature/sc 9093 default i18n config from server
  CHANGELOG.md
  src/plugins/datetime.js
  src/plugins/i18n.js
  src/plugins/i18n.unit.js
  src/store/auth.js
  src/store/auth.unit.js
  src/store/env-config.js
  src/store/env-config.unit.js
  src/store/filePaths.js
  src/store/filePaths.unit.js
  stories/.storybook/preview.js
Labels: size/L

#1799 SC-9106 remove endpoints determined by component
  CHANGELOG.md
  src/components/organisms/FormCreateUser.unit.js
  src/pages/administration/students/consent.vue
  src/pages/administration/students/index.unit.js
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.unit.js
  src/pages/administration/teachers/index.vue
  src/store/users.js
  src/store/users.unit.js
  src/utils/service-template.js
Labels: size/L

#1801 SC-9131 - fix consent bug
  CHANGELOG.md
  src/pages/administration/students/consent.unit.js
  src/pages/administration/students/consent.vue
  src/store/bulkConsent.js
  src/store/bulkConsent.unit.js
  src/store/users.js
  src/store/users.unit.js
Labels: size/XL, waiting for review

#1811 SC-9122 - getters logic
  CHANGELOG.md
  src/components/helpers/UserHasPermission.unit.js
  src/components/helpers/UserHasRole.unit.js
  src/components/helpers/UserHasRole.vue
  src/components/legacy/UserRole.unit.js
  src/components/legacy/UserRole.vue
  src/components/molecules/AddContentModal.unit.js
  src/components/molecules/AddContentModal.vue
  src/layouts/legacyLoggedIn.vue
  src/middleware/externally-managed-check.js
  src/mixins/UserHasPermission.js
  src/pages/administration/students/index.unit.js
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.unit.js
  src/pages/administration/teachers/index.vue
  src/store/auth.js
  src/store/courses.js
  tests/middleware/externally-managed-check.unit.js
Labels: size/L, waiting for review

#1813 SC-9160 - fix getStatus getter
  CHANGELOG.md
  src/utils/service-template.js
Labels: size/XS

#1816 Feature/SC-9131 - fixing password changing on student consent page
  CHANGELOG.md
  src/pages/administration/students/consent.unit.js
  src/pages/administration/students/consent.vue
  src/store/bulkConsent.js
  src/store/users.unit.js
Labels: size/L

#1817 OPS-2467 - changes build pipeline to github actions
  .github/workflows/build_push_service.yml
  .github/workflows/main.yml
  .github/workflows/tag.yml
  .travis.yml
  CHANGELOG.md
  Dockerfile.client
  Dockerfile.storybook
  Dockerfile.vuepress
  ansible/group_vars/all/nuxt-client.yml
  ansible/group_vars/brb/nuxt-client.yml
  ansible/group_vars/nbc/nuxt-client.yml
  ansible/roles/nuxt-client/tasks/main.yml
  ansible/roles/nuxt-client/templates/configmap-files.yml.j2
  ansible/roles/nuxt-client/templates/configmap.yml.j2
  ansible/roles/nuxt-client/templates/deployment.yml.j2
  ansible/roles/nuxt-client/templates/svc.yml.j2
  deploy/build.sh
  deploy/buildAndDeployFilter.sh
  deploy/compose-client_brb.dummy
  deploy/compose-client_default.dummy
  deploy/compose-client_int.dummy
  deploy/compose-client_n21.dummy
  deploy/compose-client_open.dummy
  deploy/compose-client_thr.dummy
  deploy/compose-storybook.dummy
  deploy/compose-vuepress.dummy
  deploy/decryptSecrets.sh
  deploy/pull-deploy.sh
  deploy/travis_rsa.enc
  package-lock.json
  package.json
Labels: waiting for review

#1818 Feature/sc 8448 fix merlin url
  CHANGELOG.md
  src/components/organisms/AddContentButton.vue
Labels: size/M
