Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2021-11, with the labels that each got.

#1938 BC-392 - Skip to main content link (accessibility feature)
  CHANGELOG.md
  locale/de.json
  locale/en.json
  locale/es.json
  src/components/molecules/SkipLinks.unit.js
  src/components/molecules/SkipLinks.vue
  src/components/organisms/FormNews.unit.js
  src/layouts/defaultVuetify.vue
  src/layouts/legacyLoggedIn.vue
Labels: size/M, waiting for review, run tests

#1949 BC-273 - Adding data test id's for nuxt task overview
  CHANGELOG.md
  src/components/atoms/vCustomAutocomplete.vue
  src/components/molecules/vCustomDoublePanels.vue
  src/components/molecules/vCustomEmptyState.vue
  src/components/molecules/vTaskItemStudent.vue
  src/components/molecules/vTaskItemTeacher.vue
  src/components/templates/TasksDashboardMain.vue
  tests/unit/__snapshots__/components/molecules/vTaskItemTeacher.unit.js.snap
Labels: size/M, waiting for review

#1952 BC-402 - change e2e test include to reusable workflows
  .github/workflows/push.yml
  CHANGELOG.md
Labels: waiting for review, run unstable tests

#1953 26.15.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: waiting for review, changes requested

#1954 Feature/BC-577 - Refactoring rooms-overview
  CHANGELOG.md
  src/components/atoms/vRoomAvatar.unit.ts
  src/components/atoms/vRoomAvatar.vue
  src/components/atoms/vRoomEmptyAvatar.unit.ts
  src/components/atoms/vRoomEmptyAvatar.vue
  src/components/molecules/RoomModal.unit.ts
  src/components/molecules/RoomModal.vue
  src/components/molecules/vRoomGroupAvatar.unit.ts
  src/components/molecules/vRoomGroupAvatar.vue
  src/components/organisms/vCustomDialog.vue
  src/pages/rooms-overview.unit.js
  src/pages/rooms-overview.vue
  src/store/rooms.ts
  tests/test-utils/componentMocks.ts
  tests/unit/setup.js
Labels: waiting for review

#1956 version 26.16.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: waiting for review, run tests

#1947 Feature/bc 155 substitution teacher filter2
  CHANGELOG.md
  locale/de.json
  locale/en.json
  locale/es.json
  src/components/molecules/vTaskItemStudent.stories.js
  src/components/molecules/vTaskItemStudent.unit.js
  src/components/molecules/vTaskItemTeacher.stories.js
  src/components/molecules/vTaskItemTeacher.unit.js
  src/components/molecules/vTaskItemTeacher.vue
  src/components/organisms/TasksList.stories.js
  src/components/organisms/TasksList.unit.js
  src/components/templates/TasksDashboardMain.stories.js
  src/components/templates/TasksDashboardMain.unit.js
  src/components/templates/TasksDashboardMain.vue
  src/components/templates/TasksDashboardStudent.unit.js
  src/components/templates/TasksDashboardStudent.vue
  src/components/templates/TasksDashboardTeacher.unit.js
  src/components/templates/TasksDashboardTeacher.vue
  src/pages/tasks/assigned.unit.js
  src/store/tasks.js
  src/store/tasks.unit.js
  stories/mockData/Tasks.js
  tests/screenshot/__image_snapshots__/0-vuetify-templates-tasksdashboard-tasks-dashboard-teacher_1-snap.png
  tests/unit/__snapshots__/components/molecules/vTaskItemTeacher.unit.js.snap
Labels: size/L, waiting for review, run-e2e-tests, run tests

#1957 BC-589 - BC-653 - Change auto deployment to a reusable workflow
  .github/workflows/clean.yml
  .github/workflows/push.yml
  CHANGELOG.md
Labels: waiting for review

#1959 BC-589 - fix branch ref for delete event
  .github/workflows/clean.yml
  CHANGELOG.md
Labels: waiting for review

#1961 version 26.17.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: waiting for review

#1962 BC-633 - store types refactoring
  CHANGELOG.md
  src/.nuxtignore
  src/store/accounts.ts
  src/store/auth.ts
  src/store/content.ts
  src/store/content.unit.ts
  src/store/env-config.ts
  src/store/env-config.unit.ts
  src/store/filePaths.ts
  src/store/news.ts
  src/store/rooms.ts
  src/store/rooms.unit.ts
  src/store/schools.ts
  src/store/types/auth.ts
  src/store/types/commons.ts
  src/store/types/content.ts
  src/store/types/env-config.ts
  src/store/types/filePaths.ts
  src/store/types/news.ts
  src/store/types/rooms.ts
  src/store/types/schools.ts
  tests/test-utils/mockObjects.ts
Labels: waiting for review, run tests, run unstable tests

#1955 Feature/bc 537 add task fab
  CHANGELOG.md
  locale/de.json
  locale/en.json
  locale/es.json
  src/components/atoms/vCustomFab.stories.js
  src/components/atoms/vCustomFab.unit.ts
  src/components/atoms/vCustomFab.vue
  src/components/legacy/PopupIconInitials.vue
  src/components/molecules/vTaskItemStudent.vue
  src/components/molecules/vTaskItemTeacher.vue
  src/components/organisms/TasksList.vue
  src/components/templates/TasksDashboardMain.vue
  src/pages/administration/ldap/activate.vue
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
  src/themes/base/styles/variables/_layers.scss
  src/themes/base/styles/vuetify-custom.scss
  stories/mockData/LoremIpsumParagraphs.js
  tests/screenshot/__image_snapshots__/0-vuetify-atoms-vcustomfab-multiple-actions_1-snap.png
  tests/screenshot/__image_snapshots__/0-vuetify-atoms-vcustomfab-simple-action_1-snap.png
  tests/screenshot/__image_snapshots__/0-vuetify-templates-tasksdashboard-tasks-dashboard-teacher_1-snap.png
Labels: waiting for review, run tests

#1966 BC-724 - Listing elements and search
  CHANGELOG.md
  locale/de.json
  locale/en.json
  locale/es.json
  src/components/atoms/vRoomAvatar.unit.ts
  src/components/atoms/vRoomAvatar.vue
  src/components/atoms/vRoomEmptyAvatar.unit.ts
  src/components/atoms/vRoomEmptyAvatar.vue
  src/components/molecules/RoomModal.unit.ts
  src/components/molecules/RoomModal.vue
  src/components/molecules/vRoomGroupAvatar.unit.ts
  src/components/molecules/vRoomGroupAvatar.vue
  src/components/organisms/RoomAvatarIterator.unit.ts
  src/components/organisms/RoomAvatarIterator.vue
  src/pages/rooms-list.unit.ts
  src/pages/rooms-list.vue
  src/pages/rooms-overview.unit.js
  src/pages/rooms-overview.vue
  src/plugins/global.d.ts
  src/plugins/user.d.ts
  src/serverApi/v3/api.ts
  src/serverMiddleware/routes.js
  src/store/rooms.ts
  src/store/rooms.unit.ts
  src/store/types/rooms.ts
Labels: waiting for review

#1967 version 26.18.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: waiting for review

#1970 BC-740 change ansible vars for docker image and tag
  CHANGELOG.md
  ansible/group_vars/all/nuxt-client.yml
  ansible/roles/nuxt-client/templates/deployment.yml.j2
Labels: waiting for review

#1969 BC-839: Removing search filter while dragging
  CHANGELOG.md
  src/pages/rooms-overview.unit.js
  src/pages/rooms-overview.vue
Labels: waiting for review

#1971 BC-828: changed fetchAllElements action to generated api client
  CHANGELOG.md
  src/store/rooms.ts
  src/store/rooms.unit.ts
Labels: waiting for review, changes requested

#1974 BC-832 - remove github images from CORS
  CHANGELOG.md
  ansible/roles/nuxt-client/templates/configmap-files.yml.j2
  http-headers.config.js
Labels: waiting for review

#1958 BC-157 - Add typescript to task store
  CHANGELOG.md
  src/.nuxtignore
  src/components/organisms/TasksList.unit.js
  src/components/organisms/TasksList.vue
  src/components/templates/TasksDashboardMain.stories.js
  src/components/templates/TasksDashboardMain.unit.js
  src/components/templates/TasksDashboardMain.vue
  src/components/templates/TasksDashboardStudent.unit.js
  src/components/templates/TasksDashboardStudent.vue
  src/components/templates/TasksDashboardTeacher.unit.js
  src/components/templates/TasksDashboardTeacher.vue
  src/pages/tasks/assigned.unit.js
  src/serverApi/v3/api.ts
  src/store/news.ts
  src/store/task.filter.ts
  src/store/task.filter.unit.ts
  src/store/tasks.js
  src/store/tasks.ts
  src/store/tasks.unit.js
  src/store/tasks.unit.ts
  src/store/types/commons.ts
  src/store/types/news.ts
  src/store/types/tasks.ts
  tests/unit/setup.js
Labels: run tests

#1968 BC-661 Add school logo to top bar. Refactor legacyLoggedIn
  CHANGELOG.md
  src/components/legacy/TheTopBar.unit.js
  src/components/legacy/TheTopBar.vue
  src/components/organisms/administration/GeneralSettings.unit.js
  src/components/organisms/administration/GeneralSettings.vue
  src/layouts/legacyLoggedIn.vue
  src/pages/administration/school-settings.unit.js
  src/pages/administration/school-settings.vue
Labels: waiting for review

#1976 version 26.19.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: waiting for review

#1975 BC-878 fix accidentialy deleting school logo
  CHANGELOG.md
  src/components/organisms/administration/GeneralSettings.vue
Labels: waiting for review
