Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2021-09, with the labels that each got.

#1884 feature/BC-190 - removing dataStorage
  CHANGELOG.md
  src/components/organisms/administration/GeneralSettings.unit.js
  src/components/organisms/administration/GeneralSettings.vue
  src/pages/administration/school-settings.vue
  src/store/schools.js
  src/store/schools.unit.js
Labels: size/L, run tests

#1882 BC-38 - BC-126 - Add ansible files for Bosscloud (default)
  CHANGELOG.md
  ansible/group_vars/default/nuxt-client.yml
Labels: size/XS, waiting for review, run-e2e-tests, run tests

#1885 BC-201 - hasRole action and roles module cleanup
  CHANGELOG.md
  src/store/auth.js
  src/store/roles.js
Labels: size/M, waiting for review, run tests

#1883 BC-136 - add no-focused-tests eslint rule
  .eslintrc.js
  CHANGELOG.md
Labels: size/XS, run tests

#1878 BC-132 - autologout, content, and env-config modules tests
  CHANGELOG.md
  src/store/accounts.unit.ts
  src/store/autoLogout.ts
  src/store/autoLogout.unit.ts
  src/store/content.ts
  src/store/content.unit.ts
  src/store/env-config.ts
  src/store/env-config.unit.js
  src/store/env-config.unit.ts
  src/store/filePaths.unit.ts
Labels: size/XXL, waiting for review, run tests

#1887 Change logic for non-editable systems
  CHANGELOG.md
  src/components/organisms/administration/AuthSystems.unit.js
  src/components/organisms/administration/AuthSystems.vue
Labels: size/M, waiting for review, run tests

#1891 BC 195 - fix multiple select courses for students
  src/components/atoms/vCustomAutocomplete.vue
  src/components/molecules/vCustomDoublePanels.vue
  src/components/molecules/vHomeworkItemTeacher.vue
  src/components/organisms/HomeworksDashboardMain.unit.js
  src/components/organisms/HomeworksDashboardMain.vue
  src/components/organisms/HomeworksDashboardStudent.vue
  src/components/organisms/HomeworksDashboardTeacher.vue
  src/components/organisms/HomeworksList.vue
  src/store/homeworks.js
  src/store/homeworks.unit.js
  stories/mockData/Homeworks.js
Labels: WIP, size/L

#1893 BC-81 - remove old lern-store mode
  CHANGELOG.md
  docs/0-GettingStarted/1-Build.md
  nuxt.config.js
  src/components/organisms/administration/PrivacySettings.unit.js
  src/store/env-config.ts
  src/store/env-config.unit.ts
Labels: size/S, run tests

#1888 BC-98 - added unit tests for admin school page
  CHANGELOG.md
  src/pages/administration/school-settings.unit.js
  src/pages/administration/school-settings.vue
Labels: size/L, run tests

#1896 BC-234 changed nbc imprint
  CHANGELOG.md
  src/themes/n21/components/templates/impressum.vue
Labels: size/M, waiting for review, run-e2e-tests, run tests

#1895 Hotfix/fix nuxt routing
  CHANGELOG.md
  Dockerfile.client
  nuxt.config.js
  package-lock.json
  package.json
  startup.sh
Labels: size/S, waiting for review, run tests

#1890 BC 179 - refactor tasks
  CHANGELOG.md
  locale/de.json
  locale/en.json
  locale/es.json
  src/components/atoms/vCustomAutocomplete.vue
  src/components/molecules/vCustomDoublePanels.vue
  src/components/molecules/vHomeworkItemTeacher.vue
  src/components/organisms/HomeworksDashboardMain.stories.js
  src/components/organisms/HomeworksDashboardMain.unit.js
  src/components/organisms/HomeworksDashboardMain.vue
  src/components/organisms/HomeworksDashboardStudent.unit.js
  src/components/organisms/HomeworksDashboardStudent.vue
  src/components/organisms/HomeworksDashboardTeacher.unit.js
  src/components/organisms/HomeworksDashboardTeacher.vue
  src/components/organisms/HomeworksList.unit.js
  src/components/organisms/HomeworksList.vue
  src/pages/tasks/assigned.unit.js
  src/store/homeworks.js
  src/store/homeworks.unit.js
  stories/mockData/Homeworks.js
  tests/screenshot/__image_snapshots__/0-vuetify-templates-homeworksdashboard-homeworks-dashboard-teacher_1-snap.png
Labels: size/XXL, run tests

#1900 Feature/BC-252 - creating avatar component
  CHANGELOG.md
  src/components/atoms/vRoomAvatar.unit.ts
  src/components/atoms/vRoomAvatar.vue
  src/components/atoms/vRoomEmptyAvatar.unit.ts
  src/components/atoms/vRoomEmptyAvatar.vue
  src/components/molecules/vRoomGroupAvatar.unit.ts
  src/components/molecules/vRoomGroupAvatar.vue
  src/components/organisms/administration/AuthSystems.vue
  src/components/organisms/vCustomDialog.unit.js
  src/components/organisms/vCustomDialog.vue
  src/pages/rooms-overview/index.unit.js
  src/pages/rooms-overview/index.vue
  src/serverMiddleware/routes.js
  src/store/rooms.ts
  src/store/rooms.unit.ts
Labels: size/XXL, run tests

#1897 Feature/bc 167 layouts
  CHANGELOG.md
  locale/de.json
  locale/en.json
  locale/es.json
  src/.nuxtignore
  src/components/atoms/vCustomBreadcrumbs.vue
  src/components/templates/DefaultWireframe.unit.js
  src/components/templates/DefaultWireframe.vue
  src/layouts/legacyLoggedIn.vue
  src/layouts/loggedInFullNoPadding.vue
  src/layouts/loggedoutFullLayout.vue
  src/layouts/loggedoutFullWidth.vue
  src/pages/administration/school-settings.unit.js
  src/pages/administration/school-settings.vue
  src/pages/administration/students/index.unit.js
  src/pages/administration/students/index.vue
  src/pages/administration/students/new.vue
  src/pages/administration/teachers/index.unit.js
  src/pages/administration/teachers/index.vue
  src/pages/administration/teachers/new.vue
  src/themes/base/styles/variables/_spacing.scss
  src/utils/sidebarBaseItems.js
  tests/unit/setup.js
  tsconfig.template.js
Labels: size/XL, run tests

#1902 BC-266 load baseUrl from api call
  CHANGELOG.md
  Dockerfile.client
  http-headers.config.js
  run.sh
  src/plugins/axios.js
  src/static/runtime.config.json
  src/store/auth.ts
  startup.sh
Labels: size/M, waiting for review, run-e2e-tests, run tests

#1908 BC-311 - renamed homeworks to tasks to fit server naming
  CHANGELOG.md
  locale/de.json
  locale/en.json
  locale/es.json
  src/components/molecules/vHomeworkItemStudent.stories.js
  src/components/molecules/vHomeworkItemTeacher.stories.js
  src/components/molecules/vHomeworkItemTeacher.unit.js
  src/components/molecules/vTaskItemStudent.stories.js
  src/components/molecules/vTaskItemStudent.unit.js
  src/components/molecules/vTaskItemStudent.vue
  src/components/molecules/vTaskItemTeacher.stories.js
  src/components/molecules/vTaskItemTeacher.unit.js
  src/components/molecules/vTaskItemTeacher.vue
  src/components/organisms/HomeworksDashboardMain.stories.js
  src/components/organisms/HomeworksDashboardStudent.unit.js
  src/components/organisms/HomeworksDashboardStudent.vue
  src/components/organisms/HomeworksDashboardTeacher.unit.js
  src/components/organisms/HomeworksDashboardTeacher.vue
  src/components/organisms/HomeworksList.stories.js
  src/components/organisms/HomeworksList.vue
  src/components/organisms/TasksDashboardMain.stories.js
  src/components/organisms/TasksDashboardMain.unit.js
  src/components/organisms/TasksDashboardMain.vue
  src/components/organisms/TasksDashboardStudent.unit.js
  src/components/organisms/TasksDashboardStudent.vue
  src/components/organisms/TasksDashboardTeacher.unit.js
  src/components/organisms/TasksDashboardTeacher.vue
  src/components/organisms/TasksList.stories.js
  src/components/organisms/TasksList.unit.js
  src/components/organisms/TasksList.vue
  src/pages/tasks/assigned.unit.js
  src/pages/tasks/assigned.vue
  src/pages/tasks/open.unit.js
  src/pages/tasks/open.vue
  src/store/homeworks.js
  src/store/tasks.js
  src/store/tasks.unit.js
  stories/mockData/Tasks.js
  tests/screenshot/__image_snapshots__/0-vuetify-molecules-vtaskitemstudent_1-snap.png
  tests/screenshot/__image_snapshots__/0-vuetify-molecules-vtaskitemteacher_1-snap.png
  tests/screenshot/__image_snapshots__/0-vuetify-organisms-taskslist-taskslist-student_1-snap.png
  tests/screenshot/__image_snapshots__/0-vuetify-organisms-taskslist-taskslist-teacher_1-snap.png
  tests/screenshot/__image_snapshots__/0-vuetify-organisms-taskslist-taskslistloading_1-snap.png
  tests/screenshot/__image_snapshots__/0-vuetify-templates-tasksdashboard-tasks-dashboard-student_1-snap.png
  tests/screenshot/__image_snapshots__/0-vuetify-templates-tasksdashboard-tasks-dashboard-teacher_1-snap.png
  tests/unit/__snapshots__/components/molecules/vTaskItemTeacher.unit.js.snap
Labels: size/XXL, waiting for review, run tests

#1904 BC-68 - fix server manifest error
  .github/workflows/main.yml
  .github/workflows/push.yml
  .github/workflows/test_e2e_pull_request.yml
  .github/workflows/test_e2e_push_main.yml
  CHANGELOG.md
Labels: size/L, waiting for review

#1912 Feature/bc 313 fix active tab behaviour
  CHANGELOG.md
  src/components/organisms/TasksDashboardMain.vue
  src/components/organisms/TasksDashboardStudent.vue
  src/themes/brb/vuetify.options.js
  src/themes/default/vuetify.options.js
  src/themes/int/vuetify.options.js
  src/themes/n21/vuetify.options.js
  src/themes/open/vuetify.options.js
  src/themes/thr/vuetify.options.js
Labels: size/S, run tests

#1910 BC-321 - changed further hrefs to to
  CHANGELOG.md
  src/store/schools.ts
  src/store/schools.unit.ts
  src/utils/sidebarBaseItems.js
Labels: size/S, run tests

#1917 Release/26.11
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/S

#1914 BC-322 Fix race condition while loading the school in school settings…
  CHANGELOG.md
  src/components/organisms/administration/GeneralSettings.vue
  src/components/organisms/administration/SchoolPolicies.vue
  src/store/schools.ts
  src/store/schools.unit.ts
  tests/test-utils/mockObjects.ts
Labels: size/M

#1907 BC-309/310 - adjust task course filter
  CHANGELOG.md
  src/components/molecules/vCustomDoublePanels.unit.js
  src/components/molecules/vCustomDoublePanels.vue
  src/components/organisms/TasksDashboardMain.stories.js
  src/components/organisms/TasksDashboardMain.unit.js
  src/components/organisms/TasksDashboardMain.vue
Labels: size/L, waiting for review, run tests

#1922 BC-333 - update node sass
  CHANGELOG.md
  package-lock.json
  package.json
Labels: size/XS
