Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2021-04, with the labels that each got.

#1711 SC-8837 - fix timezone issues in datetime.js
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/organisms/FormNews.unit.js
  src/components/organisms/FormNews.vue
  src/plugins/datetime.js
  tests/plugins/datetime.unit.js
Labels: size/S

#1702 SC-8837 - activate ldap config pages again
  CHANGELOG.md
  package-lock.json
  package.json
  src/serverMiddleware/routes.js
Labels: size/S

#1710 SC-8881 - double role fix
  CHANGELOG.md
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
Labels: auto_merged, ready to merge, size/XS

#1693 Quickfix - splits jobs, improves template, adds more checks
  .github/mergeable.yml
  .github/pull_request_template.md
  .github/workflows/test.yml
  .github/workflows/test_e2e.yml
  .github/workflows/test_screenshot.yml
  CHANGELOG.md
Labels: size/L

#1709 SC-8878 - invalid date on filter chip
  CHANGELOG.md
  src/pages/administration/students/index.vue
  src/utils/adminFilter.js
  src/utils/adminFilter.unit.js
Labels: auto update, ready to merge, size/S

#1712 SC-8681 - consent column
  CHANGELOG.md
  nuxt.config.js
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
Labels: size/M

#1728 SC-8910 - add external check for delete action
  CHANGELOG.md
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
Labels: size/M

#1734 SC-8916 - adds page titles to some administration pages
  CHANGELOG.md
  src/pages/administration/datasources/index.vue
  src/pages/administration/datasources/new.vue
  src/pages/administration/ldap/activate.vue
  src/pages/administration/ldap/config.vue
  src/pages/administration/students/consent.vue
  src/pages/administration/students/index.vue
  src/pages/administration/students/new.vue
  src/pages/administration/teachers/index.vue
  src/pages/administration/teachers/new.vue
Labels: ready to merge, size/M

#1740 SC-8916 - fixes some titltes
  CHANGELOG.md
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
Labels: ready to merge, size/S

#1738 Quickfix - Git Workflow upgrade
  .github/workflows/test_e2e.yml
  .github/workflows/test_screenshot.yml
  stories/.storybook/manager-head.html
Labels: ready to merge, size/XS

#1741 SC-8884 - Admin Table Unit Tests
  src/components/molecules/AdminTableLegend.vue
  src/pages/administration/students/index.unit.js
  src/pages/administration/students/index.vue
  src/pages/administration/students/new.unit.js
  src/pages/administration/teachers/index.vue
  src/pages/administration/teachers/teacherIndex.unit.js
  src/store/users.js
  src/store/users.unit.js
Labels: ready to merge, size/XL

#1162 SC-5175 - Added alt text for profile picture
  locale/de.json
  locale/en.json
  locale/es.json
  src/components/atoms/ProfilePicture.unit.js
  src/components/atoms/ProfilePicture.vue
Labels: a11y, ready to merge, size/S

#1743 SC-8884 - NAT unit tests [follow-up]
  src/components/molecules/ContextMenu.vue
  src/components/organisms/DataTable/RowSelectionBar.vue
  src/pages/administration/students/index.unit.js
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
  src/pages/administration/teachers/teacherIndex.unit.js
Labels: ready to merge, size/L

#1749 SC-8681 - consent fix
  CHANGELOG.md
  src/pages/administration/students/index.vue
Labels: size/XS

#1751 Quickfix - Storybook: remove addon backgrounds which breaks storybook in this version
  package.json
  stories/.storybook/main.js
Labels: size/XS

#1752 SC-8681 - remove NAT legend
  CHANGELOG.md
  jest.config.js
  src/components/molecules/AdminTableLegend.vue
  src/pages/administration/students/index.unit.js
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
  src/pages/administration/teachers/teacherIndex.unit.js
  tests/screenshot/__image_snapshots__/5-molecules-admintablelegend-default_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
Labels: size/L

#1756 Hotfix 26.1.1
  CHANGELOG.md
  package-lock.json
  package.json
  tests/screenshot/__image_snapshots__/6-organisms-datatable-subcomponents-tabledatarow_1-snap.png
Labels: size/S

#1757 Quickfix - conflicting screenshots
  CHANGELOG.md
  tests/screenshot/__image_snapshots__/5-molecules-admintablelegend-default_1-snap.png
Labels: size/XS
