Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2021-08, with the labels that each got.

#1853 SC-9232 - gender specific role names
  CHANGELOG.md
  locale/de.json
  locale/en.json
  locale/es.json
  src/components/legacy/PopupIconInitials.vue
  src/components/legacy/UserRole.unit.js
  src/components/legacy/UserRole.vue
  src/layouts/legacyLoggedIn.vue
Labels: size/M, waiting for review

#1854 SC-9169 fix icon color in context menu
  CHANGELOG.md
  src/components/molecules/ContextMenu.vue
  tests/screenshot/__image_snapshots__/5-molecules-contextmenu-with-icons_1-snap.png
Labels: size/S

#1858 SC-9236 update THR imprint
  CHANGELOG.md
  package-lock.json
  package.json
  src/themes/brb/components/legacy/TheFooter.vue
  src/themes/thr/components/legacy/TheFooter.vue
  src/themes/thr/components/templates/impressum.vue
Labels: size/L

#1861 SC-9191 run e2e tests in pull requests with 'run tests' label
  .github/workflows/test_e2e.yml
  CHANGELOG.md
Labels: size/S, run tests

#1844 SC-9192 Fix path mapping
  CHANGELOG.md
  nuxt.config.js
  package-lock.json
  package.json
  src/components/organisms/AddContentButton.vue
  src/components/organisms/LernstoreDetailView.vue
  src/pages/TermsOfUse.vue
  src/store/accounts.js
  src/store/activation.js
  src/store/auth.js
  src/store/bulkConsent.js
  src/store/calendar.js
  src/store/content.js
  src/store/env-config.js
  src/store/env-config.unit.js
  src/store/insights.js
  src/store/ldap-config.js
  src/store/ldap-config.unit.js
  src/store/messenger.js
  src/store/messenger.unit.js
  src/store/news.ts
  src/store/news.unit.ts
  src/store/teams.js
  src/store/terms-and-conditions.js
  src/store/users.js
  src/store/users.unit.js
  src/store/webuntis-metadata.js
  src/utils/service-template.js
Labels: size/L, run tests

#1866 BC-64 - Fix e2e test branch selection bug
  .github/workflows/test_e2e.yml
Labels: size/XS, waiting for review, run tests

#1865 SC-9192 BC-69 add path versions in axios requests
  CHANGELOG.md
  package-lock.json
  package.json
  src/store/content.js
  src/store/ldap-config.js
  src/store/ldap-config.unit.js
Labels: size/S, run tests

#1869 Feature/SC-9083 admin schools tests
  src/store/schools.unit.js
Labels: size/L

#1868 BC-64 BC-67 execute e2e tests for push on main
  .github/workflows/test_e2e_pull_request.yml
  .github/workflows/test_e2e_push_main.yml
  CHANGELOG.md
Labels: size/M, waiting for review, run-e2e-tests, run tests

#1870 BC-14-changed thr contact address
  CHANGELOG.md
  src/themes/thr/components/legacy/TheFooter.vue
Labels: size/XS, run tests

#1871 BC-37 - BC-56 - reduce resource consumption for deployed nuxtclient
  CHANGELOG.md
  ansible/roles/nuxt-client/templates/deployment.yml.j2
Labels: size/S, waiting for review, run tests

#1873 bc-36 improved nuxt container image
  .dockerignore
  Dockerfile.client
  docs/0-GettingStarted/1-Build.md
  startup.sh
Labels: size/M

#1862 SC-9280 fix primary and secondary colors according to old client
  CHANGELOG.md
  src/components/legacy/PopupIconInitials.vue
  src/components/legacy/TheSidebar.vue
  src/themes/base/styles/variables/_colors.scss
  src/themes/brb/styles/custom-styles.scss
  src/themes/brb/styles/index.scss
  src/themes/default/styles/variables/_colors.scss
  src/themes/default/vuetify.options.js
  src/themes/demo/styles/variables/_colors.scss
  src/themes/int/styles/variables/_colors.scss
  src/themes/n21/styles/variables/_colors.scss
  src/themes/n21/vuetify.options.js
  src/themes/open/styles/variables/_colors.scss
  src/themes/open/vuetify.options.js
  src/themes/thr/styles/variables/_colors.scss
  src/themes/thr/vuetify.options.js
  tests/screenshot/__image_snapshots__/0-vuetify-vuetify-default-button_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-base-ui-base-image_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-base-ui-base-progressbar_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-base-ui-basebutton_1-snap.png
  tests/screenshot/__image_snapshots__/4-base-ui-components-basechip-default_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-content-states-contentemptystate_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-fabfloating-default_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-fabicon-multiple-actions_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-fabicon-single-action_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-minteclinkcontainer-default_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-onboarding-landing-cta_1-snap.png
  tests/screenshot/__image_snapshots__/5-molecules-responsivebutton-default_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-formcreateuser_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-formdatasourcelogin_1-snap.png
  tests/screenshot/__image_snapshots__/7-others-misc-dropdownmenumintec_1-snap.png
Labels: size/M, run-e2e-tests, run tests

#1852 BC-18 - store refactor to typescript
  CHANGELOG.md
  nuxt.config.js
  package-lock.json
  package.json
  src/components/molecules/AddContentModal.unit.js
  src/components/molecules/AddContentModal.vue
  src/components/organisms/AddContentButton.vue
  src/components/organisms/AutoLogoutWarning.unit.js
  src/components/organisms/AutoLogoutWarning.vue
  src/components/organisms/ContentCard.vue
  src/components/organisms/LernstoreCollectionDetailView.vue
  src/middleware/links-fallback.js
  src/pages/administration/students/consent.vue
  src/pages/administration/students/index.unit.js
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.unit.js
  src/pages/administration/teachers/index.vue
  src/pages/content/_id/index.vue
  src/pages/content/index.vue
  src/plugins/authenticate.js
  src/plugins/configInit.js
  src/plugins/datetime.js
  src/plugins/i18n.js
  src/plugins/i18n.unit.js
  src/store/accounts.js
  src/store/accounts.ts
  src/store/auth.js
  src/store/auth.unit.js
  src/store/autoLogout.js
  src/store/autoLogout.ts
  src/store/content.js
  src/store/content.ts
  src/store/env-config.js
  src/store/env-config.ts
  src/store/env-config.unit.js
  src/store/filePaths.js
  src/store/filePaths.ts
  src/store/filePaths.unit.js
  src/store/index.ts
  src/store/news.ts
  src/themes/brb/components/legacy/TheFooter.vue
  src/themes/n21/components/legacy/TheFooter.vue
  src/themes/n21/components/templates/CommonTermsOfUse.vue
  src/themes/open/components/legacy/TheFooter.vue
  src/themes/thr/components/legacy/TheFooter.vue
  tests/middleware/links-fallback.unit.js
  tsconfig.template.js
Labels: size/XXL, run tests

#1874 Feature/bc 5 rename open task
  CHANGELOG.md
  locale/de.json
  locale/en.json
  locale/es.json
  src/utils/sidebarBaseItems.js
Labels: size/XS

#1875 Feature/bc 5 filter
  src/components/molecules/vHomeworkItemTeacher.unit.js
  src/components/organisms/HomeworksDashboardMain.unit.js
  src/components/organisms/HomeworksDashboardMain.vue
  src/components/organisms/HomeworksDashboardStudent.unit.js
  src/components/organisms/HomeworksDashboardStudent.vue
  src/store/homeworks.js
  stories/mockData/Homeworks.js
Labels: WIP, size/L

#1876 BC-133 - filePaths and accounts module tests
  CHANGELOG.md
  src/store/accounts.unit.ts
  src/store/filePaths.unit.js
  src/store/filePaths.unit.ts
Labels: size/L, run tests

#1877 Feature/bc 5 task states
  locale/de.json
  locale/en.json
  locale/es.json
  src/assets/icons/hourglass-disabled.vue
  src/assets/icons/task-done-filled.vue
  src/assets/icons/task-done.vue
  src/assets/icons/task-missed-filled.vue
  src/assets/icons/task-missed.vue
  src/assets/icons/task-open-filled.vue
  src/assets/img/courses/task-done.svg
  src/assets/img/courses/task-open.svg
  src/components/atoms/VCustomChipTimeRemaining.vue
  src/components/atoms/vCustomChipTimeRemaining.stories.js
  src/components/atoms/vCustomChipTimeRemaining.unit.js
  src/components/molecules/vCustomEmptyState.stories.js
  src/components/molecules/vHomeworkItemStudent.stories.js
  src/components/molecules/vHomeworkItemStudent.unit.js
  src/components/molecules/vHomeworkItemStudent.vue
  src/components/molecules/vHomeworkItemTeacher.vue
  src/components/organisms/HomeworksDashboardMain.stories.js
  src/components/organisms/HomeworksDashboardMain.unit.js
  src/components/organisms/HomeworksDashboardMain.vue
  src/components/organisms/HomeworksDashboardStudent.unit.js
  src/components/organisms/HomeworksDashboardStudent.vue
  src/components/organisms/HomeworksList.stories.js
  src/components/organisms/HomeworksList.unit.js
  src/pages/tasks/assigned.unit.js
  src/store/homeworks.js
  src/store/homeworks.unit.js
  src/themes/base/vuetify.options.js
  stories/mockData/Homeworks.js
  stories/vuetify.stories.js
  tests/unit/__snapshots__/components/atoms/vCustomChipTimeRemaining.unit.js.snap
  tests/unit/__snapshots__/components/molecules/vCustomChipTimeRemaining.unit.js.snap
Labels: size/XL, run-e2e-tests, run tests
