Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2021-07, with the labels that each got.

#1823 Feature/sc 9159 news typescript frontend
  CHANGELOG.md
  package-lock.json
  src/components/organisms/FormNews.unit.js
  src/components/organisms/FormNews.vue
  src/pages/news/index.vue
  src/serverMiddleware/routes.js
  src/store/news.js
  tests/screenshot/__image_snapshots__/6-organisms-news-details_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-news-edit_1-snap.png
  tests/screenshot/__image_snapshots__/6-organisms-news-new_1-snap.png
Labels: size/M

#1824 Feature/sc 9143 teacher task dashboard
  CHANGELOG.md
  locale/de.json
  locale/en.json
  locale/es.json
  package-lock.json
  package.json
  src/components/legacy/PopupIcon.vue
  src/components/legacy/PopupIconInitials.vue
  src/components/legacy/TheSidebar.vue
  src/components/molecules/ContextMenu.vue
  src/components/molecules/vHomeworkItemStudent.unit.js
  src/components/molecules/vHomeworkItemStudent.vue
  src/components/molecules/vHomeworkItemTeacher.unit.js
  src/components/molecules/vHomeworkItemTeacher.vue
  src/components/organisms/DataFilter/DataFilterSelect.vue
  src/components/organisms/HomeworksDashboardMain.stories.js
  src/components/organisms/HomeworksDashboardMain.unit.js
  src/components/organisms/HomeworksDashboardMain.vue
  src/components/organisms/HomeworksDashboardStudent.vue
  src/components/organisms/HomeworksDashboardTeacher.unit.js
  src/components/organisms/HomeworksDashboardTeacher.vue
  src/components/organisms/HomeworksList.stories.js
  src/components/organisms/HomeworksList.vue
  src/layouts/defaultVuetify.vue
  src/pages/tasks/assigned.unit.js
  src/pages/tasks/assigned.vue
  src/pages/tasks/open.unit.js
  src/pages/tasks/open.vue
  src/plugins/directives.js
  src/store/homeworks.js
  src/store/homeworks.unit.js
  src/utils/sidebarBaseItems.js
  stories/mockData/Homeworks.js
  tests/screenshot/__image_snapshots__/0-vuetify-homeworks-homeworkslist-homeworkslist-student_1-snap.png
  tests/screenshot/__image_snapshots__/0-vuetify-homeworks-homeworkslist-homeworkslist-teacher_1-snap.png
  tests/screenshot/__image_snapshots__/0-vuetify-homeworks-templates-task-dashboard-student_1-snap.png
  tests/screenshot/__image_snapshots__/0-vuetify-homeworks-templates-task-dashboard-teacher_1-snap.png
  tests/unit/__snapshots__/components/molecules/vHomeworkItemTeacher.unit.js.snap
Labels: size/XL

#1826 changed multiselect style to solo and rounded
  src/components/organisms/HomeworksDashboardMain.vue
  tests/screenshot/__image_snapshots__/0-vuetify-homeworks-templates-task-dashboard-student_1-snap.png
  tests/screenshot/__image_snapshots__/0-vuetify-homeworks-templates-task-dashboard-teacher_1-snap.png
Labels: size/XS

#1812 SC-9158 Fix launch config to debug single test
  .vscode/launch.json
  CHANGELOG.md
Labels: size/XS

#1836 OPS-2574 - Removeing autodeployed branches for developers if branch deleted
  .github/workflows/clean.yml
  CHANGELOG.md
Labels: size/S, waiting for review

#1834 Feature/sc 9108 refactor news page
  .vscode/settings.json
  CHANGELOG.md
  jest.config.js
  nuxt.config.js
  package-lock.json
  package.json
  src/.nuxtignore
  src/components/organisms/FormNews.unit.js
  src/components/organisms/FormNews.vue
  src/pages/news/_id/edit.vue
  src/pages/news/new.vue
  src/plugins/axios-accessor.ts
  src/plugins/datetime.js
  src/serverMiddleware/routes.js
  src/store/index.ts
  src/store/ldap-config.js
  src/store/news.js
  src/store/news.ts
  src/store/news.unit.ts
  src/utils/api.ts
  tests/plugins/datetime.unit.js
  tests/unit/setup.js
  tsconfig.template.js
Labels: size/XL

#1845 SC-9217 toggle() in vCustomDoublePanels
  CHANGELOG.md
  src/components/molecules/vCustomDoublePanels.unit.js
  src/components/molecules/vCustomDoublePanels.vue
  src/components/organisms/HomeworksDashboardStudent.vue
  src/components/organisms/HomeworksDashboardTeacher.vue
Labels: run-e2e-tests, size/M

#1849 SC-9221 changed contact data in imprint
  CHANGELOG.md
  locale/de.json
  locale/en.json
  locale/es.json
  src/components/templates/impressum.vue
  src/themes/brb/components/templates/impressum.vue
  src/themes/n21/components/templates/impressum.vue
  src/themes/open/templates/impressum.vue
  src/themes/thr/components/templates/impressum.vue
Labels: size/M

#1850 SC-9175 removing old and future classes from class filter
  CHANGELOG.md
  src/utils/adminFilter.js
Labels: size/XS

#1847 SC-8915 add axios openapi client
  .vscode/launch.json
  generate-client.js
  openapitools.json
  package-lock.json
  package.json
  src/clients/server/v3/.openapi-generator-ignore
  src/clients/server/v3/.openapi-generator/FILES
  src/clients/server/v3/.openapi-generator/VERSION
  src/clients/server/v3/README.md
  src/clients/server/v3/api.ts
  src/clients/server/v3/base.ts
  src/clients/server/v3/common.ts
  src/clients/server/v3/configuration.ts
  src/clients/server/v3/index.ts
Labels: WIP, size/XXL

#1851 Task/sc 9226 imprint change brb
  src/themes/brb/components/templates/impressum.vue
Labels: size/L

#1848 SC-9053 add checkboxes back
  src/pages/administration/students/new.vue
  src/pages/administration/teachers/new.vue
Labels: size/XS
