Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2022-04, with the labels that each got.

#2115 BC-1461 - Implement task functions into rooms view
  locale/de.json
  locale/en.json
  locale/es.json
  src/components/molecules/RoomTaskCard.unit.ts
  src/components/molecules/RoomTaskCard.vue
  src/components/templates/RoomDashboard.unit.ts
  src/components/templates/RoomDashboard.vue
Labels: waiting for review

#2120 BC-1596 changed wording on lesson share modal
  locale/de.json
  locale/en.json
  locale/es.json
Labels: waiting for review

#2117 BC-1408 - enabling school admin feature toggles
  src/components/atoms/vCustomSwitch.vue
  src/components/organisms/administration/GeneralSettings.vue
  src/components/organisms/administration/PrivacySettings.unit.js
  src/components/organisms/administration/PrivacySettings.vue
  src/pages/administration/school-settings.vue
  src/store/auth.ts
Labels: run tests

#2133 BC-1578 Adjustment on Links to the help-area
  src/layouts/legacyLoggedIn.vue
Labels: waiting for review

#2109 Feature/n21 51 custom login link
  locale/de.json
  locale/en.json
  locale/es.json
  locale/ua.json
  src/components/organisms/administration/AuthSystems.unit.js
  src/components/organisms/administration/AuthSystems.vue
  src/store/env-config.ts
  src/store/types/env-config.ts
Labels: ready to merge

#2135 BC-1595 - Change empty state on room overview
  locale/de.json
  locale/en.json
  locale/es.json
  locale/ua.json
  src/assets/img/empty-state/topics-empty-state.svg
  src/components/templates/RoomDashboard.unit.ts
  src/components/templates/RoomDashboard.vue
  src/pages/rooms/_id/index.unit.ts
  src/store/room.ts
  src/store/room.unit.ts
Labels: waiting for review, UX Review needed

#2140 BC-1667 - remove auto reviewer assignment by pullapprove
  .pullapprove.yml
Labels: waiting for review

#2131 BC-1393 - Replace current course detail page
  docs/0-GettingStarted/1-Build.md
  locale/de.json
  locale/en.json
  locale/es.json
  locale/ua.json
  src/components/atoms/vRoomAvatar.unit.ts
  src/components/atoms/vRoomAvatar.vue
  src/components/molecules/ImportLessonModal.vue
  src/components/molecules/ImportModal.vue
  src/components/molecules/RoomLessonCard.unit.ts
  src/components/molecules/RoomLessonCard.vue
  src/components/molecules/RoomTaskCard.unit.ts
  src/components/molecules/RoomTaskCard.vue
  src/pages/rooms/_id/index.unit.ts
  src/pages/rooms/_id/index.vue
  src/store/types/env-config.ts
Labels: waiting for review

#2142 BC-1465 - Label lesson cards
  src/components/atoms/vRoomAvatar.vue
  src/components/molecules/RoomLessonCard.unit.ts
  src/components/molecules/RoomLessonCard.vue
  src/components/molecules/RoomTaskCard.unit.ts
  src/components/molecules/RoomTaskCard.vue
Labels: waiting for review

#2144 BC-1386: Missing active state on Courses
  docs/0-GettingStarted/1-Build.md
  src/components/legacy/TheSidebar.unit.js
  src/components/legacy/TheSidebar.vue
  src/layouts/legacyLoggedIn.unit.js
  src/layouts/legacyLoggedIn.vue
  src/store/types/env-config.ts
  src/utils/sidebarBaseItems.js
Labels: waiting for review
