Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2022-01, with the labels that each got.

#2013 Feature/bc 999 update status pages
  ansible/roles/nuxt-client-core/templates/configmap.yml.j2
  docs/0-GettingStarted/1-Build.md
  src/components/legacy/TheFooter.unit.js
  src/components/legacy/TheFooter.vue
  src/layouts/legacyLoggedIn.unit.js
  src/store/env-config.ts
  src/store/env-config.unit.ts
  src/store/filePaths.unit.ts
  src/store/types/env-config.ts
  src/themes/default/components/legacy/TheFooter.vue
Labels: waiting for review, run tests

#2014 Feature/BC-919 - Navigation rooms overview
  docs/0-GettingStarted/1-Build.md
  src/components/legacy/TheSidebar.unit.js
  src/components/legacy/TheSidebar.vue
  src/layouts/legacyLoggedIn.unit.js
  src/layouts/legacyLoggedIn.vue
  src/store/types/env-config.ts
  src/utils/sidebarBaseItems.js
Labels: waiting for review, run tests

#2018 version 27.0.0
  package-lock.json
  package.json
Labels: waiting for review

#2017 BC-1006 - Meta file for the roles
  ansible/roles/nuxt-client-core/meta/main.yml
  ansible/roles/nuxt-client-ldap/meta/main.yml
Labels: waiting for review

#2020 feature/BC-1084-dev-nuxt-value
  ansible/roles/nuxt-client-core/templates/configmap.yml.j2
  src/components/legacy/TheFooter.vue
  src/components/templates/TasksDashboardMain.vue
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
  src/pages/rooms-overview.vue
  src/store/env-config.ts
  src/store/types/env-config.ts
  src/themes/default/components/legacy/TheFooter.vue
Labels: waiting for review, run tests

#2026 BC-1087 - update configmap to an loop
  ansible/roles/nuxt-client-core/templates/configmap.yml.j2
Labels: waiting for review

#2012 BC-538 - task item with edit action
  locale/de.json
  locale/en.json
  locale/es.json
  src/components/molecules/vTaskItemTeacher.unit.js
  src/components/molecules/vTaskItemTeacher.vue
  src/components/templates/TasksDashboardMain.vue
  tests/unit/__snapshots__/components/molecules/vTaskItemTeacher.unit.js.snap
Labels: run tests
