Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2022-03, with the labels that each got.

#2068 BC-1141 - remove sentry from nuxt-client
  .github/dependabot.yml
  ansible/roles/nuxt-client-core/templates/configmap-files.yml.j2
  docs/0-GettingStarted/1-Build.md
  nuxt.config.js
  package-lock.json
  package.json
  sentry.config.js
  src/plugins/sentry.js
Labels: waiting for review

#2066 BC-1259 update file storage api client
  nuxt.config.js
  src/fileStorageApi/v3/api.ts
  src/pages/poc-files/index.vue
  src/serverApi/v3/api.ts
  src/store/files-poc.ts
Labels: run tests

#2069 BC-180 - added delete task action
  locale/de.json
  locale/en.json
  locale/es.json
  src/components/molecules/TaskItem.unit.js
  src/components/molecules/TaskItem.vue
  src/components/molecules/TaskItemMenu.unit.js
  src/components/molecules/TaskItemMenu.vue
  src/components/molecules/TaskItemStudent.unit.js
  src/components/molecules/TaskItemStudent.vue
  src/components/molecules/TaskItemTeacher.unit.js
  src/components/molecules/TaskItemTeacher.vue
  src/components/organisms/TasksList.vue
  src/serverApi/v3/api.ts
  src/store/tasks.ts
  src/store/tasks.unit.ts
Labels: run tests

#2072 BC-557 - add copy action to task
  locale/de.json
  locale/en.json
  locale/es.json
  src/components/molecules/TaskItemMenu.unit.js
  src/components/molecules/TaskItemMenu.vue
  src/components/templates/TasksDashboardTeacher.vue
Labels: run tests

#2071 BC-1050 - removed everything relating to datasources
  docs/1-Tutorials/WorkingWithOurUistate.md
  locale/de.json
  locale/en.json
  locale/es.json
  src/assets/icons/datasource-add.svg
  src/assets/icons/datasource-check.svg
  src/assets/icons/datasource-error.svg
  src/assets/icons/datasource-export.svg
  src/assets/icons/datasource-import.svg
  src/assets/icons/datasource-remove.svg
  src/assets/icons/datasource-sync.svg
  src/assets/img/datasources/logo-ldap.svg
  src/assets/img/datasources/logo-rss.svg
  src/assets/img/datasources/logo-webuntis-text.svg
  src/assets/img/datasources/logo-webuntis.png
  src/components/molecules/AccountCard.unit.js
  src/components/molecules/AccountCard.vue
  src/components/molecules/DatasourceCard.unit.js
  src/components/molecules/FabFloating.unit.js
  src/components/molecules/FabFloating.vue
  src/components/molecules/FabIcon.unit.js
  src/components/molecules/FabIcon.vue
  src/components/molecules/ResponsiveIconButton.unit.js
  src/components/molecules/ResponsiveIconButton.vue
  src/components/organisms/DatasourceRunWebuntis.unit.js
  src/components/organisms/DatasourceRunWebuntis.vue
  src/components/organisms/FormDatasourceLogin.unit.js
  src/components/organisms/FormDatasourceLogin.vue
  src/components/organisms/FormDatasourceLoginWebuntis.unit.js
  src/components/organisms/FormDatasourceLoginWebuntis.vue
  src/pages/administration/datasources/_datasource/run/_run.vue
  src/pages/administration/datasources/index.vue
  src/pages/administration/datasources/ldap/new.vue
  src/pages/administration/datasources/new.vue
  src/pages/administration/datasources/rss/new.vue
  src/pages/administration/datasources/webuntis/_id/edit.vue
  src/pages/administration/datasources/webuntis/new.vue
  src/serverMiddleware/routes.js
  src/store/datasourceRuns.js
  src/store/datasources.js
  src/store/webuntis-metadata.js
Labels: run tests

#2053 BC-1316 - remove conflicting vue-ripple-directive plugin
  package-lock.json
  package.json
  src/components/atoms/vCustomSwitch.vue
  src/components/legacy/TheTopBar.vue
  src/components/molecules/TaskItemStudent.vue
  src/components/molecules/TaskItemTeacher.vue
  src/components/organisms/administration/SchoolPolicies.vue
  src/components/organisms/administration/SchoolPolicyFormDialog.vue
  src/components/organisms/vCustomDialog.vue
  src/pages/administration/migration/index.vue
  src/pages/rooms-overview.vue
  src/plugins/directives.js
Labels: waiting for review

#2088 Bump url-parse from 1.5.3 to 1.5.10
  package-lock.json
Labels: dependencies, waiting for review

#2093 Bump prismjs from 1.25.0 to 1.27.0
  package-lock.json
Labels: dependencies, waiting for review

#2084 BC-1342 - Add task or lesson to the room board
  locale/de.json
  locale/en.json
  locale/es.json
  src/components/atoms/vCustomFab.vue
  src/components/molecules/ImportLessonModal.unit.ts
  src/components/molecules/ImportLessonModal.vue
  src/components/molecules/ImportModal.unit.ts
  src/components/molecules/RoomLessonCard.unit.ts
  src/components/molecules/RoomLessonCard.vue
  src/components/templates/RoomDashboard.unit.ts
  src/components/templates/RoomDashboard.vue
  src/pages/rooms/_id/index.unit.ts
  src/pages/rooms/_id/index.vue
  src/store/room.ts
  src/store/room.unit.ts
  src/store/types/room.ts
Labels: waiting for review

#2086 BC-1407 - confirm dialog before deleting task
  locale/de.json
  locale/en.json
  locale/es.json
  src/components/molecules/TaskItemMenu.unit.js
  src/components/molecules/TaskItemMenu.vue
  src/components/molecules/TaskItemTeacher.vue
  src/components/organisms/administration/AuthSystems.vue
  src/components/organisms/vCustomDialog.vue
  src/themes/base/styles/vuetify-custom.scss
Labels: run tests

#2089 Bc 1447 language key fab
  locale/de.json
  locale/en.json
  locale/es.json
  src/components/templates/TasksDashboardMain.vue
  src/pages/administration/students/index.vue
  src/pages/administration/teachers/index.vue
  src/pages/rooms-overview.vue
  src/pages/rooms/_id/index.vue
Labels: size/S

#2101 Bump minimist from 1.2.5 to 1.2.6
  package-lock.json
Labels: dependencies, waiting for review

#2112 27.11.1 - Fix url for docs to docs.dbildungscloud.de
  .github/pull_request_template.md
  ansible/roles/nuxt-client-core/templates/configmap-files.yml.j2
  docs/1-Tutorials/WritingTests/EndToEndTests.md
  docs/3-BeginnerGuide/1-Was-kannst-Du-fuer-die-Schul-Cloud-tun.md
  http-headers.config.js
  package-lock.json
  package.json
  src/components/molecules/AdminTableLegend.vue
  src/components/organisms/DataTable/TableHeadRow.vue
  src/components/organisms/administration/PrivacySettings.vue
  src/pages/administration/ldap/config.vue
Labels: waiting for review

#2114 27.11.1 - Fix url for docs to docs.dbildungscloud.de ( #2112 )
  .github/pull_request_template.md
  ansible/roles/nuxt-client-core/templates/configmap-files.yml.j2
  docs/1-Tutorials/WritingTests/EndToEndTests.md
  docs/3-BeginnerGuide/1-Was-kannst-Du-fuer-die-Schul-Cloud-tun.md
  http-headers.config.js
  package-lock.json
  package.json
  src/components/molecules/AdminTableLegend.vue
  src/components/organisms/DataTable/TableHeadRow.vue
  src/components/organisms/administration/PrivacySettings.vue
  src/pages/administration/ldap/config.vue
Labels: waiting for review
