Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2024-11, with the labels that each got.

#3428 BC-8100 - Create Room Participants State
  src/locales/de.ts
  src/locales/en.ts
  src/locales/es.ts
  src/locales/uk.ts
  src/modules/data/room/index.ts
  src/modules/data/room/mockParticipantsList.ts
  src/modules/data/room/roomParticipants/mockParticipantsList.ts
  src/modules/data/room/roomParticipants/participants.composable.ts
  src/modules/data/room/roomParticipants/participants.composable.unit.ts
  src/modules/data/room/roomParticipants/types.ts
  src/modules/feature/room/RoomParticipants/AddParticipant.unit.ts
  src/modules/feature/room/RoomParticipants/AddParticipants.vue
  src/modules/feature/room/RoomParticipants/ParticipantsTable.unit.ts
  src/modules/feature/room/RoomParticipants/ParticipantsTable.vue
  src/modules/page/room/RoomParticipants.page.unit.ts
  src/modules/page/room/RoomParticipants.page.vue
  src/modules/util/board/index.ts
  src/serverApi/v3/api.ts
  tests/test-utils/factory/index.ts
  tests/test-utils/factory/room/index.ts
  tests/test-utils/factory/room/roomParticipantsFactory.ts
Labels: auto-extend-activation-time

#3439 BC-8353 - UX adjustments remove participant dialog
  src/components/molecules/TaskItemMenu.vue
  src/components/organisms/vCustomDialog.vue
  src/locales/de.ts
  src/locales/en.ts
  src/locales/es.ts
  src/locales/uk.ts
  src/modules/feature/media-shelf/MediaBoardLineMenu.unit.ts
  src/modules/feature/media-shelf/MediaBoardLineMenu.vue
  src/modules/feature/news-form/FormNews.vue
  src/modules/feature/room/RoomParticipants/ParticipantsTable.vue
  src/modules/page/room/RoomParticipants.page.vue
  src/pages/administration/ClassOverview.page.vue
  src/pages/course-rooms/CourseRoomDetails.page.vue
  src/pages/course-rooms/tools/RoomExternalToolsSection.vue
Labels: waiting for review

#3443 BC-8371 - add i18n for vuetify components
  config/webpack/webpack.common.js
  sonar-project.properties
  src/locales/schema.ts
  src/main.ts
  src/modules/feature/room/BoardTile.vue
  src/modules/ui/date-time-picker/DatePicker.vue
  src/plugins/i18n.ts
  src/plugins/vuetify.ts
  tsconfig.json
  types/shims-tsx.d.ts
  types/shims-vue.d.ts
  types/shims-vuetify.d.ts
  types/vuetify-locale-de.d.ts
Labels: waiting for review

#3455 BC-8426 - Improve A11y manage members page
  src/components/templates/DefaultWireframe.vue
  src/locales/de.ts
  src/locales/en.ts
  src/locales/es.ts
  src/locales/uk.ts
  src/modules/feature/room/RoomMembers/MembersTable.vue
  src/modules/page/room/RoomMembers.page.vue
Labels: waiting for review, auto-extend-activation-time

#3463 BC-8329 - fix meta tag extractor
  src/modules/data/board/Board.store.ts
  src/modules/data/board/Board.store.unit.ts
  src/modules/data/board/boardActions/boardSocketApi.composable.ts
  src/modules/data/board/boardActions/boardSocketApi.composable.unit.ts
  src/modules/data/board/cardActions/cardSocketApi.composable.ts
  src/modules/data/board/cardActions/cardSocketApi.composable.unit.ts
  src/modules/feature/board-link-element/components/LinkContentElement.unit.ts
  src/modules/feature/board-link-element/components/LinkContentElement.vue
  src/modules/feature/board-link-element/composables/MetaTagExtractorApi.composable.ts
  src/modules/feature/board-link-element/composables/MetaTagExtractorApi.composable.unit.ts
  src/modules/feature/board/board/Board.vue
  src/serverApi/v3/api.ts
Labels: auto-extend-activation-time
