Repository hpi-schul-cloud/nuxt-client, pull requests merged in 2025-02, with the labels that each got.

#3544 BC-8265 - Name of room is cut off
  src/modules/feature/room/RoomTile.vue
Labels: WIP, waiting for review

#3552 BC-8569 - Handover of Owner Role
  src/locales/de.ts
  src/locales/en.ts
  src/locales/es.ts
  src/locales/uk.ts
  src/modules/data/room/roomMembers/roomMembers.composable.ts
  src/modules/data/room/roomMembers/roomMembers.composable.unit.ts
  src/modules/feature/room/RoomMembers/ChangeRole.unit.ts
  src/modules/feature/room/RoomMembers/ChangeRole.vue
  src/modules/feature/room/RoomMembers/MembersTable.vue
  src/modules/page/room/RoomMembers.page.unit.ts
  src/modules/page/room/RoomMembers.page.vue
  src/serverApi/v3/api.ts
Labels: auto-extend-activation-time

#3572 BC-8893 - Update typescript and typescript-eslint
  package-lock.json
  package.json
  src/components/templates/TasksDashboardMain.unit.ts
  src/components/templates/TasksDashboardStudent.unit.ts
  src/modules/feature/board-link-element/components/LinkContentElement.unit.ts
Labels: waiting for review
